part of 'postgrest_typed_builder.dart';

/// Converts between the elements of a pgvector `vector` or `halfvec` column
/// and the text PostgREST carries them as.
///
/// PostgREST serializes these values as their Postgres literal,
/// `[0.1,0.2,0.3]`, and accepts the same literal on insert and update.
///
/// ```dart
/// postgrestVector.encode([0.5, -2.25]) // [0.5,-2.25]
/// postgrestVector.decode('[0.5,-2.25]') // [0.5, -2.25]
/// ```
///
/// pgvector stores at least one finite element, so [encode] throws an
/// [ArgumentError] and [decode] a [FormatException] for an empty vector or
/// one holding `NaN` or an infinity.
///
/// The shared instance is [postgrestVector]. Filters on a
/// [PostgrestVectorColumn] or [PostgrestNullableVectorColumn] and the rows
/// generated by `supabase_typegen` go through it.
@experimental
final class PostgrestVectorCodec extends Codec<List<double>, String> {
  /// Creates the codec; prefer the shared [postgrestVector].
  const PostgrestVectorCodec();

  @override
  Converter<List<double>, String> get encoder => const _VectorEncoder();

  @override
  Converter<String, List<double>> get decoder => const _VectorDecoder();
}

/// The pgvector codec, see [PostgrestVectorCodec].
@experimental
const postgrestVector = PostgrestVectorCodec();

final class _VectorEncoder extends Converter<List<double>, String> {
  const _VectorEncoder();

  @override
  String convert(List<double> input) {
    if (input.isEmpty || !input.every((element) => element.isFinite)) {
      throw ArgumentError.value(
        input,
        'input',
        'A vector needs at least one element, and every element finite',
      );
    }
    return '[${input.join(',')}]';
  }
}

final class _VectorDecoder extends Converter<String, List<double>> {
  const _VectorDecoder();

  @override
  List<double> convert(String input) {
    final literal = input.trim();
    if (!literal.startsWith('[') || !literal.endsWith(']')) {
      throw FormatException('Not a vector literal', input);
    }
    final body = literal.substring(1, literal.length - 1);
    return [
      for (final element in body.split(','))
        switch (double.tryParse(element.trim())) {
          final double value when value.isFinite => value,
          _ => throw FormatException('Invalid vector element', input),
        },
    ];
  }
}

/// A stored `NOT NULL` pgvector `vector` or `halfvec` column of the table
/// whose rows are [Row].
///
/// Compared with a `List<double>` operand, sent as the vector literal
/// `[0.1,0.2]` instead of the array literal a [PostgrestColumn] of a list
/// type sends.
@experimental
final class PostgrestVectorColumn<Row>
    extends PostgrestColumn<Row, List<double>> {
  /// Creates a reference to the vector column called [name] in the database.
  const PostgrestVectorColumn(super.name);
}

/// A stored pgvector `vector` or `halfvec` column the database allows to be
/// `NULL`, see [PostgrestVectorColumn].
@experimental
final class PostgrestNullableVectorColumn<Row>
    extends PostgrestNullableColumn<Row, List<double>> {
  /// Creates a reference to the nullable vector column called [name] in the
  /// database.
  const PostgrestNullableVectorColumn(super.name);
}
