part of 'postgrest_typed_builder.dart';

/// Converts between the bytes of a `bytea` column and the text PostgREST
/// carries them as.
///
/// PostgREST serializes `bytea` values in the database's `bytea_output`
/// format, hex by default (`\x48656c6c6f`), and Postgres accepts either
/// format as input. [encode] renders hex; [decode] reads both hex and the
/// escape format (`Hello`, `\\`, `\000`).
///
/// ```dart
/// postgrestBytea.encode(Uint8List.fromList([72, 105])) // \x4869
/// postgrestBytea.decode(r'\x4869')                      // [72, 105]
/// ```
///
/// The shared instance is [postgrestBytea]. Filter values of type [Uint8List]
/// and the rows generated by `supabase_typegen` go through it.
@experimental
final class PostgrestByteaCodec extends Codec<List<int>, String> {
  /// Creates the codec; prefer the shared [postgrestBytea].
  const PostgrestByteaCodec();

  @override
  Converter<List<int>, String> get encoder => const _ByteaEncoder();

  @override
  Converter<String, Uint8List> get decoder => const _ByteaDecoder();

  /// Decodes the `bytea` literal [encoded], hex or escape format.
  ///
  /// Throws a [FormatException] when [encoded] is neither.
  @override
  Uint8List decode(String encoded) => decoder.convert(encoded);
}

/// The `bytea` codec, see [PostgrestByteaCodec].
@experimental
const postgrestBytea = PostgrestByteaCodec();

final class _ByteaEncoder extends Converter<List<int>, String> {
  const _ByteaEncoder();

  @override
  String convert(List<int> input) => '\\x${hex.encode(input)}';
}

final class _ByteaDecoder extends Converter<String, Uint8List> {
  const _ByteaDecoder();

  @override
  Uint8List convert(String input) => input.startsWith(r'\x')
      ? hex.decoder.convert(input.substring(2))
      : _decodeEscape(input);

  Uint8List _decodeEscape(String input) {
    final bytes = <int>[];
    var index = 0;
    while (index < input.length) {
      final unit = input.codeUnitAt(index);
      if (unit > 0x7f) {
        throw FormatException('Not a bytea literal', input, index);
      }
      if (unit != 0x5c) {
        bytes.add(unit);
        index++;
        continue;
      }
      if (index + 1 < input.length && input.codeUnitAt(index + 1) == 0x5c) {
        bytes.add(0x5c);
        index += 2;
        continue;
      }
      if (index + 3 >= input.length) {
        throw FormatException('Incomplete escape sequence', input, index);
      }
      final value = int.tryParse(
        input.substring(index + 1, index + 4),
        radix: 8,
      );
      if (value == null || value > 0xff) {
        throw FormatException('Invalid escape sequence', input, index);
      }
      bytes.add(value);
      index += 4;
    }
    return Uint8List.fromList(bytes);
  }
}
