part of 'postgrest_typed_builder.dart';

/// Converts between the bytes of a `bytea` column and the text PostgREST
/// carries them as.
///
/// PostgREST serializes `bytea` values in the database's `bytea_output`
/// format, hex by default (`\x48656c6c6f`), and Postgres accepts either
/// format as input. [encode] renders hex; [decode] reads both hex and the
/// escape format (`Hello`, `\\`, `\000`).
///
/// ```dart
/// postgrestBytea.encode(Uint8List.fromList([72, 105])) // \x4869
/// postgrestBytea.decode(r'\x4869')                      // [72, 105]
/// ```
///
/// The shared instance is [postgrestBytea]. Filter values of type [Uint8List]
/// and the rows generated by `supabase_typegen` go through it.
@experimental
final class PostgrestByteaCodec extends Codec<List<int>, String> {
  /// Creates the codec; prefer the shared [postgrestBytea].
  const PostgrestByteaCodec();

  @override
  Converter<List<int>, String> get encoder => const _ByteaEncoder();

  @override
  Converter<String, Uint8List> get decoder => const _ByteaDecoder();

  /// Decodes the `bytea` literal [encoded], hex or escape format.
  ///
  /// Throws a [FormatException] when [encoded] is neither.
  @override
  Uint8List decode(String encoded) => decoder.convert(encoded);
}

/// The `bytea` codec, see [PostgrestByteaCodec].
@experimental
const postgrestBytea = PostgrestByteaCodec();

const _hexDigits = '0123456789abcdef';

final class _ByteaEncoder extends Converter<List<int>, String> {
  const _ByteaEncoder();

  @override
  String convert(List<int> input) {
    final buffer = StringBuffer(r'\x');
    for (final byte in input) {
      buffer
        ..writeCharCode(_hexDigits.codeUnitAt(byte >> 4))
        ..writeCharCode(_hexDigits.codeUnitAt(byte & 0x0f));
    }
    return buffer.toString();
  }
}

final class _ByteaDecoder extends Converter<String, Uint8List> {
  const _ByteaDecoder();

  @override
  Uint8List convert(String input) =>
      input.startsWith(r'\x') ? _decodeHex(input) : _decodeEscape(input);

  /// Postgres allows whitespace between the digit pairs of a hex literal,
  /// though not within a pair.
  Uint8List _decodeHex(String input) {
    final bytes = <int>[];
    var index = 2;
    while (index < input.length) {
      final first = input.codeUnitAt(index);
      if (_isWhitespace(first)) {
        index++;
        continue;
      }
      if (index + 1 >= input.length) {
        throw FormatException('Odd number of hex digits', input, index);
      }
      bytes.add(
        (_hexValue(input, index) << 4) | _hexValue(input, index + 1),
      );
      index += 2;
    }
    return Uint8List.fromList(bytes);
  }

  Uint8List _decodeEscape(String input) {
    final bytes = <int>[];
    var index = 0;
    while (index < input.length) {
      final unit = input.codeUnitAt(index);
      if (unit > 0x7f) {
        throw FormatException('Not a bytea literal', input, index);
      }
      if (unit != 0x5c) {
        bytes.add(unit);
        index++;
        continue;
      }
      if (index + 1 < input.length && input.codeUnitAt(index + 1) == 0x5c) {
        bytes.add(0x5c);
        index += 2;
        continue;
      }
      if (index + 3 >= input.length) {
        throw FormatException('Incomplete escape sequence', input, index);
      }
      final value = int.tryParse(
        input.substring(index + 1, index + 4),
        radix: 8,
      );
      if (value == null || value > 0xff) {
        throw FormatException('Invalid escape sequence', input, index);
      }
      bytes.add(value);
      index += 4;
    }
    return Uint8List.fromList(bytes);
  }

  static int _hexValue(String input, int index) {
    final unit = input.codeUnitAt(index);
    if (unit >= 0x30 && unit <= 0x39) return unit - 0x30;
    if (unit >= 0x61 && unit <= 0x66) return unit - 0x61 + 10;
    if (unit >= 0x41 && unit <= 0x46) return unit - 0x41 + 10;
    throw FormatException('Not a hex digit', input, index);
  }

  static bool _isWhitespace(int unit) =>
      unit == 0x20 || unit == 0x09 || unit == 0x0a || unit == 0x0d;
}
