import 'package:postgrest/postgrest.dart';
import 'package:supabase_test/supabase_test.dart';
import 'package:test/test.dart';

const _document = {
  'swagger': '2.0',
  'info': {
    'description': 'This is a dynamic API generated by PostgREST',
    'title': 'PostgREST API',
    'version': '13.0.4',
  },
  'host': '0.0.0.0:3000',
  'basePath': '/',
  'paths': {
    '/': {'get': {}},
    '/users': {'get': {}, 'post': {}},
    '/rpc/get_status': {'post': {}},
  },
  'definitions': {
    'users': {'type': 'object'},
  },
  'parameters': {
    'preferParams': {'name': 'Prefer', 'in': 'header'},
  },
  'externalDocs': {'url': 'https://postgrest.org'},
};

void main() {
  const url = 'https://example.com/rest/v1';
  late MockSupabaseHttpClient httpClient;
  late PostgrestClient postgrest;

  setUp(() {
    httpClient = MockSupabaseHttpClient();
    postgrest = PostgrestClient(
      url,
      headers: {'apikey': 'key'},
      httpClient: httpClient,
    );
  });

  tearDown(() => postgrest.dispose());

  test('requests the document from the PostgREST root', () async {
    httpClient.stub(_document, path: '/rest/v1/');

    await postgrest.getOpenApiSpec();

    final request = httpClient.requests.single;
    expect(request.method, HttpMethod.get.value);
    expect(request.url.toString(), '$url/');
    expect(request.headers['Accept'], 'application/openapi+json');
    expect(request.headers['apikey'], 'key');
    expect(request.headers, isNot(contains('Accept-Profile')));
  });

  test('types the top level of the document', () async {
    httpClient.stub(_document, path: '/rest/v1/');

    final spec = await postgrest.getOpenApiSpec();

    expect(spec.swagger, '2.0');
    expect(spec.info, containsPair('title', 'PostgREST API'));
    expect(spec.host, '0.0.0.0:3000');
    expect(spec.basePath, '/');
    expect(spec.paths.keys, ['/', '/users', '/rpc/get_status']);
    expect(spec.paths['/users'], containsPair('post', {}));
    expect(spec.definitions, containsPair('users', {'type': 'object'}));
    expect(spec.parameters?.keys, ['preferParams']);
  });

  test('keeps the fields it does not type reachable', () async {
    httpClient.stub(_document, path: '/rest/v1/');

    final spec = await postgrest.getOpenApiSpec();

    expect(spec.toJson(), _document);
    expect(spec.toJson()['externalDocs'], {'url': 'https://postgrest.org'});
  });

  test('cannot be changed through the document or the typed fields', () async {
    httpClient.stub(_document, path: '/rest/v1/');

    final spec = await postgrest.getOpenApiSpec();

    expect(() => spec.toJson()['swagger'] = '3.0', throwsUnsupportedError);
    expect(
      () => spec.toJson()['info']['title'] = 'changed',
      throwsUnsupportedError,
    );
    expect(() => spec.info['title'] = 'changed', throwsUnsupportedError);
    expect(() => spec.paths['/users']!['get'] = null, throwsUnsupportedError);
    expect(
      () => spec.paths['/users']!['get']['tags'] = ['x'],
      throwsUnsupportedError,
    );
    expect(spec.toJson(), _document);
  });

  test('leaves out the optional fields a root spec override omits', () async {
    httpClient.stub({
      'swagger': '2.0',
      'info': {'title': 'Custom', 'version': '1'},
    }, path: '/rest/v1/');

    final spec = await postgrest.getOpenApiSpec();

    expect(spec.paths, isEmpty);
    expect(spec.host, isNull);
    expect(spec.basePath, isNull);
    expect(spec.definitions, isNull);
    expect(spec.parameters, isNull);
  });

  test('describes the schema the client was created with', () async {
    postgrest = PostgrestClient(url, schema: 'billing', httpClient: httpClient);
    httpClient.stub(_document, path: '/rest/v1/');

    await postgrest.getOpenApiSpec();

    expect(httpClient.requests.single.headers['Accept-Profile'], 'billing');
  });

  test('describes the schema selected with schema()', () async {
    httpClient.stub(_document, path: '/rest/v1/');

    await postgrest.schema('personal').getOpenApiSpec();

    expect(httpClient.requests.single.headers['Accept-Profile'], 'personal');
  });

  test('rejects a document that is not OpenAPI 2.0', () async {
    httpClient.stub({'openapi': '3.0.0'}, path: '/rest/v1/');

    await expectLater(
      () => postgrest.getOpenApiSpec(),
      throwsA(isA<FormatException>()),
    );
  });

  test('rejects paths that are not objects', () async {
    httpClient.stub({
      'swagger': '2.0',
      'info': {},
      'paths': {'/users': 'not an object'},
    }, path: '/rest/v1/');

    await expectLater(
      () => postgrest.getOpenApiSpec(),
      throwsA(isA<FormatException>()),
    );
  });

  test('throws when PostgREST answers with an error', () async {
    httpClient.stub(
      {'message': 'permission denied', 'code': '42501'},
      path: '/rest/v1/',
      statusCode: 401,
    );

    await expectLater(
      () => postgrest.getOpenApiSpec(),
      throwsA(
        isA<PostgrestApiException>()
            .having((exception) => exception.statusCode, 'statusCode', 401)
            .having((exception) => exception.errorCode, 'errorCode', '42501'),
      ),
    );
  });

  test('retries a transient failure like every other read', () async {
    postgrest = PostgrestClient(
      url,
      httpClient: httpClient,
      retryOptions: const SupabaseRetryOptions(initialDelay: Duration.zero),
    );
    httpClient.stubStatuses([503, 200], body: _document, path: '/rest/v1/');

    final spec = await postgrest.getOpenApiSpec();

    expect(spec.swagger, '2.0');
    expect(httpClient.requests, hasLength(2));
    expect(httpClient.requests.last.headers['X-Retry-Count'], '1');
  });

  test('honors the per-request builder overrides', () async {
    httpClient.stub(_document, path: '/rest/v1/');

    await postgrest
        .getOpenApiSpec()
        .setHeader('Authorization', 'Bearer other')
        .retry(enabled: false);

    expect(
      httpClient.requests.single.headers['Authorization'],
      'Bearer other',
    );
  });
}
