name: supabase
description: A dart client for Supabase. This client makes it simple for developers to build secure and scalable products.
version: 3.0.0-dev.2
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/supabase'
issue_tracker: 'https://github.com/supabase/supabase-flutter/issues'
documentation: 'https://supabase.com/docs/reference/dart/introduction'
topics:
  - supabase
  - backend
  - database
  - auth
  - api

environment:
  sdk: '>=3.9.0 <4.0.0'

resolution: workspace

dependencies:
  http: ^1.6.0
  meta: ^1.7.0
  postgrest: 3.0.0-dev.2
  supabase_auth: 3.0.0-dev.2
  supabase_common: 3.0.0-dev.1
  supabase_functions: 3.0.0-dev.2
  supabase_realtime: 3.0.0-dev.2
  supabase_storage: 3.0.0-dev.2
  yet_another_json_isolate: 3.0.0
  logging: ^1.3.0

dev_dependencies:
  supabase_lints: ^0.1.2
  supabase_testing: 0.1.1
  test: ^1.25.0
  web_socket_channel: '>=3.0.0 <4.0.0'