# docker-compose.yml
version: '3'
services:
  gotrue: # Signup enabled, autoconfirm on
    image: supabase/auth:v2.151.0
    ports:
      - '9998:9998'
    environment:
      GOTRUE_JWT_SECRET: '37c304f8-51aa-419a-a1af-06154e63707a'
      GOTRUE_JWT_EXP: 3600
      GOTRUE_DB_DRIVER: postgres
      DB_NAMESPACE: auth
      GOTRUE_API_HOST: 0.0.0.0
      PORT: 9998
      GOTRUE_DISABLE_SIGNUP: 'false'
      API_EXTERNAL_URL: http://localhost:9998
      GOTRUE_SITE_URL: http://localhost:9998
      GOTRUE_MAILER_AUTOCONFIRM: 'true'
      GOTRUE_SMS_AUTOCONFIRM: 'true'
      GOTRUE_LOG_LEVEL: DEBUG
      GOTRUE_OPERATOR_TOKEN: super-secret-operator-token
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres?sslmode=disable'
      GOTRUE_EXTERNAL_PHONE_ENABLED: 'true'
      GOTRUE_EXTERNAL_GOOGLE_ENABLED: 'true'
      GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: 53566906701-bmhc1ndue7hild39575gkpimhs06b7ds.apps.googleusercontent.com
      GOTRUE_EXTERNAL_GOOGLE_SECRET: Sm3s8RE85rDcS36iMy8YjrpC
      GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: http://localhost:9998/callback
      GOTRUE_SECURITY_MANUAL_LINKING_ENABLED: 'true'
      GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED: 'true'

    depends_on:
      - db
    restart: on-failure
  rest:
    image: postgrest/postgrest:v11.2.2
    ports:
      - '3000:3000'
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_DB_SCHEMAS: auth
      PGRST_DB_EXTRA_SEARCH_PATH: extensions
      PGRST_DB_ANON_ROLE: postgres
      PGRST_DB_PLAN_ENABLED: 1
      PGRST_DB_TX_END: commit-allow-override
    depends_on:
      - db
  db:
    image: supabase/postgres:15.1.0.37
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
