-- Schema behind test/fixtures/generator_metadata.json.
--
-- Apply this to a disposable Postgres database and run
-- tool/regenerate_fixture.ts to refresh the fixture; the exact commands are
-- documented at the top of that script.

CREATE TYPE public.mood AS ENUM ('happy', 'very happy', 'sad');

CREATE TABLE public.authors (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);
ALTER TABLE public.authors ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.books (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  author_id bigint NOT NULL REFERENCES public.authors (id),
  price numeric,
  rating double precision,
  in_print boolean NOT NULL DEFAULT true,
  mood public.mood,
  tags text[],
  page_counts integer[],
  metadata jsonb,
  cover_uuid uuid,
  cover_image bytea,
  published_on date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamp
);
ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.books IS 'Books available in the library';
COMMENT ON COLUMN public.books.created_at IS 'When the row was created';

-- A read-only aggregating view: not auto-updatable, so it must generate no
-- insert or update surface.
CREATE VIEW public.author_stats AS
SELECT
  books.author_id,
  count(*) AS book_count
FROM public.books
GROUP BY books.author_id;
COMMENT ON VIEW public.author_stats IS 'Aggregated statistics per author';

-- An auto-updatable view with one computed, non-updatable column
-- (discounted_price), which must be read-only in the generated code.
CREATE VIEW public.book_prices AS
SELECT
  books.id,
  books.title,
  books.price,
  books.price * 0.9 AS discounted_price
FROM public.books;
COMMENT ON VIEW public.book_prices IS 'Prices per book, with the standard discount precomputed';

-- A materialized view: never insertable or updatable.
CREATE MATERIALIZED VIEW public.book_summaries AS
SELECT
  books.id,
  books.title,
  authors.name AS author_name
FROM public.books
JOIN public.authors ON authors.id = books.author_id;
COMMENT ON MATERIALIZED VIEW public.book_summaries IS 'Denormalized book and author names';

-- A join view made insertable only through an INSTEAD OF INSERT trigger:
-- not auto-updatable, so is_updatable is false, but is_insert_enabled is true
-- and its columns are writable.
CREATE VIEW public.book_submissions AS
SELECT
  books.title,
  authors.name AS author_name
FROM public.books
JOIN public.authors ON authors.id = books.author_id;

CREATE FUNCTION public.insert_book_submission() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO public.books (title, author_id)
  VALUES (
    NEW.title,
    (SELECT id FROM public.authors WHERE name = NEW.author_name)
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER book_submissions_insert
INSTEAD OF INSERT ON public.book_submissions
FOR EACH ROW EXECUTE FUNCTION public.insert_book_submission();

-- A second schema: its objects are generated with the schema as a name
-- prefix, a table named like public.books proves the prefixing, and the keys
-- of inventory.stock relate tables within the schema and across schemas.
CREATE SCHEMA inventory;

CREATE TYPE inventory.condition AS ENUM ('new', 'used');

CREATE TABLE inventory.books (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  isbn text NOT NULL
);

CREATE TABLE inventory.stock (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  book_id bigint NOT NULL REFERENCES public.books (id),
  copy_id bigint NOT NULL REFERENCES inventory.books (id),
  condition inventory.condition NOT NULL DEFAULT 'new',
  quantity integer NOT NULL DEFAULT 0
);
COMMENT ON TABLE inventory.stock IS 'Copies held per book';
