// Generated by supabase_typegen 0.3.0 from GeneratorMetadata version 1.
// Do not edit by hand.
//
// Source schemas: evil multiline "schema" name, private, public

// The typed table access API is still experimental.
// ignore_for_file: experimental_member_use

import 'dart:typed_data';

import 'package:postgrest/postgrest.dart';

/// Postgres enum `public.string`.
enum String$ {
  itSATrap('it\'s \$a\u{2028}trap'),
  plain('plain');

  const String$(this.wireName);

  /// The value as stored in the database.
  final String wireName;

  /// Parses the database representation of the enum.
  static String$ fromWire(String wireName) => values.firstWhere(
    (value) => value.wireName == wireName,
    orElse: () => throw ArgumentError.value(
      wireName,
      'wireName',
      'No String\$ value with this wire name',
    ),
  );

  @override
  String toString() => wireName;
}

/// A row of the `postgrest_table` table.
/// first
/// second
/// third $interpolation "quoted"
extension type const PostgrestTableRow(Map<String, dynamic> _json)
    implements Object {
  /// says "hi" \ and $more
  String get quoteNameTail => _json['quote\'name\u{2029}tail'] as String;
  String$? get mood => switch (_json['mood']) {
    null => null,
    final Object value => String$.fromWire(value as String),
  };
  List<double> get samples => (_json['samples'] as List<dynamic>)
      .map((element) => (element as num).toDouble())
      .toList();
  List<String>? get days => (_json['days'] as List<dynamic>?)?.cast();
  Uint8List get postgrestBytea$ =>
      postgrestBytea.decode(_json['postgrest_bytea'] as String);
  Uint8List? get uint8List => switch (_json['uint8_list']) {
    null => null,
    final Object value => postgrestBytea.decode(value as String),
  };
  List<String>? get blobs => (_json['blobs'] as List<dynamic>?)?.cast();
  List<double> get postgrestVector$ =>
      postgrestVector.decode(_json['postgrest_vector'] as String);
  List<double>? get halfEmbedding => switch (_json['half_embedding']) {
    null => null,
    final Object value => postgrestVector.decode(value as String),
  };
  List<String>? get embeddings =>
      (_json['embeddings'] as List<dynamic>?)?.cast();

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `postgrest_table`. Columns that are
/// nullable, identity, or covered by a database default are optional; passing
/// `null` omits the column so the database default applies. Columns the
/// database always generates itself are left out entirely. Use the `set…ToNull`
/// methods to insert SQL NULL explicitly.
extension type const PostgrestTableInsert._(Map<String, dynamic> _json)
    implements Object {
  PostgrestTableInsert({
    required String quoteNameTail,
    String$? mood,
    required List<double> samples,
    List<String>? days,
    required Uint8List postgrestBytea$,
    Uint8List? uint8List,
    List<String>? blobs,
    required List<double> postgrestVector$,
    List<double>? halfEmbedding,
    List<String>? embeddings,
  }) : this._({
         'quote\'name\u{2029}tail': quoteNameTail,
         'mood': ?mood?.wireName,
         'samples': samples,
         'days': ?days,
         'postgrest_bytea': postgrestBytea.encode(postgrestBytea$),
         'uint8_list': ?switch (uint8List) {
           null => null,
           final value => postgrestBytea.encode(value),
         },
         'blobs': ?blobs,
         'postgrest_vector': postgrestVector.encode(postgrestVector$),
         'half_embedding': ?switch (halfEmbedding) {
           null => null,
           final value => postgrestVector.encode(value),
         },
         'embeddings': ?embeddings,
       });

  /// Returns a copy with `mood` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableInsert setMoodToNull() =>
      PostgrestTableInsert._({..._json, 'mood': null});

  /// Returns a copy with `days` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableInsert setDaysToNull() =>
      PostgrestTableInsert._({..._json, 'days': null});

  /// Returns a copy with `uint8_list` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableInsert setUint8ListToNull() =>
      PostgrestTableInsert._({..._json, 'uint8_list': null});

  /// Returns a copy with `blobs` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableInsert setBlobsToNull() =>
      PostgrestTableInsert._({..._json, 'blobs': null});

  /// Returns a copy with `half_embedding` set to SQL NULL, overriding any
  /// database default.
  PostgrestTableInsert setHalfEmbeddingToNull() =>
      PostgrestTableInsert._({..._json, 'half_embedding': null});

  /// Returns a copy with `embeddings` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableInsert setEmbeddingsToNull() =>
      PostgrestTableInsert._({..._json, 'embeddings': null});
}

/// Values for updating rows of `postgrest_table`. All columns are optional;
/// passing `null` omits the column, leaving it unchanged. Use the `set…ToNull`
/// methods to write SQL NULL explicitly.
extension type const PostgrestTableUpdate._(Map<String, dynamic> _json)
    implements Object {
  PostgrestTableUpdate({
    String? quoteNameTail,
    String$? mood,
    List<double>? samples,
    List<String>? days,
    Uint8List? postgrestBytea$,
    Uint8List? uint8List,
    List<String>? blobs,
    List<double>? postgrestVector$,
    List<double>? halfEmbedding,
    List<String>? embeddings,
  }) : this._({
         'quote\'name\u{2029}tail': ?quoteNameTail,
         'mood': ?mood?.wireName,
         'samples': ?samples,
         'days': ?days,
         'postgrest_bytea': ?switch (postgrestBytea$) {
           null => null,
           final value => postgrestBytea.encode(value),
         },
         'uint8_list': ?switch (uint8List) {
           null => null,
           final value => postgrestBytea.encode(value),
         },
         'blobs': ?blobs,
         'postgrest_vector': ?switch (postgrestVector$) {
           null => null,
           final value => postgrestVector.encode(value),
         },
         'half_embedding': ?switch (halfEmbedding) {
           null => null,
           final value => postgrestVector.encode(value),
         },
         'embeddings': ?embeddings,
       });

  /// Returns a copy with `mood` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableUpdate setMoodToNull() =>
      PostgrestTableUpdate._({..._json, 'mood': null});

  /// Returns a copy with `days` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableUpdate setDaysToNull() =>
      PostgrestTableUpdate._({..._json, 'days': null});

  /// Returns a copy with `uint8_list` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableUpdate setUint8ListToNull() =>
      PostgrestTableUpdate._({..._json, 'uint8_list': null});

  /// Returns a copy with `blobs` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableUpdate setBlobsToNull() =>
      PostgrestTableUpdate._({..._json, 'blobs': null});

  /// Returns a copy with `half_embedding` set to SQL NULL, overriding any
  /// database default.
  PostgrestTableUpdate setHalfEmbeddingToNull() =>
      PostgrestTableUpdate._({..._json, 'half_embedding': null});

  /// Returns a copy with `embeddings` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableUpdate setEmbeddingsToNull() =>
      PostgrestTableUpdate._({..._json, 'embeddings': null});
}

/// Typed access to the `postgrest_table` table.
class PostgrestTable$ {
  const PostgrestTable$._();

  /// Table definition for [PostgrestClient.table].
  static const table =
      PostgrestTable<
        PostgrestTableRow,
        PostgrestTableInsert,
        PostgrestTableUpdate
      >(
        'postgrest_table',
        PostgrestTableRow.new,
        schema: 'public',
        primaryKey: [quoteNameTail, days],
        relations: [mapByMood, mapByDays],
      );

  static const quoteNameTail = PostgrestColumn<PostgrestTableRow, String>(
    'quote\'name\u{2029}tail',
  );
  static const mood = PostgrestNullableColumn<PostgrestTableRow, String$>(
    'mood',
  );
  static const samples = PostgrestColumn<PostgrestTableRow, List<double>>(
    'samples',
  );
  static const days = PostgrestNullableColumn<PostgrestTableRow, List<String>>(
    'days',
  );
  static const postgrestBytea$ = PostgrestColumn<PostgrestTableRow, Uint8List>(
    'postgrest_bytea',
  );
  static const uint8List =
      PostgrestNullableColumn<PostgrestTableRow, Uint8List>('uint8_list');
  static const blobs = PostgrestNullableColumn<PostgrestTableRow, List<String>>(
    'blobs',
  );
  static const postgrestVector$ = PostgrestVectorColumn<PostgrestTableRow>(
    'postgrest_vector',
  );
  static const halfEmbedding = PostgrestNullableVectorColumn<PostgrestTableRow>(
    'half_embedding',
  );
  static const embeddings =
      PostgrestNullableColumn<PostgrestTableRow, List<String>>('embeddings');

  /// The `map` row referenced by `mood`.
  static const mapByMood = PostgrestToOneRelation<PostgrestTableRow, MapRow>(
    'map!postgrest_table_mood_fkey',
    columns: [mood],
    referencedTable: 'map',
    referencedColumns: [Map$.list],
  );

  /// The `map` row referenced by `days`.
  static const mapByDays = PostgrestToOneRelation<PostgrestTableRow, MapRow>(
    'map!postgrest_table_days_fkey',
    columns: [days],
    referencedTable: 'map',
    referencedColumns: [Map$.list],
  );
}

/// A row of the `map` table.
extension type const MapRow(Map<String, dynamic> _json) implements Object {
  int get list => _json['list'] as int;
  DateTime? get dateTime => switch (_json['date_time']) {
    null => null,
    final Object value => DateTime.parse(value as String),
  };
  PostgrestRange<int> get pages =>
      PostgrestRange.parse(_json['pages'] as String, int.parse);
  PostgrestRange<num>? get prices => switch (_json['prices']) {
    null => null,
    final Object value => PostgrestRange.parse(value as String, num.parse),
  };
  PostgrestRange<PostgrestDate> get season =>
      PostgrestRange.parse(_json['season'] as String, PostgrestDate.parse);
  PostgrestRange<DateTime> get shift =>
      PostgrestRange.parse(_json['shift'] as String, DateTime.parse);
  PostgrestRange<DateTime>? get during => switch (_json['during']) {
    null => null,
    final Object value => PostgrestRange.parse(value as String, DateTime.parse),
  };
  PostgrestDate get since => PostgrestDate.parse(_json['since'] as String);
  PostgrestTime get opensAt => PostgrestTime.parse(_json['opens_at'] as String);
  PostgrestTime? get closesAt => switch (_json['closes_at']) {
    null => null,
    final Object value => PostgrestTime.parse(value as String),
  };
  PostgrestInterval? get ttl => switch (_json['ttl']) {
    null => null,
    final Object value => PostgrestInterval.parse(value as String),
  };

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `map`. Columns that are nullable, identity,
/// or covered by a database default are optional; passing `null` omits the
/// column so the database default applies. Columns the database always
/// generates itself are left out entirely. Use the `set…ToNull` methods to
/// insert SQL NULL explicitly.
extension type const MapInsert._(Map<String, dynamic> _json) implements Object {
  MapInsert({
    required int list,
    DateTime? dateTime,
    required PostgrestRange<int> pages,
    PostgrestRange<num>? prices,
    PostgrestRange<PostgrestDate>? season,
    required PostgrestRange<DateTime> shift,
    PostgrestRange<DateTime>? during,
    required PostgrestDate since,
    required PostgrestTime opensAt,
    PostgrestTime? closesAt,
    PostgrestInterval? ttl,
  }) : this._({
         'list': list,
         'date_time': ?dateTime?.toUtc().toIso8601String(),
         'pages': pages.literal,
         'prices': ?prices?.literal,
         'season': ?season?.literal,
         'shift': shift.render((bound) => bound.toIso8601String()),
         'during': ?during?.render((bound) => bound.toUtc().toIso8601String()),
         'since': since.literal,
         'opens_at': opensAt.literal,
         'closes_at': ?closesAt?.literal,
         'ttl': ?ttl?.literal,
       });

  /// Returns a copy with `date_time` set to SQL NULL, overriding any database
  /// default.
  MapInsert setDateTimeToNull() => MapInsert._({..._json, 'date_time': null});

  /// Returns a copy with `prices` set to SQL NULL, overriding any database
  /// default.
  MapInsert setPricesToNull() => MapInsert._({..._json, 'prices': null});

  /// Returns a copy with `during` set to SQL NULL, overriding any database
  /// default.
  MapInsert setDuringToNull() => MapInsert._({..._json, 'during': null});

  /// Returns a copy with `closes_at` set to SQL NULL, overriding any database
  /// default.
  MapInsert setClosesAtToNull() => MapInsert._({..._json, 'closes_at': null});

  /// Returns a copy with `ttl` set to SQL NULL, overriding any database
  /// default.
  MapInsert setTtlToNull() => MapInsert._({..._json, 'ttl': null});
}

/// Values for updating rows of `map`. All columns are optional; passing `null`
/// omits the column, leaving it unchanged. Use the `set…ToNull` methods to
/// write SQL NULL explicitly.
extension type const MapUpdate._(Map<String, dynamic> _json) implements Object {
  MapUpdate({
    int? list,
    DateTime? dateTime,
    PostgrestRange<int>? pages,
    PostgrestRange<num>? prices,
    PostgrestRange<PostgrestDate>? season,
    PostgrestRange<DateTime>? shift,
    PostgrestRange<DateTime>? during,
    PostgrestDate? since,
    PostgrestTime? opensAt,
    PostgrestTime? closesAt,
    PostgrestInterval? ttl,
  }) : this._({
         'list': ?list,
         'date_time': ?dateTime?.toUtc().toIso8601String(),
         'pages': ?pages?.literal,
         'prices': ?prices?.literal,
         'season': ?season?.literal,
         'shift': ?shift?.render((bound) => bound.toIso8601String()),
         'during': ?during?.render((bound) => bound.toUtc().toIso8601String()),
         'since': ?since?.literal,
         'opens_at': ?opensAt?.literal,
         'closes_at': ?closesAt?.literal,
         'ttl': ?ttl?.literal,
       });

  /// Returns a copy with `date_time` set to SQL NULL, overriding any database
  /// default.
  MapUpdate setDateTimeToNull() => MapUpdate._({..._json, 'date_time': null});

  /// Returns a copy with `prices` set to SQL NULL, overriding any database
  /// default.
  MapUpdate setPricesToNull() => MapUpdate._({..._json, 'prices': null});

  /// Returns a copy with `during` set to SQL NULL, overriding any database
  /// default.
  MapUpdate setDuringToNull() => MapUpdate._({..._json, 'during': null});

  /// Returns a copy with `closes_at` set to SQL NULL, overriding any database
  /// default.
  MapUpdate setClosesAtToNull() => MapUpdate._({..._json, 'closes_at': null});

  /// Returns a copy with `ttl` set to SQL NULL, overriding any database
  /// default.
  MapUpdate setTtlToNull() => MapUpdate._({..._json, 'ttl': null});
}

/// Typed access to the `map` table.
class Map$ {
  const Map$._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable<MapRow, MapInsert, MapUpdate>(
    'map',
    MapRow.new,
    schema: 'public',
    primaryKey: [],
    relations: [postgrestTableViaMood, postgrestTableViaDays],
  );

  static const list = PostgrestColumn<MapRow, int>('list');
  static const dateTime = PostgrestNullableColumn<MapRow, DateTime>(
    'date_time',
  );
  static const pages = PostgrestColumn<MapRow, PostgrestRange<int>>('pages');
  static const prices = PostgrestNullableColumn<MapRow, PostgrestRange<num>>(
    'prices',
  );
  static const season = PostgrestColumn<MapRow, PostgrestRange<PostgrestDate>>(
    'season',
  );
  static const shift = PostgrestColumn<MapRow, PostgrestRange<DateTime>>(
    'shift',
  );
  static const during =
      PostgrestNullableColumn<MapRow, PostgrestRange<DateTime>>('during');
  static const since = PostgrestColumn<MapRow, PostgrestDate>('since');
  static const opensAt = PostgrestColumn<MapRow, PostgrestTime>('opens_at');
  static const closesAt = PostgrestNullableColumn<MapRow, PostgrestTime>(
    'closes_at',
  );
  static const ttl = PostgrestNullableColumn<MapRow, PostgrestInterval>('ttl');

  /// The `postgrest_table` rows referencing this row through `mood`.
  static const postgrestTableViaMood =
      PostgrestToManyRelation<MapRow, PostgrestTableRow>(
        'postgrest_table!postgrest_table_mood_fkey',
        columns: [list],
        referencedTable: 'postgrest_table',
        referencedColumns: [PostgrestTable$.mood],
      );

  /// The `postgrest_table` row referencing this row through `days`.
  static const postgrestTableViaDays =
      PostgrestToOneRelation<MapRow, PostgrestTableRow>(
        'postgrest_table!postgrest_table_days_fkey',
        columns: [list],
        referencedTable: 'postgrest_table',
        referencedColumns: [PostgrestTable$.days],
      );
}

/// A row of the `evil
/// multiline "schema" name.postgrest_column` table.
extension type const EvilMultilineSchemaNamePostgrestColumnRow(
  Map<String, dynamic> _json
)
    implements Object {
  int get id => _json['id'] as int;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `evil
/// multiline "schema" name.postgrest_column`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const EvilMultilineSchemaNamePostgrestColumnInsert._(
  Map<String, dynamic> _json
)
    implements Object {
  EvilMultilineSchemaNamePostgrestColumnInsert({required int id})
    : this._({'id': id});
}

/// Values for updating rows of `evil
/// multiline "schema" name.postgrest_column`. All columns are optional; passing
/// `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods
/// to write SQL NULL explicitly.
extension type const EvilMultilineSchemaNamePostgrestColumnUpdate._(
  Map<String, dynamic> _json
)
    implements Object {
  EvilMultilineSchemaNamePostgrestColumnUpdate({int? id}) : this._({'id': ?id});
}

/// Typed access to the `evil
/// multiline "schema" name.postgrest_column` table.
class EvilMultilineSchemaNamePostgrestColumn {
  const EvilMultilineSchemaNamePostgrestColumn._();

  /// Table definition for [PostgrestClient.table].
  static const table =
      PostgrestTable<
        EvilMultilineSchemaNamePostgrestColumnRow,
        EvilMultilineSchemaNamePostgrestColumnInsert,
        EvilMultilineSchemaNamePostgrestColumnUpdate
      >(
        'postgrest_column',
        EvilMultilineSchemaNamePostgrestColumnRow.new,
        schema: 'evil\nmultiline "schema" name',
        primaryKey: [],
      );

  static const id =
      PostgrestColumn<EvilMultilineSchemaNamePostgrestColumnRow, int>('id');
}

/// A row of the `private.achievement_item_progress_tbl` table.
extension type const PrivateAchievementItemProgressTblRow(
  Map<String, dynamic> _json
)
    implements Object {
  int get id => _json['id'] as int;
  String get name => _json['name'] as String;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `private.achievement_item_progress_tbl`.
/// Columns that are nullable, identity, or covered by a database default are
/// optional; passing `null` omits the column so the database default applies.
/// Columns the database always generates itself are left out entirely. Use the
/// `set…ToNull` methods to insert SQL NULL explicitly.
extension type const PrivateAchievementItemProgressTblInsert._(
  Map<String, dynamic> _json
)
    implements Object {
  PrivateAchievementItemProgressTblInsert({int? id, required String name})
    : this._({'id': ?id, 'name': name});
}

/// Values for updating rows of `private.achievement_item_progress_tbl`. All
/// columns are optional; passing `null` omits the column, leaving it unchanged.
/// Use the `set…ToNull` methods to write SQL NULL explicitly.
extension type const PrivateAchievementItemProgressTblUpdate._(
  Map<String, dynamic> _json
)
    implements Object {
  PrivateAchievementItemProgressTblUpdate({int? id, String? name})
    : this._({'id': ?id, 'name': ?name});
}

/// Typed access to the `private.achievement_item_progress_tbl` table.
class PrivateAchievementItemProgressTbl {
  const PrivateAchievementItemProgressTbl._();

  /// Table definition for [PostgrestClient.table].
  static const table =
      PostgrestTable<
        PrivateAchievementItemProgressTblRow,
        PrivateAchievementItemProgressTblInsert,
        PrivateAchievementItemProgressTblUpdate
      >(
        'achievement_item_progress_tbl',
        PrivateAchievementItemProgressTblRow.new,
        schema: 'private',
        primaryKey: [id],
      );

  static const id = PostgrestColumn<PrivateAchievementItemProgressTblRow, int>(
    'id',
  );
  static const name =
      PostgrestColumn<PrivateAchievementItemProgressTblRow, String>('name');
}
