// Generated by supabase_typegen. Do not edit by hand.
//
// Source schema: evil multiline "schema" name

// The typed table access API is still experimental.
// ignore_for_file: experimental_member_use

import 'package:postgrest/postgrest.dart';

/// Postgres enum `public.string`.
enum String$ {
  itSATrap('it\'s \$a\u{2028}trap'),
  plain('plain');

  const String$(this.wireName);

  /// The value as stored in the database.
  final String wireName;

  /// Parses the database representation of the enum.
  static String$ fromWire(String wireName) => values.firstWhere(
    (value) => value.wireName == wireName,
    orElse: () => throw ArgumentError.value(
      wireName,
      'wireName',
      'No String\$ value with this wire name',
    ),
  );

  @override
  String toString() => wireName;
}

/// A row of the `postgrest_table` table.
/// first
/// second
/// third $interpolation "quoted"
extension type const PostgrestTableRow(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  /// says "hi" \ and $more
  String get quoteNameTail => _json['quote\'name\u{2029}tail'] as String;
  String$? get mood => switch (_json['mood']) {
    null => null,
    final Object value => String$.fromWire(value as String),
  };
  List<double> get samples => (_json['samples'] as List<dynamic>)
      .map((element) => (element as num).toDouble())
      .toList();
  List<String>? get days => (_json['days'] as List<dynamic>?)?.cast();
}

/// Values for inserting a row into `postgrest_table`. Columns that are
/// nullable, identity, or covered by a database default are optional; passing
/// `null` omits the column so the database default applies. Columns the
/// database always generates itself are left out entirely. Use the `set…ToNull`
/// methods to insert SQL NULL explicitly.
extension type const PostgrestTableInsert._(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  PostgrestTableInsert({
    required String quoteNameTail,
    String$? mood,
    required List<double> samples,
    List<String>? days,
  }) : this._({
         'quote\'name\u{2029}tail': quoteNameTail,
         'mood': ?mood?.wireName,
         'samples': samples,
         'days': ?days,
       });

  /// Returns a copy with `mood` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableInsert setMoodToNull() =>
      PostgrestTableInsert._({..._json, 'mood': null});

  /// Returns a copy with `days` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableInsert setDaysToNull() =>
      PostgrestTableInsert._({..._json, 'days': null});
}

/// Values for updating rows of `postgrest_table`. All columns are optional;
/// passing `null` omits the column, leaving it unchanged. Use the `set…ToNull`
/// methods to write SQL NULL explicitly.
extension type const PostgrestTableUpdate._(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  PostgrestTableUpdate({
    String? quoteNameTail,
    String$? mood,
    List<double>? samples,
    List<String>? days,
  }) : this._({
         'quote\'name\u{2029}tail': ?quoteNameTail,
         'mood': ?mood?.wireName,
         'samples': ?samples,
         'days': ?days,
       });

  /// Returns a copy with `mood` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableUpdate setMoodToNull() =>
      PostgrestTableUpdate._({..._json, 'mood': null});

  /// Returns a copy with `days` set to SQL NULL, overriding any database
  /// default.
  PostgrestTableUpdate setDaysToNull() =>
      PostgrestTableUpdate._({..._json, 'days': null});
}

/// Typed access to the `postgrest_table` table.
class PostgrestTable$ {
  const PostgrestTable$._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable('postgrest_table', PostgrestTableRow.new);

  static const quoteNameTail = PostgrestColumn<PostgrestTableRow, String>(
    'quote\'name\u{2029}tail',
  );
  static const mood = PostgrestNullableColumn<PostgrestTableRow, String$>(
    'mood',
  );
  static const samples = PostgrestColumn<PostgrestTableRow, List<double>>(
    'samples',
  );
  static const days = PostgrestNullableColumn<PostgrestTableRow, List<String>>(
    'days',
  );
}

/// A row of the `map` table.
extension type const MapRow(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  int get list => _json['list'] as int;
  DateTime? get dateTime => switch (_json['date_time']) {
    null => null,
    final Object value => DateTime.parse(value as String),
  };
  PostgrestRange<int> get pages =>
      PostgrestRange.parse(_json['pages'] as String, int.parse);
  PostgrestRange<num>? get prices => switch (_json['prices']) {
    null => null,
    final Object value => PostgrestRange.parse(value as String, num.parse),
  };
  PostgrestRange<DateTime> get season =>
      PostgrestRange.parse(_json['season'] as String, DateTime.parse);
  PostgrestRange<DateTime> get shift =>
      PostgrestRange.parse(_json['shift'] as String, DateTime.parse);
  PostgrestRange<DateTime>? get during => switch (_json['during']) {
    null => null,
    final Object value => PostgrestRange.parse(value as String, DateTime.parse),
  };
}

/// Values for inserting a row into `map`. Columns that are nullable, identity,
/// or covered by a database default are optional; passing `null` omits the
/// column so the database default applies. Columns the database always
/// generates itself are left out entirely. Use the `set…ToNull` methods to
/// insert SQL NULL explicitly.
extension type const MapInsert._(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  MapInsert({
    required int list,
    DateTime? dateTime,
    required PostgrestRange<int> pages,
    PostgrestRange<num>? prices,
    PostgrestRange<DateTime>? season,
    required PostgrestRange<DateTime> shift,
    PostgrestRange<DateTime>? during,
  }) : this._({
         'list': list,
         'date_time': ?dateTime?.toUtc().toIso8601String(),
         'pages': pages.literal,
         'prices': ?prices?.literal,
         'season': ?season?.render(_dateString),
         'shift': shift.render((bound) => bound.toIso8601String()),
         'during': ?during?.render((bound) => bound.toUtc().toIso8601String()),
       });

  /// Returns a copy with `date_time` set to SQL NULL, overriding any database
  /// default.
  MapInsert setDateTimeToNull() => MapInsert._({..._json, 'date_time': null});

  /// Returns a copy with `prices` set to SQL NULL, overriding any database
  /// default.
  MapInsert setPricesToNull() => MapInsert._({..._json, 'prices': null});

  /// Returns a copy with `during` set to SQL NULL, overriding any database
  /// default.
  MapInsert setDuringToNull() => MapInsert._({..._json, 'during': null});
}

/// Values for updating rows of `map`. All columns are optional; passing `null`
/// omits the column, leaving it unchanged. Use the `set…ToNull` methods to
/// write SQL NULL explicitly.
extension type const MapUpdate._(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  MapUpdate({
    int? list,
    DateTime? dateTime,
    PostgrestRange<int>? pages,
    PostgrestRange<num>? prices,
    PostgrestRange<DateTime>? season,
    PostgrestRange<DateTime>? shift,
    PostgrestRange<DateTime>? during,
  }) : this._({
         'list': ?list,
         'date_time': ?dateTime?.toUtc().toIso8601String(),
         'pages': ?pages?.literal,
         'prices': ?prices?.literal,
         'season': ?season?.render(_dateString),
         'shift': ?shift?.render((bound) => bound.toIso8601String()),
         'during': ?during?.render((bound) => bound.toUtc().toIso8601String()),
       });

  /// Returns a copy with `date_time` set to SQL NULL, overriding any database
  /// default.
  MapUpdate setDateTimeToNull() => MapUpdate._({..._json, 'date_time': null});

  /// Returns a copy with `prices` set to SQL NULL, overriding any database
  /// default.
  MapUpdate setPricesToNull() => MapUpdate._({..._json, 'prices': null});

  /// Returns a copy with `during` set to SQL NULL, overriding any database
  /// default.
  MapUpdate setDuringToNull() => MapUpdate._({..._json, 'during': null});
}

/// Typed access to the `map` table.
class Map$ {
  const Map$._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable('map', MapRow.new);

  static const list = PostgrestColumn<MapRow, int>('list');
  static const dateTime = PostgrestNullableColumn<MapRow, DateTime>(
    'date_time',
  );
  static const pages = PostgrestColumn<MapRow, PostgrestRange<int>>('pages');
  static const prices = PostgrestNullableColumn<MapRow, PostgrestRange<num>>(
    'prices',
  );
  static const season = PostgrestColumn<MapRow, PostgrestRange<DateTime>>(
    'season',
  );
  static const shift = PostgrestColumn<MapRow, PostgrestRange<DateTime>>(
    'shift',
  );
  static const during =
      PostgrestNullableColumn<MapRow, PostgrestRange<DateTime>>('during');
}

String _dateString(DateTime date) =>
    '${date.year.toString().padLeft(4, '0')}-'
    '${date.month.toString().padLeft(2, '0')}-'
    '${date.day.toString().padLeft(2, '0')}';
