// Generated by supabase_typegen 0.3.0 from GeneratorMetadata version 1.
// Do not edit by hand.
//
// Source schemas: inventory, public

// The typed table access API is still experimental.
// ignore_for_file: experimental_member_use

import 'dart:typed_data';

import 'package:postgrest/postgrest.dart';

/// Postgres enum `inventory.condition`.
enum InventoryCondition {
  new$('new'),
  used('used');

  const InventoryCondition(this.wireName);

  /// The value as stored in the database.
  final String wireName;

  /// Parses the database representation of the enum.
  static InventoryCondition fromWire(String wireName) => values.firstWhere(
    (value) => value.wireName == wireName,
    orElse: () => throw ArgumentError.value(
      wireName,
      'wireName',
      'No InventoryCondition value with this wire name',
    ),
  );

  @override
  String toString() => wireName;
}

/// Postgres enum `public.mood`.
enum Mood {
  happy('happy'),
  veryHappy('very happy'),
  sad('sad');

  const Mood(this.wireName);

  /// The value as stored in the database.
  final String wireName;

  /// Parses the database representation of the enum.
  static Mood fromWire(String wireName) => values.firstWhere(
    (value) => value.wireName == wireName,
    orElse: () => throw ArgumentError.value(
      wireName,
      'wireName',
      'No Mood value with this wire name',
    ),
  );

  @override
  String toString() => wireName;
}

/// A row of the `inventory.books` table.
extension type const InventoryBooksRow(Map<String, dynamic> _json)
    implements Object {
  int get id => _json['id'] as int;
  String get isbn => _json['isbn'] as String;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `inventory.books`. Columns that are
/// nullable, identity, or covered by a database default are optional; passing
/// `null` omits the column so the database default applies. Columns the
/// database always generates itself are left out entirely. Use the `set…ToNull`
/// methods to insert SQL NULL explicitly.
extension type const InventoryBooksInsert._(Map<String, dynamic> _json)
    implements Object {
  InventoryBooksInsert({required String isbn}) : this._({'isbn': isbn});
}

/// Values for updating rows of `inventory.books`. All columns are optional;
/// passing `null` omits the column, leaving it unchanged. Use the `set…ToNull`
/// methods to write SQL NULL explicitly.
extension type const InventoryBooksUpdate._(Map<String, dynamic> _json)
    implements Object {
  InventoryBooksUpdate({String? isbn}) : this._({'isbn': ?isbn});
}

/// Typed access to the `inventory.books` table.
class InventoryBooks {
  const InventoryBooks._();

  /// Table definition for [PostgrestClient.table].
  static const table =
      PostgrestTable<
        InventoryBooksRow,
        InventoryBooksInsert,
        InventoryBooksUpdate
      >(
        'books',
        InventoryBooksRow.new,
        schema: 'inventory',
        primaryKey: [id],
        relations: [stock],
      );

  static const id = PostgrestColumn<InventoryBooksRow, int>('id');
  static const isbn = PostgrestColumn<InventoryBooksRow, String>('isbn');

  /// The `inventory.stock` rows referencing this row through `copy_id`.
  static const stock =
      PostgrestToManyRelation<InventoryBooksRow, InventoryStockRow>(
        'stock',
        columns: [id],
        referencedTable: 'stock',
        referencedColumns: [InventoryStock.copyId],
      );
}

/// A row of the `inventory.stock` table.
/// Copies held per book
extension type const InventoryStockRow(Map<String, dynamic> _json)
    implements Object {
  int get bookId => _json['book_id'] as int;
  InventoryCondition get condition =>
      InventoryCondition.fromWire(_json['condition'] as String);
  int get copyId => _json['copy_id'] as int;
  int get id => _json['id'] as int;
  int get quantity => _json['quantity'] as int;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `inventory.stock`. Columns that are
/// nullable, identity, or covered by a database default are optional; passing
/// `null` omits the column so the database default applies. Columns the
/// database always generates itself are left out entirely. Use the `set…ToNull`
/// methods to insert SQL NULL explicitly.
extension type const InventoryStockInsert._(Map<String, dynamic> _json)
    implements Object {
  InventoryStockInsert({
    required int bookId,
    InventoryCondition? condition,
    required int copyId,
    int? quantity,
  }) : this._({
         'book_id': bookId,
         'condition': ?condition?.wireName,
         'copy_id': copyId,
         'quantity': ?quantity,
       });
}

/// Values for updating rows of `inventory.stock`. All columns are optional;
/// passing `null` omits the column, leaving it unchanged. Use the `set…ToNull`
/// methods to write SQL NULL explicitly.
extension type const InventoryStockUpdate._(Map<String, dynamic> _json)
    implements Object {
  InventoryStockUpdate({
    int? bookId,
    InventoryCondition? condition,
    int? copyId,
    int? quantity,
  }) : this._({
         'book_id': ?bookId,
         'condition': ?condition?.wireName,
         'copy_id': ?copyId,
         'quantity': ?quantity,
       });
}

/// Typed access to the `inventory.stock` table.
class InventoryStock {
  const InventoryStock._();

  /// Table definition for [PostgrestClient.table].
  static const table =
      PostgrestTable<
        InventoryStockRow,
        InventoryStockInsert,
        InventoryStockUpdate
      >(
        'stock',
        InventoryStockRow.new,
        schema: 'inventory',
        primaryKey: [id],
        relations: [books],
      );

  static const bookId = PostgrestColumn<InventoryStockRow, int>('book_id');
  static const condition =
      PostgrestColumn<InventoryStockRow, InventoryCondition>('condition');
  static const copyId = PostgrestColumn<InventoryStockRow, int>('copy_id');
  static const id = PostgrestColumn<InventoryStockRow, int>('id');
  static const quantity = PostgrestColumn<InventoryStockRow, int>('quantity');

  /// The `inventory.books` row referenced by `copy_id`.
  static const books =
      PostgrestToOneRelation<InventoryStockRow, InventoryBooksRow>(
        'books',
        columns: [copyId],
        referencedTable: 'books',
        referencedColumns: [InventoryBooks.id],
      );
}

/// A row of the `author_stats` table.
/// Aggregated statistics per author
extension type const AuthorStatsRow(Map<String, dynamic> _json)
    implements Object {
  int? get authorId => _json['author_id'] as int?;
  int? get bookCount => _json['book_count'] as int?;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Typed access to the `author_stats` table.
class AuthorStats {
  const AuthorStats._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable<AuthorStatsRow, Never, Never>(
    'author_stats',
    AuthorStatsRow.new,
    schema: 'public',
    primaryKey: [],
    relations: [authors],
  );

  static const authorId = PostgrestNullableColumn<AuthorStatsRow, int>(
    'author_id',
  );
  static const bookCount = PostgrestNullableColumn<AuthorStatsRow, int>(
    'book_count',
  );

  /// The `authors` row referenced by `author_id`.
  static const authors = PostgrestToOneRelation<AuthorStatsRow, AuthorsRow>(
    'authors',
    columns: [authorId],
    referencedTable: 'authors',
    referencedColumns: [Authors.id],
  );
}

/// A row of the `authors` table.
extension type const AuthorsRow(Map<String, dynamic> _json) implements Object {
  int get id => _json['id'] as int;
  String get name => _json['name'] as String;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `authors`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const AuthorsInsert._(Map<String, dynamic> _json)
    implements Object {
  AuthorsInsert({required String name}) : this._({'name': name});
}

/// Values for updating rows of `authors`. All columns are optional; passing
/// `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods
/// to write SQL NULL explicitly.
extension type const AuthorsUpdate._(Map<String, dynamic> _json)
    implements Object {
  AuthorsUpdate({String? name}) : this._({'name': ?name});
}

/// Typed access to the `authors` table.
class Authors {
  const Authors._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable<AuthorsRow, AuthorsInsert, AuthorsUpdate>(
    'authors',
    AuthorsRow.new,
    schema: 'public',
    primaryKey: [id],
    relations: [books, authorStats],
  );

  static const id = PostgrestColumn<AuthorsRow, int>('id');
  static const name = PostgrestColumn<AuthorsRow, String>('name');

  /// The `books` rows referencing this row through `author_id`.
  static const books = PostgrestToManyRelation<AuthorsRow, BooksRow>(
    'books',
    columns: [id],
    referencedTable: 'books',
    referencedColumns: [Books.authorId],
  );

  /// The `author_stats` rows referencing this row through `author_id`.
  static const authorStats =
      PostgrestToManyRelation<AuthorsRow, AuthorStatsRow>(
        'author_stats',
        columns: [id],
        referencedTable: 'author_stats',
        referencedColumns: [AuthorStats.authorId],
      );
}

/// A row of the `book_prices` table.
/// Prices per book, with the standard discount precomputed
extension type const BookPricesRow(Map<String, dynamic> _json)
    implements Object {
  num? get discountedPrice => _json['discounted_price'] as num?;
  int? get id => _json['id'] as int?;
  num? get price => _json['price'] as num?;
  String? get title => _json['title'] as String?;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `book_prices`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const BookPricesInsert._(Map<String, dynamic> _json)
    implements Object {
  BookPricesInsert({int? id, num? price, String? title})
    : this._({'id': ?id, 'price': ?price, 'title': ?title});

  /// Returns a copy with `id` set to SQL NULL, overriding any database default.
  BookPricesInsert setIdToNull() => BookPricesInsert._({..._json, 'id': null});

  /// Returns a copy with `price` set to SQL NULL, overriding any database
  /// default.
  BookPricesInsert setPriceToNull() =>
      BookPricesInsert._({..._json, 'price': null});

  /// Returns a copy with `title` set to SQL NULL, overriding any database
  /// default.
  BookPricesInsert setTitleToNull() =>
      BookPricesInsert._({..._json, 'title': null});
}

/// Values for updating rows of `book_prices`. All columns are optional; passing
/// `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods
/// to write SQL NULL explicitly.
extension type const BookPricesUpdate._(Map<String, dynamic> _json)
    implements Object {
  BookPricesUpdate({int? id, num? price, String? title})
    : this._({'id': ?id, 'price': ?price, 'title': ?title});

  /// Returns a copy with `id` set to SQL NULL, overriding any database default.
  BookPricesUpdate setIdToNull() => BookPricesUpdate._({..._json, 'id': null});

  /// Returns a copy with `price` set to SQL NULL, overriding any database
  /// default.
  BookPricesUpdate setPriceToNull() =>
      BookPricesUpdate._({..._json, 'price': null});

  /// Returns a copy with `title` set to SQL NULL, overriding any database
  /// default.
  BookPricesUpdate setTitleToNull() =>
      BookPricesUpdate._({..._json, 'title': null});
}

/// Typed access to the `book_prices` table.
class BookPrices {
  const BookPrices._();

  /// Table definition for [PostgrestClient.table].
  static const table =
      PostgrestTable<BookPricesRow, BookPricesInsert, BookPricesUpdate>(
        'book_prices',
        BookPricesRow.new,
        schema: 'public',
        primaryKey: [],
      );

  static const discountedPrice = PostgrestNullableColumn<BookPricesRow, num>(
    'discounted_price',
  );
  static const id = PostgrestNullableColumn<BookPricesRow, int>('id');
  static const price = PostgrestNullableColumn<BookPricesRow, num>('price');
  static const title = PostgrestNullableColumn<BookPricesRow, String>('title');
}

/// A row of the `book_submissions` table.
extension type const BookSubmissionsRow(Map<String, dynamic> _json)
    implements Object {
  String? get authorName => _json['author_name'] as String?;
  String? get title => _json['title'] as String?;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `book_submissions`. Columns that are
/// nullable, identity, or covered by a database default are optional; passing
/// `null` omits the column so the database default applies. Columns the
/// database always generates itself are left out entirely. Use the `set…ToNull`
/// methods to insert SQL NULL explicitly.
extension type const BookSubmissionsInsert._(Map<String, dynamic> _json)
    implements Object {
  BookSubmissionsInsert({String? authorName, String? title})
    : this._({'author_name': ?authorName, 'title': ?title});

  /// Returns a copy with `author_name` set to SQL NULL, overriding any database
  /// default.
  BookSubmissionsInsert setAuthorNameToNull() =>
      BookSubmissionsInsert._({..._json, 'author_name': null});

  /// Returns a copy with `title` set to SQL NULL, overriding any database
  /// default.
  BookSubmissionsInsert setTitleToNull() =>
      BookSubmissionsInsert._({..._json, 'title': null});
}

/// Typed access to the `book_submissions` table.
class BookSubmissions {
  const BookSubmissions._();

  /// Table definition for [PostgrestClient.table].
  static const table =
      PostgrestTable<BookSubmissionsRow, BookSubmissionsInsert, Never>(
        'book_submissions',
        BookSubmissionsRow.new,
        schema: 'public',
        primaryKey: [],
      );

  static const authorName = PostgrestNullableColumn<BookSubmissionsRow, String>(
    'author_name',
  );
  static const title = PostgrestNullableColumn<BookSubmissionsRow, String>(
    'title',
  );
}

/// A row of the `book_summaries` table.
/// Denormalized book and author names
extension type const BookSummariesRow(Map<String, dynamic> _json)
    implements Object {
  String? get authorName => _json['author_name'] as String?;
  int? get id => _json['id'] as int?;
  String? get title => _json['title'] as String?;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Typed access to the `book_summaries` table.
class BookSummaries {
  const BookSummaries._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable<BookSummariesRow, Never, Never>(
    'book_summaries',
    BookSummariesRow.new,
    schema: 'public',
    primaryKey: [],
  );

  static const authorName = PostgrestNullableColumn<BookSummariesRow, String>(
    'author_name',
  );
  static const id = PostgrestNullableColumn<BookSummariesRow, int>('id');
  static const title = PostgrestNullableColumn<BookSummariesRow, String>(
    'title',
  );
}

/// A row of the `books` table.
/// Books available in the library
extension type const BooksRow(Map<String, dynamic> _json) implements Object {
  int get authorId => _json['author_id'] as int;
  Uint8List? get coverImage => switch (_json['cover_image']) {
    null => null,
    final Object value => postgrestBytea.decode(value as String),
  };
  String? get coverUuid => _json['cover_uuid'] as String?;

  /// When the row was created
  DateTime get createdAt => DateTime.parse(_json['created_at'] as String);
  int get id => _json['id'] as int;
  bool get inPrint => _json['in_print'] as bool;
  Object? get metadata => _json['metadata'] as Object?;
  Mood? get mood => switch (_json['mood']) {
    null => null,
    final Object value => Mood.fromWire(value as String),
  };
  List<int>? get pageCounts => (_json['page_counts'] as List<dynamic>?)?.cast();
  num? get price => _json['price'] as num?;
  PostgrestDate? get publishedOn => switch (_json['published_on']) {
    null => null,
    final Object value => PostgrestDate.parse(value as String),
  };
  double? get rating => (_json['rating'] as num?)?.toDouble();
  List<String>? get tags => (_json['tags'] as List<dynamic>?)?.cast();
  String get title => _json['title'] as String;
  DateTime? get updatedAt => switch (_json['updated_at']) {
    null => null,
    final Object value => DateTime.parse(value as String),
  };

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `books`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const BooksInsert._(Map<String, dynamic> _json)
    implements Object {
  BooksInsert({
    required int authorId,
    Uint8List? coverImage,
    String? coverUuid,
    DateTime? createdAt,
    int? id,
    bool? inPrint,
    Object? metadata,
    Mood? mood,
    List<int>? pageCounts,
    num? price,
    PostgrestDate? publishedOn,
    double? rating,
    List<String>? tags,
    required String title,
    DateTime? updatedAt,
  }) : this._({
         'author_id': authorId,
         'cover_image': ?switch (coverImage) {
           null => null,
           final value => postgrestBytea.encode(value),
         },
         'cover_uuid': ?coverUuid,
         'created_at': ?createdAt?.toUtc().toIso8601String(),
         'id': ?id,
         'in_print': ?inPrint,
         'metadata': ?metadata,
         'mood': ?mood?.wireName,
         'page_counts': ?pageCounts,
         'price': ?price,
         'published_on': ?publishedOn?.literal,
         'rating': ?rating,
         'tags': ?tags,
         'title': title,
         'updated_at': ?updatedAt?.toIso8601String(),
       });

  /// Returns a copy with `cover_image` set to SQL NULL, overriding any database
  /// default.
  BooksInsert setCoverImageToNull() =>
      BooksInsert._({..._json, 'cover_image': null});

  /// Returns a copy with `cover_uuid` set to SQL NULL, overriding any database
  /// default.
  BooksInsert setCoverUuidToNull() =>
      BooksInsert._({..._json, 'cover_uuid': null});

  /// Returns a copy with `metadata` set to SQL NULL, overriding any database
  /// default.
  BooksInsert setMetadataToNull() =>
      BooksInsert._({..._json, 'metadata': null});

  /// Returns a copy with `mood` set to SQL NULL, overriding any database
  /// default.
  BooksInsert setMoodToNull() => BooksInsert._({..._json, 'mood': null});

  /// Returns a copy with `page_counts` set to SQL NULL, overriding any database
  /// default.
  BooksInsert setPageCountsToNull() =>
      BooksInsert._({..._json, 'page_counts': null});

  /// Returns a copy with `price` set to SQL NULL, overriding any database
  /// default.
  BooksInsert setPriceToNull() => BooksInsert._({..._json, 'price': null});

  /// Returns a copy with `published_on` set to SQL NULL, overriding any
  /// database default.
  BooksInsert setPublishedOnToNull() =>
      BooksInsert._({..._json, 'published_on': null});

  /// Returns a copy with `rating` set to SQL NULL, overriding any database
  /// default.
  BooksInsert setRatingToNull() => BooksInsert._({..._json, 'rating': null});

  /// Returns a copy with `tags` set to SQL NULL, overriding any database
  /// default.
  BooksInsert setTagsToNull() => BooksInsert._({..._json, 'tags': null});

  /// Returns a copy with `updated_at` set to SQL NULL, overriding any database
  /// default.
  BooksInsert setUpdatedAtToNull() =>
      BooksInsert._({..._json, 'updated_at': null});
}

/// Values for updating rows of `books`. All columns are optional; passing
/// `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods
/// to write SQL NULL explicitly.
extension type const BooksUpdate._(Map<String, dynamic> _json)
    implements Object {
  BooksUpdate({
    int? authorId,
    Uint8List? coverImage,
    String? coverUuid,
    DateTime? createdAt,
    int? id,
    bool? inPrint,
    Object? metadata,
    Mood? mood,
    List<int>? pageCounts,
    num? price,
    PostgrestDate? publishedOn,
    double? rating,
    List<String>? tags,
    String? title,
    DateTime? updatedAt,
  }) : this._({
         'author_id': ?authorId,
         'cover_image': ?switch (coverImage) {
           null => null,
           final value => postgrestBytea.encode(value),
         },
         'cover_uuid': ?coverUuid,
         'created_at': ?createdAt?.toUtc().toIso8601String(),
         'id': ?id,
         'in_print': ?inPrint,
         'metadata': ?metadata,
         'mood': ?mood?.wireName,
         'page_counts': ?pageCounts,
         'price': ?price,
         'published_on': ?publishedOn?.literal,
         'rating': ?rating,
         'tags': ?tags,
         'title': ?title,
         'updated_at': ?updatedAt?.toIso8601String(),
       });

  /// Returns a copy with `cover_image` set to SQL NULL, overriding any database
  /// default.
  BooksUpdate setCoverImageToNull() =>
      BooksUpdate._({..._json, 'cover_image': null});

  /// Returns a copy with `cover_uuid` set to SQL NULL, overriding any database
  /// default.
  BooksUpdate setCoverUuidToNull() =>
      BooksUpdate._({..._json, 'cover_uuid': null});

  /// Returns a copy with `metadata` set to SQL NULL, overriding any database
  /// default.
  BooksUpdate setMetadataToNull() =>
      BooksUpdate._({..._json, 'metadata': null});

  /// Returns a copy with `mood` set to SQL NULL, overriding any database
  /// default.
  BooksUpdate setMoodToNull() => BooksUpdate._({..._json, 'mood': null});

  /// Returns a copy with `page_counts` set to SQL NULL, overriding any database
  /// default.
  BooksUpdate setPageCountsToNull() =>
      BooksUpdate._({..._json, 'page_counts': null});

  /// Returns a copy with `price` set to SQL NULL, overriding any database
  /// default.
  BooksUpdate setPriceToNull() => BooksUpdate._({..._json, 'price': null});

  /// Returns a copy with `published_on` set to SQL NULL, overriding any
  /// database default.
  BooksUpdate setPublishedOnToNull() =>
      BooksUpdate._({..._json, 'published_on': null});

  /// Returns a copy with `rating` set to SQL NULL, overriding any database
  /// default.
  BooksUpdate setRatingToNull() => BooksUpdate._({..._json, 'rating': null});

  /// Returns a copy with `tags` set to SQL NULL, overriding any database
  /// default.
  BooksUpdate setTagsToNull() => BooksUpdate._({..._json, 'tags': null});

  /// Returns a copy with `updated_at` set to SQL NULL, overriding any database
  /// default.
  BooksUpdate setUpdatedAtToNull() =>
      BooksUpdate._({..._json, 'updated_at': null});
}

/// Typed access to the `books` table.
class Books {
  const Books._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable<BooksRow, BooksInsert, BooksUpdate>(
    'books',
    BooksRow.new,
    schema: 'public',
    primaryKey: [id],
    relations: [authors],
  );

  static const authorId = PostgrestColumn<BooksRow, int>('author_id');
  static const coverImage = PostgrestNullableColumn<BooksRow, Uint8List>(
    'cover_image',
  );
  static const coverUuid = PostgrestNullableColumn<BooksRow, String>(
    'cover_uuid',
  );
  static const createdAt = PostgrestColumn<BooksRow, DateTime>('created_at');
  static const id = PostgrestColumn<BooksRow, int>('id');
  static const inPrint = PostgrestColumn<BooksRow, bool>('in_print');
  static const metadata = PostgrestNullableColumn<BooksRow, Object>('metadata');
  static const mood = PostgrestNullableColumn<BooksRow, Mood>('mood');
  static const pageCounts = PostgrestNullableColumn<BooksRow, List<int>>(
    'page_counts',
  );
  static const price = PostgrestNullableColumn<BooksRow, num>('price');
  static const publishedOn = PostgrestNullableColumn<BooksRow, PostgrestDate>(
    'published_on',
  );
  static const rating = PostgrestNullableColumn<BooksRow, double>('rating');
  static const tags = PostgrestNullableColumn<BooksRow, List<String>>('tags');
  static const title = PostgrestColumn<BooksRow, String>('title');
  static const updatedAt = PostgrestNullableColumn<BooksRow, DateTime>(
    'updated_at',
  );

  /// The `authors` row referenced by `author_id`.
  static const authors = PostgrestToOneRelation<BooksRow, AuthorsRow>(
    'authors',
    columns: [authorId],
    referencedTable: 'authors',
    referencedColumns: [Authors.id],
  );
}
