// Generated by supabase_typegen. Do not edit by hand.
//
// Source schema: public

import 'package:postgrest/postgrest.dart';

/// Postgres enum `public.mood`.
enum Mood {
  happy('happy'),
  veryHappy('very happy'),
  sad('sad');

  const Mood(this.wireName);

  /// The value as stored in the database.
  final String wireName;

  /// Parses the database representation of the enum.
  static Mood fromWire(String wireName) => values.firstWhere(
    (value) => value.wireName == wireName,
    orElse: () => throw ArgumentError.value(
      wireName,
      'wireName',
      'No Mood value with this wire name',
    ),
  );

  @override
  String toString() => wireName;
}

/// A row of the `author_stats` table.
/// Aggregated statistics per author
extension type const AuthorStatsRow(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  int? get authorId => _json['author_id'] as int?;
  int? get bookCount => _json['book_count'] as int?;
}

/// Values for inserting a row into `author_stats`. Columns that are nullable, part of a generated primary key, or covered by a database default are optional; passing `null` omits the column so the database default applies. Use the `set…ToNull` methods to insert SQL NULL explicitly.
extension type const AuthorStatsInsert._(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  AuthorStatsInsert({int? authorId, int? bookCount})
    : this._({'author_id': ?authorId, 'book_count': ?bookCount});

  /// Returns a copy with `author_id` set to SQL NULL, overriding any database default.
  AuthorStatsInsert setAuthorIdToNull() =>
      AuthorStatsInsert._({..._json, 'author_id': null});

  /// Returns a copy with `book_count` set to SQL NULL, overriding any database default.
  AuthorStatsInsert setBookCountToNull() =>
      AuthorStatsInsert._({..._json, 'book_count': null});
}

/// Values for updating rows of `author_stats`. All columns are optional; passing `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods to write SQL NULL explicitly.
extension type const AuthorStatsUpdate._(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  AuthorStatsUpdate({int? authorId, int? bookCount})
    : this._({'author_id': ?authorId, 'book_count': ?bookCount});

  /// Returns a copy with `author_id` set to SQL NULL, overriding any database default.
  AuthorStatsUpdate setAuthorIdToNull() =>
      AuthorStatsUpdate._({..._json, 'author_id': null});

  /// Returns a copy with `book_count` set to SQL NULL, overriding any database default.
  AuthorStatsUpdate setBookCountToNull() =>
      AuthorStatsUpdate._({..._json, 'book_count': null});
}

/// Typed access to the `author_stats` table.
class AuthorStats {
  const AuthorStats._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable('author_stats', AuthorStatsRow.new);

  static const authorId = TableColumn<int>('author_id');
  static const bookCount = TableColumn<int>('book_count');
}

/// A row of the `authors` table.
extension type const AuthorsRow(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  int get id => _json['id'] as int;
  String get name => _json['name'] as String;
}

/// Values for inserting a row into `authors`. Columns that are nullable, part of a generated primary key, or covered by a database default are optional; passing `null` omits the column so the database default applies. Use the `set…ToNull` methods to insert SQL NULL explicitly.
extension type const AuthorsInsert._(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  AuthorsInsert({required int id, required String name})
    : this._({'id': id, 'name': name});
}

/// Values for updating rows of `authors`. All columns are optional; passing `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods to write SQL NULL explicitly.
extension type const AuthorsUpdate._(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  AuthorsUpdate({int? id, String? name}) : this._({'id': ?id, 'name': ?name});
}

/// Typed access to the `authors` table.
class Authors {
  const Authors._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable('authors', AuthorsRow.new);

  static const id = TableColumn<int>('id');
  static const name = TableColumn<String>('name');
}

/// A row of the `books` table.
/// Books available in the library
extension type const BooksRow(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  int get id => _json['id'] as int;
  String get title => _json['title'] as String;
  int get authorId => _json['author_id'] as int;
  num? get price => _json['price'] as num?;
  double? get rating => (_json['rating'] as num?)?.toDouble();
  bool? get inPrint => _json['in_print'] as bool?;
  Mood? get mood => switch (_json['mood']) {
    null => null,
    final Object value => Mood.fromWire(value as String),
  };
  List<String>? get tags => (_json['tags'] as List<dynamic>?)?.cast();
  List<int>? get pageCounts => (_json['page_counts'] as List<dynamic>?)?.cast();
  Object? get metadata => _json['metadata'] as Object?;
  String? get coverUuid => _json['cover_uuid'] as String?;
  DateTime? get publishedOn => switch (_json['published_on']) {
    null => null,
    final Object value => DateTime.parse(value as String),
  };

  /// When the row was created
  DateTime? get createdAt => switch (_json['created_at']) {
    null => null,
    final Object value => DateTime.parse(value as String),
  };
  DateTime? get updatedAt => switch (_json['updated_at']) {
    null => null,
    final Object value => DateTime.parse(value as String),
  };
}

/// Values for inserting a row into `books`. Columns that are nullable, part of a generated primary key, or covered by a database default are optional; passing `null` omits the column so the database default applies. Use the `set…ToNull` methods to insert SQL NULL explicitly.
extension type const BooksInsert._(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  BooksInsert({
    int? id,
    required String title,
    required int authorId,
    num? price,
    double? rating,
    bool? inPrint,
    Mood? mood,
    List<String>? tags,
    List<int>? pageCounts,
    Object? metadata,
    String? coverUuid,
    DateTime? publishedOn,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) : this._({
         'id': ?id,
         'title': title,
         'author_id': authorId,
         'price': ?price,
         'rating': ?rating,
         'in_print': ?inPrint,
         'mood': ?mood?.wireName,
         'tags': ?tags,
         'page_counts': ?pageCounts,
         'metadata': ?metadata,
         'cover_uuid': ?coverUuid,
         'published_on': ?switch (publishedOn) {
           null => null,
           final value => _dateString(value),
         },
         'created_at': ?createdAt?.toUtc().toIso8601String(),
         'updated_at': ?updatedAt?.toIso8601String(),
       });

  /// Returns a copy with `price` set to SQL NULL, overriding any database default.
  BooksInsert setPriceToNull() => BooksInsert._({..._json, 'price': null});

  /// Returns a copy with `rating` set to SQL NULL, overriding any database default.
  BooksInsert setRatingToNull() => BooksInsert._({..._json, 'rating': null});

  /// Returns a copy with `in_print` set to SQL NULL, overriding any database default.
  BooksInsert setInPrintToNull() => BooksInsert._({..._json, 'in_print': null});

  /// Returns a copy with `mood` set to SQL NULL, overriding any database default.
  BooksInsert setMoodToNull() => BooksInsert._({..._json, 'mood': null});

  /// Returns a copy with `tags` set to SQL NULL, overriding any database default.
  BooksInsert setTagsToNull() => BooksInsert._({..._json, 'tags': null});

  /// Returns a copy with `page_counts` set to SQL NULL, overriding any database default.
  BooksInsert setPageCountsToNull() =>
      BooksInsert._({..._json, 'page_counts': null});

  /// Returns a copy with `metadata` set to SQL NULL, overriding any database default.
  BooksInsert setMetadataToNull() =>
      BooksInsert._({..._json, 'metadata': null});

  /// Returns a copy with `cover_uuid` set to SQL NULL, overriding any database default.
  BooksInsert setCoverUuidToNull() =>
      BooksInsert._({..._json, 'cover_uuid': null});

  /// Returns a copy with `published_on` set to SQL NULL, overriding any database default.
  BooksInsert setPublishedOnToNull() =>
      BooksInsert._({..._json, 'published_on': null});

  /// Returns a copy with `created_at` set to SQL NULL, overriding any database default.
  BooksInsert setCreatedAtToNull() =>
      BooksInsert._({..._json, 'created_at': null});

  /// Returns a copy with `updated_at` set to SQL NULL, overriding any database default.
  BooksInsert setUpdatedAtToNull() =>
      BooksInsert._({..._json, 'updated_at': null});
}

/// Values for updating rows of `books`. All columns are optional; passing `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods to write SQL NULL explicitly.
extension type const BooksUpdate._(Map<String, dynamic> _json)
    implements Map<String, dynamic> {
  BooksUpdate({
    int? id,
    String? title,
    int? authorId,
    num? price,
    double? rating,
    bool? inPrint,
    Mood? mood,
    List<String>? tags,
    List<int>? pageCounts,
    Object? metadata,
    String? coverUuid,
    DateTime? publishedOn,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) : this._({
         'id': ?id,
         'title': ?title,
         'author_id': ?authorId,
         'price': ?price,
         'rating': ?rating,
         'in_print': ?inPrint,
         'mood': ?mood?.wireName,
         'tags': ?tags,
         'page_counts': ?pageCounts,
         'metadata': ?metadata,
         'cover_uuid': ?coverUuid,
         'published_on': ?switch (publishedOn) {
           null => null,
           final value => _dateString(value),
         },
         'created_at': ?createdAt?.toUtc().toIso8601String(),
         'updated_at': ?updatedAt?.toIso8601String(),
       });

  /// Returns a copy with `price` set to SQL NULL, overriding any database default.
  BooksUpdate setPriceToNull() => BooksUpdate._({..._json, 'price': null});

  /// Returns a copy with `rating` set to SQL NULL, overriding any database default.
  BooksUpdate setRatingToNull() => BooksUpdate._({..._json, 'rating': null});

  /// Returns a copy with `in_print` set to SQL NULL, overriding any database default.
  BooksUpdate setInPrintToNull() => BooksUpdate._({..._json, 'in_print': null});

  /// Returns a copy with `mood` set to SQL NULL, overriding any database default.
  BooksUpdate setMoodToNull() => BooksUpdate._({..._json, 'mood': null});

  /// Returns a copy with `tags` set to SQL NULL, overriding any database default.
  BooksUpdate setTagsToNull() => BooksUpdate._({..._json, 'tags': null});

  /// Returns a copy with `page_counts` set to SQL NULL, overriding any database default.
  BooksUpdate setPageCountsToNull() =>
      BooksUpdate._({..._json, 'page_counts': null});

  /// Returns a copy with `metadata` set to SQL NULL, overriding any database default.
  BooksUpdate setMetadataToNull() =>
      BooksUpdate._({..._json, 'metadata': null});

  /// Returns a copy with `cover_uuid` set to SQL NULL, overriding any database default.
  BooksUpdate setCoverUuidToNull() =>
      BooksUpdate._({..._json, 'cover_uuid': null});

  /// Returns a copy with `published_on` set to SQL NULL, overriding any database default.
  BooksUpdate setPublishedOnToNull() =>
      BooksUpdate._({..._json, 'published_on': null});

  /// Returns a copy with `created_at` set to SQL NULL, overriding any database default.
  BooksUpdate setCreatedAtToNull() =>
      BooksUpdate._({..._json, 'created_at': null});

  /// Returns a copy with `updated_at` set to SQL NULL, overriding any database default.
  BooksUpdate setUpdatedAtToNull() =>
      BooksUpdate._({..._json, 'updated_at': null});
}

/// Typed access to the `books` table.
class Books {
  const Books._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable('books', BooksRow.new);

  static const id = TableColumn<int>('id');
  static const title = TableColumn<String>('title');
  static const authorId = TableColumn<int>('author_id');
  static const price = TableColumn<num>('price');
  static const rating = TableColumn<double>('rating');
  static const inPrint = TableColumn<bool>('in_print');
  static const mood = TableColumn<Mood>('mood');
  static const tags = TableColumn<List<String>>('tags');
  static const pageCounts = TableColumn<List<int>>('page_counts');
  static const metadata = TableColumn<Object>('metadata');
  static const coverUuid = TableColumn<String>('cover_uuid');
  static const publishedOn = TableColumn<DateTime>('published_on');
  static const createdAt = TableColumn<DateTime>('created_at');
  static const updatedAt = TableColumn<DateTime>('updated_at');
}

String _dateString(DateTime date) =>
    '${date.year.toString().padLeft(4, '0')}-'
    '${date.month.toString().padLeft(2, '0')}-'
    '${date.day.toString().padLeft(2, '0')}';
