name: database_crud_example
description: Demonstrates database CRUD with PostgREST using supabase_flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.17.0

dev_dependencies:
  supabase_lints: ^0.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
