import 'package:meta/meta.dart';

/// A passkey (WebAuthn credential) registered to a user.
@experimental
class Passkey {
  /// ID of the passkey.
  final String id;

  /// Human readable name of the passkey.
  ///
  /// Automatically generated by the server from the authenticator that
  /// created the credential (e.g. "iCloud Keychain"). Can be changed with
  /// [GoTruePasskeyApi.update].
  final String? friendlyName;

  /// Timestamp when the passkey was registered.
  final DateTime createdAt;

  /// Timestamp when the passkey was last used to sign in, if ever.
  final DateTime? lastUsedAt;

  const Passkey({
    required this.id,
    this.friendlyName,
    required this.createdAt,
    this.lastUsedAt,
  });

  factory Passkey.fromJson(Map<String, dynamic> json) {
    final createdAt = json['created_at'];
    if (createdAt is! String) {
      throw FormatException(
        'Expected created_at to be a string, got ${createdAt.runtimeType}',
        json.toString(),
      );
    }
    final lastUsedAt = json['last_used_at'] as String?;
    return Passkey(
      id: json['id'] as String,
      friendlyName: json['friendly_name'] as String?,
      createdAt: DateTime.parse(createdAt),
      lastUsedAt: lastUsedAt != null ? DateTime.parse(lastUsedAt) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'friendly_name': friendlyName,
      'created_at': createdAt.toIso8601String(),
      'last_used_at': lastUsedAt?.toIso8601String(),
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is Passkey &&
        other.id == id &&
        other.friendlyName == friendlyName &&
        other.createdAt == createdAt &&
        other.lastUsedAt == lastUsedAt;
  }

  @override
  int get hashCode {
    return id.hashCode ^
        friendlyName.hashCode ^
        createdAt.hashCode ^
        lastUsedAt.hashCode;
  }
}

/// Response containing the options needed to register a new passkey.
@experimental
class PasskeyRegistrationOptionsResponse {
  /// ID of the challenge, pass it to [GoTruePasskeyApi.verifyRegistration]
  /// together with the created credential.
  final String challengeId;

  /// WebAuthn credential creation options in the W3C
  /// `PublicKeyCredentialCreationOptionsJSON` format, with binary fields
  /// encoded as base64url strings.
  ///
  /// Pass these to the platform's passkey API (`navigator.credentials.create`
  /// on web, or a passkey plugin on iOS/Android) to create the credential.
  final Map<String, dynamic> options;

  /// Timestamp when this challenge will no longer be usable.
  final DateTime expiresAt;

  const PasskeyRegistrationOptionsResponse({
    required this.challengeId,
    required this.options,
    required this.expiresAt,
  });

  factory PasskeyRegistrationOptionsResponse.fromJson(
    Map<String, dynamic> json,
  ) {
    return PasskeyRegistrationOptionsResponse(
      challengeId: json['challenge_id'] as String,
      options: Map.from(json['options'] as Map),
      expiresAt: _parseExpiresAt(json),
    );
  }
}

/// Response containing the options needed to sign in with a passkey.
@experimental
class PasskeyAuthenticationOptionsResponse {
  /// ID of the challenge, pass it to [GoTruePasskeyApi.verifyAuthentication]
  /// together with the signed assertion.
  final String challengeId;

  /// WebAuthn credential request options in the W3C
  /// `PublicKeyCredentialRequestOptionsJSON` format, with binary fields
  /// encoded as base64url strings.
  ///
  /// Pass these to the platform's passkey API (`navigator.credentials.get`
  /// on web, or a passkey plugin on iOS/Android) to obtain an assertion.
  final Map<String, dynamic> options;

  /// Timestamp when this challenge will no longer be usable.
  final DateTime expiresAt;

  const PasskeyAuthenticationOptionsResponse({
    required this.challengeId,
    required this.options,
    required this.expiresAt,
  });

  factory PasskeyAuthenticationOptionsResponse.fromJson(
    Map<String, dynamic> json,
  ) {
    return PasskeyAuthenticationOptionsResponse(
      challengeId: json['challenge_id'] as String,
      options: Map.from(json['options'] as Map),
      expiresAt: _parseExpiresAt(json),
    );
  }
}

DateTime _parseExpiresAt(Map<String, dynamic> json) {
  final expiresAtValue = json['expires_at'];
  if (expiresAtValue is! num) {
    throw FormatException(
      'Expected expires_at to be a number, got ${expiresAtValue.runtimeType}',
      json.toString(),
    );
  }
  return DateTime.fromMillisecondsSinceEpoch(expiresAtValue.toInt() * 1000);
}
