import 'package:dart_style/dart_style.dart';
import 'package:pub_semver/pub_semver.dart';

import 'identifiers.dart';
import 'language_version_io.dart';
import 'sdk_formatter_io.dart';
import 'schema_description.dart';
import 'version.dart';

class _Binding {
  const _Binding(this.dartType, this.kind, {this.boundKind});

  /// The non-nullable Dart type of the column.
  final String dartType;
  final ColumnTypeKind kind;

  /// The kind of the bounds of a [ColumnTypeKind.range] column.
  final ColumnTypeKind? boundKind;
}

/// The lowest language version the generated code is valid for: the value
/// types omit unset columns with null-aware map elements, which need Dart
/// 3.8.
final minimumLanguageVersion = Version(3, 8, 0);

/// Generates a Dart source file with typed table definitions, row extension
/// types, insert and update value types, column tokens and Postgres enums for
/// the schemas of [database].
///
/// Objects of the `public` schema are named after themselves, `books` becomes
/// `Books` and `BooksRow`; objects of any other schema carry the schema as a
/// prefix, so `inventory.books` becomes `InventoryBooks` and
/// `InventoryBooksRow`.
///
/// The generated code depends only on the library at [importUri], which must
/// export the typed table access API of `package:postgrest` (`PostgrestTable`,
/// `PostgrestColumn`, `PostgrestNullableColumn`, `PostgrestVectorColumn`,
/// `PostgrestNullableVectorColumn`, `PostgrestRange`,
/// `PostgrestToOneRelation`, `PostgrestToManyRelation`, `postgrestBytea` and
/// `postgrestVector`).
///
/// The code is formatted for [languageVersion], so it uses no syntax a
/// project on that language version rejects; pass the version
/// [packageLanguageVersion] finds for the project the file is written into.
/// It defaults to, and is never lower than, [minimumLanguageVersion]. To
/// match the formatter of a project exactly, pass the result through
/// [formatWithSdk] as well.
String generateDartCode(
  DatabaseDescription database, {
  String importUri = 'package:postgrest/postgrest.dart',
  Version? languageVersion,
}) {
  final formatVersion =
      languageVersion == null || languageVersion < minimumLanguageVersion
      ? minimumLanguageVersion
      : languageVersion;
  final usesDateColumns = database.tables.any(
    (table) => table.columns.any(
      (column) =>
          column.typeKind == ColumnTypeKind.date ||
          column.boundTypeKind == ColumnTypeKind.date,
    ),
  );
  final usesBinaryColumns = database.tables.any(
    (table) => table.columns.any(
      (column) => column.typeKind == ColumnTypeKind.binary,
    ),
  );
  // Caller-provided values are encoded before they are written into source:
  // a line terminator in a schema name would escape the comment, and a
  // quote in the import URI would escape the import string.
  final schemasComment = database.schemaNames
      .map((name) => name.replaceAll(_lineTerminators, ' '))
      .join(', ');
  final buffer = StringBuffer()
    ..writeln(
      '// Generated by supabase_typegen $version from GeneratorMetadata '
      'version ${database.metadataVersion}.',
    )
    ..writeln('// Do not edit by hand.')
    ..writeln('//')
    ..writeln('// Source schemas: $schemasComment')
    ..writeln()
    ..writeln('// The typed table access API is still experimental.')
    ..writeln('// ignore_for_file: experimental_member_use')
    ..writeln();
  if (usesBinaryColumns) {
    buffer
      ..writeln("import 'dart:typed_data';")
      ..writeln();
  }
  buffer
    ..writeln('import ${_stringLiteral(importUri)};')
    ..writeln();

  final typeNames = _TypeNameRegistry();
  final enumTypeNames = <(String, String), String>{};

  for (final enumDescription in database.enums) {
    final typeName = typeNames.claim(
      _typeBaseName(enumDescription.schema, enumDescription.name),
    );
    enumTypeNames[(enumDescription.schema, enumDescription.name)] = typeName;
    _writeEnum(buffer, enumDescription, typeName);
  }

  final tables = [
    for (final table in database.tables)
      if (table.columns.isNotEmpty) table,
  ];
  final tableNames = {
    for (final table in tables)
      (table.schema, table.name): _TableNames.claim(table, typeNames),
  };
  final tableMembers = {
    for (final table in tables)
      (table.schema, table.name): _TableMembers.claim(
        table,
        tableNames[(table.schema, table.name)]!,
      ),
  };
  for (final table in tables) {
    _writeTable(
      buffer,
      table,
      tableNames[(table.schema, table.name)]!,
      tableMembers[(table.schema, table.name)]!,
      _relationMembers(table, database, tableNames, tableMembers),
      enumTypeNames,
    );
  }

  if (usesDateColumns) {
    buffer
      ..writeln('String _dateString(DateTime date) =>')
      ..writeln("    '\${date.year.toString().padLeft(4, '0')}-'")
      ..writeln("    '\${date.month.toString().padLeft(2, '0')}-'")
      ..writeln("    '\${date.day.toString().padLeft(2, '0')}';")
      ..writeln();
  }

  return DartFormatter(
    languageVersion: formatVersion,
  ).format(buffer.toString());
}

/// The PascalCase base of the type names of a schema object: the object name
/// alone for `public`, prefixed with the schema for any other schema.
String _typeBaseName(String schema, String name) =>
    schema == 'public' ? pascalCase(name) : pascalCase('${schema}_$name');

/// The name a schema object is referred to by in documentation: bare for
/// `public`, schema-qualified otherwise.
String _displayName(String schema, String name) =>
    schema == 'public' ? name : '$schema.$name';

/// Hands out unique top level type names, suffixing `$` on collisions.
///
/// Starts out with every identifier the generated source references
/// unqualified, so a schema object named like one of them (for example an
/// enum named `string`) cannot shadow it.
class _TypeNameRegistry {
  final _used = {
    'String',
    'Object',
    'Map',
    'MapEntry',
    'List',
    'DateTime',
    'Uint8List',
    'int',
    'double',
    'num',
    'bool',
    'Never',
    'PostgrestTable',
    'PostgrestColumn',
    'PostgrestNullableColumn',
    'PostgrestVectorColumn',
    'PostgrestNullableVectorColumn',
    'PostgrestRange',
    'PostgrestRelation',
    'PostgrestToOneRelation',
    'PostgrestToManyRelation',
  };

  String claim(String name) => _claimName(_used, name);
}

void _writeEnum(
  StringBuffer buffer,
  EnumDescription enumDescription,
  String typeName,
) {
  final valueNames = _uniqueMemberNames(
    enumDescription.values,
    reserved: {
      typeName,
      'index',
      'name',
      'values',
      'wireName',
      'fromWire',
      'toString',
      'hashCode',
      'runtimeType',
      'noSuchMethod',
    },
  );

  _writeDocComment(buffer, 'Postgres enum `${enumDescription.qualifiedName}`.');
  buffer.writeln('enum $typeName {');
  for (final value in enumDescription.values) {
    buffer.writeln("  ${valueNames[value]}(${_stringLiteral(value)}),");
  }
  buffer
    ..writeln(';')
    ..writeln()
    ..writeln('  const $typeName(this.wireName);')
    ..writeln()
    ..writeln('  /// The value as stored in the database.')
    ..writeln('  final String wireName;')
    ..writeln()
    ..writeln('  /// Parses the database representation of the enum.')
    ..writeln('  static $typeName fromWire(String wireName) =>')
    ..writeln('      values.firstWhere(')
    ..writeln('        (value) => value.wireName == wireName,')
    ..writeln('        orElse: () => throw ArgumentError.value(')
    ..writeln('          wireName,')
    ..writeln("          'wireName',")
    ..writeln(
      '          ${_stringLiteral('No $typeName value with this wire name')},',
    )
    ..writeln('        ),')
    ..writeln('      );')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  String toString() => wireName;')
    ..writeln('}')
    ..writeln();
}

/// The generated type names of one table, claimed in a fixed order so a
/// collision always resolves the same way.
class _TableNames {
  const _TableNames({
    required this.rowType,
    required this.insertType,
    required this.updateType,
    required this.namespaceType,
    required this.displayName,
  });

  factory _TableNames.claim(
    TableDescription table,
    _TypeNameRegistry typeNames,
  ) {
    final baseName = _typeBaseName(table.schema, table.name);
    return _TableNames(
      rowType: typeNames.claim('${baseName}Row'),
      insertType: table.isInsertable
          ? typeNames.claim('${baseName}Insert')
          : null,
      updateType: table.isUpdatable
          ? typeNames.claim('${baseName}Update')
          : null,
      namespaceType: typeNames.claim(baseName),
      displayName: _displayName(table.schema, table.name),
    );
  }

  final String rowType;
  final String? insertType;
  final String? updateType;
  final String namespaceType;

  /// The table name as written in documentation comments.
  final String displayName;
}

/// One relation member of a namespace class, before its Dart name is settled
/// against the table's columns.
/// The member identifiers of one table: [rowMembers] for the getters of the
/// row and value types, [columnMembers] for the column constants of the
/// namespace class, both keyed by column name.
class _TableMembers {
  const _TableMembers({required this.rowMembers, required this.columnMembers});

  factory _TableMembers.claim(TableDescription table, _TableNames names) {
    final _TableNames(:rowType, :insertType, :updateType, :namespaceType) =
        names;
    final columns = [for (final column in table.columns) column.name];
    // The row getters and the value constructor parameters share their
    // names, and both are in scope where the generated conversions call
    // the codecs, so a column of such a name may not claim it.
    final rowMembers = _uniqueMemberNames(
      columns,
      reserved: {
        rowType,
        ?insertType,
        ?updateType,
        'toJson',
        'postgrestBytea',
        'postgrestVector',
      },
    );
    return _TableMembers(
      rowMembers: rowMembers,
      columnMembers: _uniqueMemberNames(
        columns,
        reserved: {'table', namespaceType},
        existing: rowMembers,
      ),
    );
  }

  final Map<String, String> rowMembers;
  final Map<String, String> columnMembers;
}

class _RelationMember {
  const _RelationMember({
    required this.baseName,
    required this.disambiguatedName,
    required this.type,
    required this.embedName,
    required this.columns,
    required this.referencedTable,
    required this.referencedColumns,
    required this.docLine,
  });

  /// The name used when nothing else in the namespace claims it.
  final String baseName;

  /// The name used when [baseName] collides, spelling out the foreign key
  /// columns.
  final String disambiguatedName;

  /// `PostgrestToOneRelation<SourceRow, TargetRow>` or the to-many kind.
  final String type;

  /// The name PostgREST addresses the embed by, with a foreign key hint when
  /// the plain table name would be ambiguous.
  final String embedName;

  /// The column constants of this table the relation joins on.
  final List<String> columns;

  /// The name of the table the relation points at.
  final String referencedTable;

  /// The column constants of the referenced table, qualified with its
  /// namespace class.
  final List<String> referencedColumns;

  final String docLine;
}

/// The relation members of [table]: one to-one member per foreign key it
/// holds, and one to-many (or to-one, for a unique key) member per foreign
/// key pointing at it.
///
/// A self-referential key produces no member. PostgREST cannot tell the two
/// directions of such an embed apart and needs a computed relationship, so a
/// generated member could never be requested. A key into another schema
/// produces no member either: PostgREST resolves embeds within the schema of
/// the request only.
List<_RelationMember> _relationMembers(
  TableDescription table,
  DatabaseDescription database,
  Map<(String, String), _TableNames> tableNames,
  Map<(String, String), _TableMembers> tableMembers,
) {
  final members = <_RelationMember>[];
  for (final relationship in database.relationships) {
    final sourceKey = (relationship.sourceSchema, relationship.sourceTable);
    final targetKey = (relationship.targetSchema, relationship.targetTable);
    final source = tableNames[sourceKey];
    final target = tableNames[targetKey];
    if (source == null || target == null) continue;
    if (sourceKey == targetKey) continue;
    if (relationship.sourceSchema != relationship.targetSchema) continue;
    final sourceColumns = _columnConstants(
      relationship.sourceColumns,
      source.displayName,
      tableMembers[sourceKey]!.columnMembers,
      keyDescription: 'the foreign key "${relationship.foreignKeyName}"',
    );
    final targetColumns = _columnConstants(
      relationship.targetColumns,
      target.displayName,
      tableMembers[targetKey]!.columnMembers,
      keyDescription: 'the foreign key "${relationship.foreignKeyName}"',
    );
    final columns = relationship.sourceColumns.join('_');
    // `By` names the key this table holds, `Via` the key the other table
    // holds.
    final byColumns = 'By${pascalCase(columns)}';
    final viaColumns = 'Via${pascalCase(columns)}';
    // Several keys between the same two tables make the plain table name
    // ambiguous for PostgREST, so the embed carries the hint.
    final ambiguous = database.relationships.any(
      (other) =>
          other != relationship &&
          (other.sourceSchema, other.sourceTable) == sourceKey &&
          (other.targetSchema, other.targetTable) == targetKey,
    );

    if (sourceKey == (table.schema, table.name)) {
      final targetName = memberIdentifier(relationship.targetTable);
      members.add(
        _RelationMember(
          baseName: ambiguous ? '$targetName$byColumns' : targetName,
          disambiguatedName: '$targetName$byColumns',
          type: 'PostgrestToOneRelation<${source.rowType}, ${target.rowType}>',
          embedName: ambiguous
              ? '${relationship.targetTable}!${relationship.foreignKeyName}'
              : relationship.targetTable,
          columns: sourceColumns,
          referencedTable: relationship.targetTable,
          referencedColumns: [
            for (final column in targetColumns)
              '${target.namespaceType}.$column',
          ],
          docLine:
              'The `${target.displayName}` row referenced by '
              '`$columns`.',
        ),
      );
    }
    if (targetKey == (table.schema, table.name)) {
      final sourceName = memberIdentifier(relationship.sourceTable);
      final kind = relationship.isOneToOne
          ? 'PostgrestToOneRelation'
          : 'PostgrestToManyRelation';
      members.add(
        _RelationMember(
          baseName: ambiguous ? '$sourceName$viaColumns' : sourceName,
          disambiguatedName: '$sourceName$viaColumns',
          type: '$kind<${target.rowType}, ${source.rowType}>',
          embedName: ambiguous
              ? '${relationship.sourceTable}!${relationship.foreignKeyName}'
              : relationship.sourceTable,
          columns: targetColumns,
          referencedTable: relationship.sourceTable,
          referencedColumns: [
            for (final column in sourceColumns)
              '${source.namespaceType}.$column',
          ],
          docLine:
              'The `${source.displayName}` '
              '${relationship.isOneToOne ? 'row' : 'rows'} referencing this '
              'row through `$columns`.',
        ),
      );
    }
  }
  return members;
}

/// The column constants of [columns] in the namespace of [table].
///
/// A key over a column the document does not list for its table is a
/// malformed document rather than something to generate around: dropping the
/// column would silently change which rows the key identifies.
List<String> _columnConstants(
  List<String> columns,
  String table,
  Map<String, String> columnNames, {
  required String keyDescription,
}) => [
  for (final column in columns)
    columnNames[column] ??
        (throw FormatException(
          'Not a GeneratorMetadata document: $keyDescription names the '
          'column "$column", which the document does not list for the '
          'table "$table".',
        )),
];

void _writeTable(
  StringBuffer buffer,
  TableDescription table,
  _TableNames names,
  _TableMembers members,
  List<_RelationMember> relations,
  Map<(String, String), String> enumTypeNames,
) {
  final _TableNames(:insertType, :updateType) = names;

  final memberNames = members.rowMembers;
  final bindings = {
    for (final column in table.columns)
      column.name: _bindingFor(column, enumTypeNames),
  };

  _writeRow(buffer, table, names, memberNames, bindings);
  if (insertType != null) {
    _writeValues(
      buffer,
      table,
      insertType,
      memberNames,
      bindings,
      requireRequiredColumns: true,
      docLine:
          'Values for inserting a row into `${names.displayName}`. Columns '
          'that are nullable, identity, or covered by a database default are '
          'optional; '
          'passing `null` omits the column so the database default applies. '
          'Columns the database always generates itself are left out '
          'entirely. Use the `set…ToNull` methods to insert SQL NULL '
          'explicitly.',
    );
  }
  if (updateType != null) {
    _writeValues(
      buffer,
      table,
      updateType,
      memberNames,
      bindings,
      requireRequiredColumns: false,
      docLine:
          'Values for updating rows of `${names.displayName}`. All columns '
          'are optional; passing `null` omits the column, leaving it '
          'unchanged. '
          'Use the `set…ToNull` methods to write SQL NULL explicitly.',
    );
  }
  _writeNamespace(
    buffer,
    table,
    names,
    members.columnMembers,
    bindings,
    relations,
  );
}

void _writeRow(
  StringBuffer buffer,
  TableDescription table,
  _TableNames names,
  Map<String, String> memberNames,
  Map<String, _Binding> bindings,
) {
  final rowType = names.rowType;
  _writeDocComment(buffer, 'A row of the `${names.displayName}` table.');
  _writeDocComment(buffer, table.comment);
  buffer
    ..writeln('extension type const $rowType(Map<String, dynamic> _json)')
    ..writeln('    implements Object {');
  for (final column in table.columns) {
    final binding = bindings[column.name]!;
    _writeDocComment(buffer, column.comment, indent: '  ');
    buffer.writeln(
      '  ${_getterType(column, binding)} get ${memberNames[column.name]} => '
      '${_readExpression(column, binding)};',
    );
  }
  buffer
    ..writeln()
    ..writeln('  /// The row as decoded from the response.')
    ..writeln('  Map<String, dynamic> toJson() => _json;')
    ..writeln('}')
    ..writeln();
}

void _writeValues(
  StringBuffer buffer,
  TableDescription table,
  String typeName,
  Map<String, String> memberNames,
  Map<String, _Binding> bindings, {
  required bool requireRequiredColumns,
  required String docLine,
}) {
  bool isRequired(ColumnDescription column) =>
      requireRequiredColumns && column.isRequired;
  final writableColumns = [
    for (final column in table.columns)
      if (!column.isReadOnly) column,
  ];

  _writeDocComment(buffer, docLine);
  buffer
    ..writeln('extension type const $typeName._(Map<String, dynamic> _json)')
    ..writeln('    implements Object {');
  if (writableColumns.isEmpty) {
    // A named parameter list cannot be empty, so a table whose columns are
    // all read-only gets a parameterless constructor.
    buffer.writeln('  $typeName() : this._({});');
  } else {
    buffer.writeln('  $typeName({');
    for (final column in writableColumns) {
      final binding = bindings[column.name]!;
      final name = memberNames[column.name]!;
      if (isRequired(column)) {
        buffer.writeln('    required ${binding.dartType} $name,');
      } else {
        buffer.writeln('    ${binding.dartType}? $name,');
      }
    }
    buffer.writeln('  }) : this._({');
    for (final column in writableColumns) {
      final binding = bindings[column.name]!;
      final name = memberNames[column.name]!;
      final key = _stringLiteral(column.name);
      if (isRequired(column)) {
        buffer.writeln(
          '         $key: ${_writeExpression(name, binding, nullable: false)},',
        );
      } else {
        buffer.writeln(
          '         $key: ?${_writeExpression(name, binding, nullable: true)},',
        );
      }
    }
    buffer.writeln('       });');
  }
  for (final column in writableColumns) {
    if (!column.isNullable) continue;
    final name = memberNames[column.name]!;
    final methodName = 'set${name[0].toUpperCase()}${name.substring(1)}ToNull';
    buffer.writeln();
    _writeDocComment(
      buffer,
      'Returns a copy with `${column.name}` set to SQL NULL, overriding any '
      'database default.',
      indent: '  ',
    );
    buffer.writeln(
      '  $typeName $methodName() => '
      '$typeName._({..._json, ${_stringLiteral(column.name)}: null});',
    );
  }
  buffer
    ..writeln('}')
    ..writeln();
}

void _writeNamespace(
  StringBuffer buffer,
  TableDescription table,
  _TableNames names,
  Map<String, String> columnNames,
  Map<String, _Binding> bindings,
  List<_RelationMember> relations,
) {
  final _TableNames(:rowType, :insertType, :updateType, :namespaceType) = names;
  final used = {'table', namespaceType, ...columnNames.values};
  final baseNameCounts = <String, int>{};
  for (final relation in relations) {
    baseNameCounts.update(
      relation.baseName,
      (count) => count + 1,
      ifAbsent: () => 1,
    );
  }
  final relationNames = [
    for (final relation in relations)
      _claimName(
        used,
        used.contains(relation.baseName) ||
                baseNameCounts[relation.baseName]! > 1
            ? relation.disambiguatedName
            : relation.baseName,
      ),
  ];

  final primaryKey = _columnConstants(
    table.primaryKey,
    names.displayName,
    columnNames,
    keyDescription: 'the primary key',
  );
  _writeDocComment(buffer, 'Typed access to the `${names.displayName}` table.');
  buffer
    ..writeln('class $namespaceType {')
    ..writeln('  const $namespaceType._();')
    ..writeln()
    ..writeln('  /// Table definition for [PostgrestClient.table].')
    ..writeln(
      '  static const table = PostgrestTable<$rowType, '
      '${insertType ?? 'Never'}, ${updateType ?? 'Never'}>(',
    )
    ..writeln('    ${_stringLiteral(table.name)},')
    ..writeln('    $rowType.new,')
    ..writeln('    schema: ${_stringLiteral(table.schema)},')
    ..writeln('    primaryKey: [${primaryKey.join(', ')}],');
  if (relations.isNotEmpty) {
    buffer.writeln('    relations: [${relationNames.join(', ')}],');
  }
  buffer
    ..writeln('  );')
    ..writeln();
  for (final column in table.columns) {
    final binding = bindings[column.name]!;
    final columnType = switch ((binding.kind, column.isNullable)) {
      (ColumnTypeKind.vector, true) =>
        'PostgrestNullableVectorColumn<$rowType>',
      (ColumnTypeKind.vector, false) => 'PostgrestVectorColumn<$rowType>',
      (_, true) => 'PostgrestNullableColumn<$rowType, ${binding.dartType}>',
      (_, false) => 'PostgrestColumn<$rowType, ${binding.dartType}>',
    };
    buffer.writeln(
      '  static const ${columnNames[column.name]} = '
      '$columnType(${_stringLiteral(column.name)});',
    );
  }
  for (final (index, relation) in relations.indexed) {
    buffer.writeln();
    _writeDocComment(buffer, relation.docLine, indent: '  ');
    buffer
      ..writeln(
        '  static const ${relationNames[index]} = ${relation.type}(',
      )
      ..writeln('    ${_stringLiteral(relation.embedName)},')
      ..writeln('    columns: [${relation.columns.join(', ')}],')
      ..writeln(
        '    referencedTable: ${_stringLiteral(relation.referencedTable)},',
      )
      ..writeln(
        '    referencedColumns: [${relation.referencedColumns.join(', ')}],',
      )
      ..writeln('  );');
  }
  buffer
    ..writeln('}')
    ..writeln();
}

_Binding _bindingFor(
  ColumnDescription column,
  Map<(String, String), String> enumTypeNames,
) => switch (column.typeKind) {
  ColumnTypeKind.enumType => _Binding(
    _enumTypeName(column, enumTypeNames),
    ColumnTypeKind.enumType,
  ),
  ColumnTypeKind.array => _Binding(
    'List<${_elementDartType(column.elementTypeKind)}>',
    ColumnTypeKind.array,
  ),
  ColumnTypeKind.integer => const _Binding('int', ColumnTypeKind.integer),
  ColumnTypeKind.floating => const _Binding('double', ColumnTypeKind.floating),
  ColumnTypeKind.numeric => const _Binding('num', ColumnTypeKind.numeric),
  ColumnTypeKind.boolean => const _Binding('bool', ColumnTypeKind.boolean),
  ColumnTypeKind.date => const _Binding('DateTime', ColumnTypeKind.date),
  ColumnTypeKind.timestamp => const _Binding(
    'DateTime',
    ColumnTypeKind.timestamp,
  ),
  ColumnTypeKind.timestampWithTimeZone => const _Binding(
    'DateTime',
    ColumnTypeKind.timestampWithTimeZone,
  ),
  ColumnTypeKind.text => const _Binding('String', ColumnTypeKind.text),
  ColumnTypeKind.binary => const _Binding('Uint8List', ColumnTypeKind.binary),
  ColumnTypeKind.vector => const _Binding(
    'List<double>',
    ColumnTypeKind.vector,
  ),
  ColumnTypeKind.range => _Binding(
    'PostgrestRange<${_boundDartType(column.boundTypeKind)}>',
    ColumnTypeKind.range,
    boundKind: column.boundTypeKind,
  ),
  ColumnTypeKind.json ||
  ColumnTypeKind.unknown => const _Binding('Object', ColumnTypeKind.json),
};

/// The generated Dart enum of an enum [column], resolved by the schema and
/// name of its Postgres enum rather than by a qualified string, which could
/// not tell `tenant.v1`.`status` from `tenant`.`v1.status`.
String _enumTypeName(
  ColumnDescription column,
  Map<(String, String), String> enumTypeNames,
) {
  final enumType = column.enumType;
  if (enumType == null) {
    throw ArgumentError.value(
      column,
      'column',
      'An enum column has to name its enum type.',
    );
  }
  return enumTypeNames[(enumType.schema, enumType.name)] ??
      (throw ArgumentError.value(
        column,
        'column',
        'The enum ${enumType.qualifiedName} is not among the described enums.',
      ));
}

String _boundDartType(ColumnTypeKind? boundTypeKind) => switch (boundTypeKind) {
  ColumnTypeKind.integer => 'int',
  ColumnTypeKind.numeric => 'num',
  ColumnTypeKind.date ||
  ColumnTypeKind.timestamp ||
  ColumnTypeKind.timestampWithTimeZone => 'DateTime',
  ColumnTypeKind.floating ||
  ColumnTypeKind.boolean ||
  ColumnTypeKind.text ||
  ColumnTypeKind.binary ||
  ColumnTypeKind.vector ||
  ColumnTypeKind.json ||
  ColumnTypeKind.enumType ||
  ColumnTypeKind.array ||
  ColumnTypeKind.range ||
  ColumnTypeKind.unknown ||
  null => 'String',
};

/// The function that reads one bound of a range literal.
String _boundParser(ColumnTypeKind? boundTypeKind) => switch (boundTypeKind) {
  ColumnTypeKind.integer => 'int.parse',
  ColumnTypeKind.numeric => 'num.parse',
  ColumnTypeKind.date ||
  ColumnTypeKind.timestamp ||
  ColumnTypeKind.timestampWithTimeZone => 'DateTime.parse',
  ColumnTypeKind.floating ||
  ColumnTypeKind.boolean ||
  ColumnTypeKind.text ||
  ColumnTypeKind.binary ||
  ColumnTypeKind.vector ||
  ColumnTypeKind.json ||
  ColumnTypeKind.enumType ||
  ColumnTypeKind.array ||
  ColumnTypeKind.range ||
  ColumnTypeKind.unknown ||
  null => '(bound) => bound',
};

String _elementDartType(ColumnTypeKind? elementTypeKind) =>
    switch (elementTypeKind) {
      ColumnTypeKind.integer => 'int',
      ColumnTypeKind.floating => 'double',
      ColumnTypeKind.numeric => 'num',
      ColumnTypeKind.boolean => 'bool',
      // Temporal, enum, range, binary and vector elements stay in their wire
      // representation, a documented limitation of array columns.
      ColumnTypeKind.text ||
      ColumnTypeKind.binary ||
      ColumnTypeKind.vector ||
      ColumnTypeKind.date ||
      ColumnTypeKind.timestamp ||
      ColumnTypeKind.timestampWithTimeZone ||
      ColumnTypeKind.enumType ||
      ColumnTypeKind.range => 'String',
      ColumnTypeKind.json ||
      ColumnTypeKind.array ||
      ColumnTypeKind.unknown ||
      null => 'Object',
    };

String _getterType(ColumnDescription column, _Binding binding) {
  if (binding.kind == ColumnTypeKind.json) return 'Object?';
  return column.isNullable ? '${binding.dartType}?' : binding.dartType;
}

String _readExpression(ColumnDescription column, _Binding binding) {
  final access = "_json[${_stringLiteral(column.name)}]";
  final nullable = column.isNullable;
  return switch (binding.kind) {
    ColumnTypeKind.integer ||
    ColumnTypeKind.numeric ||
    ColumnTypeKind.boolean ||
    ColumnTypeKind.text =>
      '$access as ${binding.dartType}${nullable ? '?' : ''}',
    ColumnTypeKind.floating =>
      nullable
          ? '($access as num?)?.toDouble()'
          : '($access as num).toDouble()',
    // PostgREST encodes integral elements of floating point arrays as JSON
    // integers, so floating elements convert through num like the scalars
    // instead of a lazy cast that would throw on access.
    ColumnTypeKind.array
        when column.elementTypeKind == ColumnTypeKind.floating =>
      nullable
          ? '($access as List<dynamic>?)'
                '?.map((element) => (element as num).toDouble()).toList()'
          : '($access as List<dynamic>)'
                '.map((element) => (element as num).toDouble()).toList()',
    ColumnTypeKind.array =>
      nullable
          ? '($access as List<dynamic>?)?.cast()'
          : '($access as List<dynamic>).cast()',
    ColumnTypeKind.date ||
    ColumnTypeKind.timestamp ||
    ColumnTypeKind.timestampWithTimeZone =>
      nullable
          ? _nullableSwitch(access, 'DateTime.parse(value as String)')
          : 'DateTime.parse($access as String)',
    ColumnTypeKind.enumType =>
      nullable
          ? _nullableSwitch(
              access,
              '${binding.dartType}.fromWire(value as String)',
            )
          : '${binding.dartType}.fromWire($access as String)',
    ColumnTypeKind.binary =>
      nullable
          ? _nullableSwitch(access, 'postgrestBytea.decode(value as String)')
          : 'postgrestBytea.decode($access as String)',
    ColumnTypeKind.vector =>
      nullable
          ? _nullableSwitch(access, 'postgrestVector.decode(value as String)')
          : 'postgrestVector.decode($access as String)',
    ColumnTypeKind.range =>
      nullable
          ? _nullableSwitch(
              access,
              'PostgrestRange.parse(value as String, '
              '${_boundParser(binding.boundKind)})',
            )
          : 'PostgrestRange.parse($access as String, '
                '${_boundParser(binding.boundKind)})',
    ColumnTypeKind.json || ColumnTypeKind.unknown => '$access as Object?',
  };
}

String _nullableSwitch(String access, String conversion) =>
    'switch ($access) { null => null, final Object value => $conversion }';

String _writeExpression(
  String parameterName,
  _Binding binding, {
  required bool nullable,
}) {
  final access = nullable ? '$parameterName?' : parameterName;
  return switch (binding.kind) {
    ColumnTypeKind.date =>
      nullable
          ? 'switch ($parameterName) '
                '{ null => null, final value => _dateString(value) }'
          : '_dateString($parameterName)',
    ColumnTypeKind.timestamp => '$access.toIso8601String()',
    ColumnTypeKind.timestampWithTimeZone =>
      nullable
          ? '$access.toUtc().toIso8601String()'
          : '$parameterName.toUtc().toIso8601String()',
    ColumnTypeKind.enumType => '$access.wireName',
    ColumnTypeKind.binary =>
      nullable
          ? 'switch ($parameterName) '
                '{ null => null, final value => postgrestBytea.encode(value) }'
          : 'postgrestBytea.encode($parameterName)',
    ColumnTypeKind.vector =>
      nullable
          ? 'switch ($parameterName) '
                '{ null => null, final value => postgrestVector.encode(value) }'
          : 'postgrestVector.encode($parameterName)',
    ColumnTypeKind.range => switch (binding.boundKind) {
      ColumnTypeKind.date => '$access.render(_dateString)',
      ColumnTypeKind.timestamp =>
        '$access.render((bound) => bound.toIso8601String())',
      ColumnTypeKind.timestampWithTimeZone =>
        '$access.render((bound) => bound.toUtc().toIso8601String())',
      ColumnTypeKind.integer ||
      ColumnTypeKind.numeric ||
      ColumnTypeKind.floating ||
      ColumnTypeKind.boolean ||
      ColumnTypeKind.text ||
      ColumnTypeKind.binary ||
      ColumnTypeKind.vector ||
      ColumnTypeKind.json ||
      ColumnTypeKind.enumType ||
      ColumnTypeKind.array ||
      ColumnTypeKind.range ||
      ColumnTypeKind.unknown ||
      null => '$access.literal',
    },
    ColumnTypeKind.integer ||
    ColumnTypeKind.floating ||
    ColumnTypeKind.numeric ||
    ColumnTypeKind.boolean ||
    ColumnTypeKind.text ||
    ColumnTypeKind.array ||
    ColumnTypeKind.json ||
    ColumnTypeKind.unknown => parameterName,
  };
}

/// Maps raw database names to unique Dart member identifiers.
///
/// [reserved] seeds identifiers that must not be produced. When [existing] is
/// given, names are kept identical to it where possible so that, for example,
/// column tokens and row getters share their spelling.
Map<String, String> _uniqueMemberNames(
  List<String> names, {
  Set<String> reserved = const {},
  Map<String, String>? existing,
}) {
  final used = {...reserved};
  return {
    for (final name in names)
      name: _claimName(used, existing?[name] ?? memberIdentifier(name)),
  };
}

/// Adds [candidate] to [used], suffixed with `\$` until no earlier name
/// matches, and returns the name added.
String _claimName(Set<String> used, String candidate) {
  var name = candidate;
  while (!used.add(name)) {
    name = '$name\$';
  }
  return name;
}

void _writeDocComment(
  StringBuffer buffer,
  String? comment, {
  String indent = '',
}) {
  if (comment == null) return;
  final width = 80 - indent.length - '/// '.length;
  for (final line in comment.trim().split(_lineTerminators)) {
    for (final wrapped in _wrap(line.trim(), width)) {
      buffer.writeln('$indent/// $wrapped');
    }
  }
}

/// Every Dart source line terminator: a comment line broken on LF alone
/// would let a CR or U+2028/U+2029 end the generated `///` comment early and
/// turn the remainder into source code.
final _lineTerminators = RegExp('\\r\\n?|[\\n\\u2028\\u2029]');

/// Greedily wraps [text] into lines of at most [width] characters, keeping
/// words longer than [width] on their own line.
Iterable<String> _wrap(String text, int width) sync* {
  final words = text.split(' ').where((word) => word.isNotEmpty);
  final line = StringBuffer();
  for (final word in words) {
    if (line.isNotEmpty && line.length + 1 + word.length > width) {
      yield line.toString();
      line.clear();
    }
    if (line.isNotEmpty) line.write(' ');
    line.write(word);
  }
  if (line.isNotEmpty) yield line.toString();
}

String _stringLiteral(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r')
      .replaceAll('\t', r'\t')
      .replaceAll('\u2028', r'\u{2028}')
      .replaceAll('\u2029', r'\u{2029}');
  return "'$escaped'";
}
