import 'package:dart_style/dart_style.dart';
import 'package:pub_semver/pub_semver.dart';

import 'identifiers.dart';
import 'language_version_io.dart';
import 'sdk_formatter_io.dart';
import 'schema_description.dart';
import 'version.dart';

class _Binding {
  const _Binding(this.dartType, this.kind, {this.boundKind, this.element});

  /// The non-nullable Dart type of the column.
  final String dartType;
  final ColumnTypeKind kind;

  /// The kind of the bounds of a [ColumnTypeKind.range] column.
  final ColumnTypeKind? boundKind;

  /// The binding of the elements of a [ColumnTypeKind.array] column.
  final _Binding? element;
}

/// The lowest language version the generated code is valid for: the value
/// types omit unset columns with null-aware map elements, which need Dart
/// 3.8.
final minimumLanguageVersion = Version(3, 8, 0);

/// Generates a Dart source file with typed table definitions, row extension
/// types, insert and update value types, column tokens, computed fields,
/// relations and Postgres enums for the schemas of [database].
///
/// Objects of the `public` schema are named after themselves, `books` becomes
/// `Books` and `BooksRow`; objects of any other schema carry the schema as a
/// prefix, so `inventory.books` becomes `InventoryBooks` and
/// `InventoryBooksRow`.
///
/// The generated code depends only on the library at [importUri], which must
/// export the typed table access API of `package:postgrest` (`PostgrestTable`,
/// `PostgrestColumn`, `PostgrestNullableColumn`, `PostgrestVectorColumn`,
/// `PostgrestNullableVectorColumn`, `PostgrestComputedField`,
/// `PostgrestRange`, `PostgrestDate`, `PostgrestTime`, `PostgrestInterval`,
/// `PostgrestToOneRelation`, `PostgrestToManyRelation`, `postgrestBytea` and
/// `postgrestVector`); pass the library [packageImportUri] finds for the
/// project the file is written into.
///
/// The code is formatted for [languageVersion], so it uses no syntax a
/// project on that language version rejects; pass the version
/// [packageLanguageVersion] finds for the project the file is written into.
/// It defaults to, and is never lower than, [minimumLanguageVersion]. To
/// match the formatter of a project exactly, pass the result through
/// [formatWithSdk] as well.
String generateDartCode(
  DatabaseDescription database, {
  String importUri = 'package:postgrest/postgrest.dart',
  Version? languageVersion,
}) {
  final formatVersion =
      languageVersion == null || languageVersion < minimumLanguageVersion
      ? minimumLanguageVersion
      : languageVersion;
  final usesBinaryColumns = database.tables.any(
    (table) =>
        [
          for (final column in table.columns) _columnShape(column),
          for (final field in table.computedFields) _computedFieldShape(field),
        ].any(
          (shape) =>
              shape.typeKind == ColumnTypeKind.binary ||
              shape.elementTypeKind == ColumnTypeKind.binary,
        ),
  );
  // Caller-provided values are encoded before they are written into source:
  // a line terminator in a schema name would escape the comment, and a
  // quote in the import URI would escape the import string.
  final schemasComment = database.schemaNames
      .map((name) => name.replaceAll(_lineTerminators, ' '))
      .join(', ');
  final buffer = StringBuffer()
    ..writeln(
      '// Generated by supabase_typegen $version from GeneratorMetadata '
      'version ${database.metadataVersion}.',
    )
    ..writeln('// Do not edit by hand.')
    ..writeln('//')
    ..writeln('// Source schemas: $schemasComment')
    ..writeln()
    ..writeln('// The typed table access API is still experimental.')
    ..writeln('// ignore_for_file: experimental_member_use')
    ..writeln();
  if (usesBinaryColumns) {
    buffer
      ..writeln("import 'dart:typed_data';")
      ..writeln();
  }
  buffer
    ..writeln('import ${_stringLiteral(importUri)};')
    ..writeln();

  final typeNames = _TypeNameRegistry();
  final enumTypeNames = <(String, String), String>{};
  final decoders = _DecoderRegistry();

  for (final enumDescription in database.enums) {
    final typeName = typeNames.claim(
      _typeBaseName(enumDescription.schema, enumDescription.name),
    );
    enumTypeNames[(enumDescription.schema, enumDescription.name)] = typeName;
    _writeEnum(buffer, enumDescription, typeName);
  }

  final tables = [
    for (final table in database.tables)
      if (table.columns.isNotEmpty) table,
  ];
  final tableNames = {
    for (final table in tables)
      (table.schema, table.name): _TableNames.claim(table, typeNames),
  };
  final tableMembers = {
    for (final table in tables)
      (table.schema, table.name): _TableMembers.claim(
        table,
        typeNames.taken,
      ),
  };
  for (final table in tables) {
    _writeTable(
      buffer,
      table,
      tableNames[(table.schema, table.name)]!,
      tableMembers[(table.schema, table.name)]!,
      _relationMembers(table, database, tableNames, tableMembers),
      typeNames.taken,
      enumTypeNames,
      decoders,
    );
  }
  decoders.write(buffer);

  return DartFormatter(
    languageVersion: formatVersion,
  ).format(buffer.toString());
}

/// The PascalCase base of the type names of a schema object: the object name
/// alone for `public`, prefixed with the schema for any other schema.
String _typeBaseName(String schema, String name) =>
    schema == 'public' ? pascalCase(name) : pascalCase('${schema}_$name');

/// The name a schema object is referred to by in documentation: bare for
/// `public`, schema-qualified otherwise.
String _displayName(String schema, String name) =>
    schema == 'public' ? name : '$schema.$name';

/// Hands out unique top level type names, suffixing `$` on collisions.
///
/// Starts out with every identifier the generated source references
/// unqualified, so a schema object named like one of them (for example an
/// enum named `string`) cannot shadow it.
class _TypeNameRegistry {
  final _taken = {
    'String',
    'Object',
    'Map',
    'MapEntry',
    'List',
    'DateTime',
    'Uint8List',
    'int',
    'double',
    'num',
    'bool',
    'Never',
    'Function',
    'ArgumentError',
    'PostgrestTable',
    'PostgrestColumn',
    'PostgrestNullableColumn',
    'PostgrestVectorColumn',
    'PostgrestNullableVectorColumn',
    'PostgrestComputedField',
    'PostgrestRange',
    'PostgrestDate',
    'PostgrestTime',
    'PostgrestInterval',
    'PostgrestRelation',
    'PostgrestToOneRelation',
    'PostgrestToManyRelation',
  };

  String claim(String name) => _claimName(_taken, name);

  Set<String> get taken => _taken;
}

void _writeEnum(
  StringBuffer buffer,
  EnumDescription enumDescription,
  String typeName,
) {
  final valueNames = _uniqueMemberNames(
    enumDescription.values,
    reserved: {
      typeName,
      'index',
      'name',
      'values',
      'wireName',
      'fromWire',
      'toString',
      'hashCode',
      'runtimeType',
      'noSuchMethod',
    },
  );

  _writeDocComment(buffer, 'Postgres enum `${enumDescription.qualifiedName}`.');
  buffer.writeln('enum $typeName {');
  for (final value in enumDescription.values) {
    buffer.writeln("  ${valueNames[value]}(${_stringLiteral(value)}),");
  }
  buffer
    ..writeln(';')
    ..writeln()
    ..writeln('  const $typeName(this.wireName);')
    ..writeln()
    ..writeln('  /// The value as stored in the database.')
    ..writeln('  final String wireName;')
    ..writeln()
    ..writeln('  /// Parses the database representation of the enum.')
    ..writeln('  static $typeName fromWire(String wireName) =>')
    ..writeln('      values.firstWhere(')
    ..writeln('        (value) => value.wireName == wireName,')
    ..writeln('        orElse: () => throw ArgumentError.value(')
    ..writeln('          wireName,')
    ..writeln("          'wireName',")
    ..writeln(
      '          ${_stringLiteral('No $typeName value with this wire name')},',
    )
    ..writeln('        ),')
    ..writeln('      );')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  String toString() => wireName;')
    ..writeln('}')
    ..writeln();
}

/// The generated type names of one table, claimed in a fixed order so a
/// collision always resolves the same way.
class _TableNames {
  const _TableNames({
    required this.rowType,
    required this.insertType,
    required this.updateType,
    required this.namespaceType,
    required this.displayName,
  });

  factory _TableNames.claim(
    TableDescription table,
    _TypeNameRegistry typeNames,
  ) {
    final baseName = _typeBaseName(table.schema, table.name);
    return _TableNames(
      rowType: typeNames.claim('${baseName}Row'),
      insertType: table.isInsertable
          ? typeNames.claim('${baseName}Insert')
          : null,
      updateType: table.isUpdatable
          ? typeNames.claim('${baseName}Update')
          : null,
      namespaceType: typeNames.claim(baseName),
      displayName: _displayName(table.schema, table.name),
    );
  }

  final String rowType;
  final String? insertType;
  final String? updateType;
  final String namespaceType;

  /// The table name as written in documentation comments.
  final String displayName;
}

/// The member identifiers of one table: [rowMembers] for the getters of the
/// row and value types and [columnMembers] for the column constants of the
/// namespace class, both keyed by column name, and [computedFieldMembers] for
/// the computed field constants, keyed by function name.
class _TableMembers {
  const _TableMembers({
    required this.rowMembers,
    required this.columnMembers,
    required this.computedFieldMembers,
  });

  factory _TableMembers.claim(TableDescription table, Set<String> typeNames) {
    final columns = [for (final column in table.columns) column.name];
    // The row getters and the value constructor parameters share their
    // names, and both are in scope where the generated conversions call
    // the codecs, so a column of such a name may not claim it.
    final rowMembers = _uniqueMemberNames(
      columns,
      reserved: {
        ...typeNames,
        'toJson',
        'postgrestBytea',
        'postgrestVector',
      },
    );
    final columnMembers = _uniqueMemberNames(
      columns,
      reserved: {'table', ...typeNames},
      existing: rowMembers,
    );
    return _TableMembers(
      rowMembers: rowMembers,
      columnMembers: columnMembers,
      // Computed fields share the namespace with the column constants.
      computedFieldMembers: _uniqueMemberNames(
        [for (final field in table.computedFields) field.name],
        reserved: {'table', ...typeNames, ...columnMembers.values},
      ),
    );
  }

  final Map<String, String> rowMembers;
  final Map<String, String> columnMembers;
  final Map<String, String> computedFieldMembers;
}

class _RelationMember {
  const _RelationMember({
    required this.baseName,
    required this.disambiguatedName,
    required this.type,
    required this.embedName,
    required this.ambiguous,
    required this.columns,
    required this.referencedTable,
    required this.referencedColumns,
    required this.docLine,
    this.isComputed = false,
  });

  /// A computed relationship: the function called [embedName] takes a row of
  /// this table and returns rows of [referencedTable].
  factory _RelationMember.computed(
    ComputedRelationshipDescription relationship,
    _TableNames source,
    _TableNames target,
  ) {
    final name = memberIdentifier(relationship.name);
    final kind = relationship.isToMany
        ? 'PostgrestToManyRelation'
        : 'PostgrestToOneRelation';
    return _RelationMember(
      baseName: name,
      disambiguatedName: name,
      type: '$kind<${source.rowType}, ${target.rowType}>.computed',
      embedName: relationship.name,
      ambiguous: false,
      columns: const [],
      referencedTable: relationship.targetTable,
      referencedColumns: const [],
      docLine:
          'The `${target.displayName}` '
          '${relationship.isToMany ? 'rows' : 'row'} computed by '
          '`${relationship.name}`.',
      isComputed: true,
    );
  }

  /// The name used when nothing else in the namespace claims it.
  final String baseName;

  /// The name used when [baseName] collides, spelling out the foreign key
  /// columns.
  final String disambiguatedName;

  /// `PostgrestToOneRelation<SourceRow, TargetRow>` or the to-many kind.
  final String type;

  /// The name PostgREST addresses the embed by: the table name, with a
  /// foreign key hint when the plain name would be ambiguous, or the
  /// function name of a computed relationship.
  final String embedName;

  /// Whether the relation is a computed relationship rather than a foreign
  /// key, so it joins on no columns.
  final bool isComputed;

  /// The key the embedded rows come back under when the embed is not
  /// aliased: the table name, or the function name of a computed
  /// relationship.
  String get key => isComputed ? embedName : referencedTable;

  /// Whether another key joins the same two tables, so the embed carries a
  /// hint and is aliased to the member name to come back under its own key.
  final bool ambiguous;

  /// The column constants of this table the relation joins on.
  final List<String> columns;

  /// The name of the table the relation points at.
  final String referencedTable;

  /// The column constants of the referenced table, qualified with its
  /// namespace class.
  final List<String> referencedColumns;

  final String docLine;
}

/// The relation members of [table]: one to-one member per foreign key it
/// holds, and one to-many (or to-one, for a unique key) member per foreign
/// key pointing at it.
///
/// A self-referential key produces no member. PostgREST cannot tell the two
/// directions of such an embed apart and needs a computed relationship, so a
/// generated member could never be requested. A key into another schema
/// produces no member either: PostgREST resolves embeds within the schema of
/// the request only.
///
/// The computed relationships of [table] follow the foreign keys, one member
/// each, for every function whose return table is generated. A computed
/// relationship named like the table of a plain foreign key embed replaces
/// that embed: PostgREST resolves the unhinted name to the function, so the
/// foreign key gets no member of its own.
List<_RelationMember> _relationMembers(
  TableDescription table,
  DatabaseDescription database,
  Map<(String, String), _TableNames> tableNames,
  Map<(String, String), _TableMembers> tableMembers,
) {
  final members = <_RelationMember>[];
  for (final relationship in database.relationships) {
    final sourceKey = (relationship.sourceSchema, relationship.sourceTable);
    final targetKey = (relationship.targetSchema, relationship.targetTable);
    final source = tableNames[sourceKey];
    final target = tableNames[targetKey];
    if (source == null || target == null) continue;
    if (sourceKey == targetKey) continue;
    if (relationship.sourceSchema != relationship.targetSchema) continue;
    final sourceColumns = _columnConstants(
      relationship.sourceColumns,
      source.displayName,
      tableMembers[sourceKey]!.columnMembers,
      keyDescription: 'the foreign key "${relationship.foreignKeyName}"',
    );
    final targetColumns = _columnConstants(
      relationship.targetColumns,
      target.displayName,
      tableMembers[targetKey]!.columnMembers,
      keyDescription: 'the foreign key "${relationship.foreignKeyName}"',
    );
    final columns = relationship.sourceColumns.join('_');
    // `By` names the key this table holds, `Via` the key the other table
    // holds.
    final byColumns = 'By${pascalCase(columns)}';
    final viaColumns = 'Via${pascalCase(columns)}';
    // Several keys between the same two tables make the plain table name
    // ambiguous for PostgREST, so the embed carries the hint.
    final ambiguous = database.relationships.any(
      (other) =>
          other != relationship &&
          (other.sourceSchema, other.sourceTable) == sourceKey &&
          (other.targetSchema, other.targetTable) == targetKey,
    );

    if (sourceKey == (table.schema, table.name)) {
      final targetName = memberIdentifier(relationship.targetTable);
      members.add(
        _RelationMember(
          baseName: ambiguous ? '$targetName$byColumns' : targetName,
          disambiguatedName: '$targetName$byColumns',
          type: 'PostgrestToOneRelation<${source.rowType}, ${target.rowType}>',
          embedName: ambiguous
              ? '${relationship.targetTable}!${relationship.foreignKeyName}'
              : relationship.targetTable,
          ambiguous: ambiguous,
          columns: sourceColumns,
          referencedTable: relationship.targetTable,
          referencedColumns: [
            for (final column in targetColumns)
              '${target.namespaceType}.$column',
          ],
          docLine:
              'The `${target.displayName}` row referenced by '
              '`$columns`.',
        ),
      );
    }
    if (targetKey == (table.schema, table.name)) {
      final sourceName = memberIdentifier(relationship.sourceTable);
      final kind = relationship.isOneToOne
          ? 'PostgrestToOneRelation'
          : 'PostgrestToManyRelation';
      members.add(
        _RelationMember(
          baseName: ambiguous ? '$sourceName$viaColumns' : sourceName,
          disambiguatedName: '$sourceName$viaColumns',
          type: '$kind<${target.rowType}, ${source.rowType}>',
          embedName: ambiguous
              ? '${relationship.sourceTable}!${relationship.foreignKeyName}'
              : relationship.sourceTable,
          ambiguous: ambiguous,
          columns: targetColumns,
          referencedTable: relationship.sourceTable,
          referencedColumns: [
            for (final column in sourceColumns)
              '${source.namespaceType}.$column',
          ],
          docLine:
              'The `${source.displayName}` '
              '${relationship.isOneToOne ? 'row' : 'rows'} referencing this '
              'row through `$columns`.',
        ),
      );
    }
  }
  final overriddenEmbeds = {
    for (final relationship in table.computedRelationships) relationship.name,
  };
  members.removeWhere(
    (member) =>
        !member.ambiguous && overriddenEmbeds.contains(member.embedName),
  );
  final source = tableNames[(table.schema, table.name)]!;
  for (final relationship in table.computedRelationships) {
    final target =
        tableNames[(relationship.targetSchema, relationship.targetTable)];
    if (target == null) continue;
    members.add(_RelationMember.computed(relationship, source, target));
  }
  return members;
}

/// The column constants of [columns] in the namespace of [table].
///
/// A key over a column the document does not list for its table is a
/// malformed document rather than something to generate around: dropping the
/// column would silently change which rows the key identifies.
List<String> _columnConstants(
  List<String> columns,
  String table,
  Map<String, String> columnNames, {
  required String keyDescription,
}) => [
  for (final column in columns)
    columnNames[column] ??
        (throw FormatException(
          'Not a GeneratorMetadata document: $keyDescription names the '
          'column "$column", which the document does not list for the '
          'table "$table".',
        )),
];

void _writeTable(
  StringBuffer buffer,
  TableDescription table,
  _TableNames names,
  _TableMembers members,
  List<_RelationMember> relations,
  Set<String> typeNames,
  Map<(String, String), String> enumTypeNames,
  _DecoderRegistry decoders,
) {
  final _TableNames(:insertType, :updateType) = names;

  final memberNames = members.rowMembers;
  final bindings = {
    for (final column in table.columns)
      column.name: _bindingFor(_columnShape(column), enumTypeNames),
  };
  final computedFieldBindings = {
    for (final field in table.computedFields)
      field.name: _bindingFor(_computedFieldShape(field), enumTypeNames),
  };
  final relationNames = _relationNames(typeNames, members, relations);
  final relationKeys = _embedKeys(relations, relationNames);

  _writeRow(buffer, table, names, memberNames, bindings);
  if (insertType != null) {
    _writeValues(
      buffer,
      table,
      insertType,
      memberNames,
      bindings,
      requireRequiredColumns: true,
      docLine:
          'Values for inserting a row into `${names.displayName}`. Columns '
          'that are nullable, identity, or covered by a database default are '
          'optional; '
          'passing `null` omits the column so the database default applies. '
          'Columns the database always generates itself are left out '
          'entirely. Use the `set…ToNull` methods to insert SQL NULL '
          'explicitly.',
    );
  }
  if (updateType != null) {
    _writeValues(
      buffer,
      table,
      updateType,
      memberNames,
      bindings,
      requireRequiredColumns: false,
      docLine:
          'Values for updating rows of `${names.displayName}`. All columns '
          'are optional; passing `null` omits the column, leaving it '
          'unchanged. '
          'Use the `set…ToNull` methods to write SQL NULL explicitly.',
    );
  }
  _writeNamespace(
    buffer,
    table,
    names,
    members,
    bindings,
    computedFieldBindings,
    relations,
    relationNames,
    relationKeys,
    decoders,
  );
}

/// The Dart names of [relations] in the namespace class, next to the column
/// constants and the types the table definition names.
List<String> _relationNames(
  Set<String> typeNames,
  _TableMembers members,
  List<_RelationMember> relations,
) {
  final used = {
    'table',
    ...typeNames,
    ...members.columnMembers.values,
    ...members.computedFieldMembers.values,
  };
  final baseNameCounts = <String, int>{};
  for (final relation in relations) {
    baseNameCounts.update(
      relation.baseName,
      (count) => count + 1,
      ifAbsent: () => 1,
    );
  }
  return [
    for (final relation in relations)
      _claimName(
        used,
        used.contains(relation.baseName) ||
                baseNameCounts[relation.baseName]! > 1
            ? relation.disambiguatedName
            : relation.baseName,
      ),
  ];
}

/// The keys the embedded rows of [relations] come back under: the table name
/// for a plain embed, the function name for a computed relationship and, for
/// a hinted one, an alias made of the member name in snake case, kept apart
/// from every other key of the table.
List<String> _embedKeys(
  List<_RelationMember> relations,
  List<String> relationNames,
) {
  final used = {
    for (final relation in relations)
      if (!relation.ambiguous) relation.key,
  };
  return [
    for (final (index, relation) in relations.indexed)
      if (relation.ambiguous)
        _claimAlias(used, snakeCase(relationNames[index]))
      else
        relation.key,
  ];
}

/// Adds [candidate] to [used], numbered from `_2` up until no earlier alias
/// matches, and returns the alias added.
String _claimAlias(Set<String> used, String candidate) {
  var alias = candidate;
  for (var number = 2; !used.add(alias); number++) {
    alias = '${candidate}_$number';
  }
  return alias;
}

void _writeRow(
  StringBuffer buffer,
  TableDescription table,
  _TableNames names,
  Map<String, String> memberNames,
  Map<String, _Binding> bindings,
) {
  final rowType = names.rowType;
  _writeDocComment(
    buffer,
    'A row of the `${names.displayName}` table, as `select()` reads it with '
    'every column.',
  );
  _writeDocComment(buffer, table.comment);
  buffer
    ..writeln('extension type const $rowType(Map<String, dynamic> _json)')
    ..writeln('    implements Object {');
  for (final column in table.columns) {
    final binding = bindings[column.name]!;
    _writeDocComment(buffer, column.comment, indent: '  ');
    buffer.writeln(
      '  ${_getterType(column, binding)} get ${memberNames[column.name]} => '
      '${_readExpression(column, binding)};',
    );
  }
  buffer
    ..writeln()
    ..writeln('  /// The row as decoded from the response.')
    ..writeln('  Map<String, dynamic> toJson() => _json;')
    ..writeln('}')
    ..writeln();
}

void _writeValues(
  StringBuffer buffer,
  TableDescription table,
  String typeName,
  Map<String, String> memberNames,
  Map<String, _Binding> bindings, {
  required bool requireRequiredColumns,
  required String docLine,
}) {
  bool isRequired(ColumnDescription column) =>
      requireRequiredColumns && column.isRequired;
  final writableColumns = [
    for (final column in table.columns)
      if (!column.isReadOnly) column,
  ];

  _writeDocComment(buffer, docLine);
  buffer
    ..writeln('extension type const $typeName._(Map<String, dynamic> _json)')
    ..writeln('    implements Object {');
  if (writableColumns.isEmpty) {
    // A named parameter list cannot be empty, so a table whose columns are
    // all read-only gets a parameterless constructor.
    buffer.writeln('  $typeName() : this._({});');
  } else {
    buffer.writeln('  $typeName({');
    for (final column in writableColumns) {
      final binding = bindings[column.name]!;
      final name = memberNames[column.name]!;
      if (isRequired(column)) {
        buffer.writeln('    required ${binding.dartType} $name,');
      } else {
        buffer.writeln('    ${binding.dartType}? $name,');
      }
    }
    buffer.writeln('  }) : this._({');
    for (final column in writableColumns) {
      final binding = bindings[column.name]!;
      final name = memberNames[column.name]!;
      final key = _stringLiteral(column.name);
      if (isRequired(column)) {
        buffer.writeln(
          '         $key: ${_writeExpression(name, binding, nullable: false)},',
        );
      } else {
        buffer.writeln(
          '         $key: ?${_writeExpression(name, binding, nullable: true)},',
        );
      }
    }
    buffer.writeln('       });');
  }
  for (final column in writableColumns) {
    if (!column.isNullable) continue;
    final name = memberNames[column.name]!;
    final methodName = 'set${name[0].toUpperCase()}${name.substring(1)}ToNull';
    buffer.writeln();
    _writeDocComment(
      buffer,
      'Returns a copy with `${column.name}` set to SQL NULL, overriding any '
      'database default.',
      indent: '  ',
    );
    buffer.writeln(
      '  $typeName $methodName() => '
      '$typeName._({..._json, ${_stringLiteral(column.name)}: null});',
    );
  }
  buffer
    ..writeln('}')
    ..writeln();
}

void _writeNamespace(
  StringBuffer buffer,
  TableDescription table,
  _TableNames names,
  _TableMembers members,
  Map<String, _Binding> bindings,
  Map<String, _Binding> computedFieldBindings,
  List<_RelationMember> relations,
  List<String> relationNames,
  List<String> relationKeys,
  _DecoderRegistry decoders,
) {
  final _TableNames(:rowType, :insertType, :updateType, :namespaceType) = names;
  final _TableMembers(:columnMembers, :computedFieldMembers) = members;

  final primaryKey = _columnConstants(
    table.primaryKey,
    names.displayName,
    columnMembers,
    keyDescription: 'the primary key',
  );
  _writeDocComment(buffer, 'Typed access to the `${names.displayName}` table.');
  buffer
    ..writeln('class $namespaceType {')
    ..writeln('  const $namespaceType._();')
    ..writeln()
    ..writeln('  /// Table definition for [PostgrestClient.table].')
    ..writeln(
      '  static const table = PostgrestTable<$rowType, '
      '${insertType ?? 'Never'}, ${updateType ?? 'Never'}>(',
    )
    ..writeln('    ${_stringLiteral(table.name)},')
    ..writeln('    $rowType.new,')
    ..writeln('    schema: ${_stringLiteral(table.schema)},')
    ..writeln('    primaryKey: [${primaryKey.join(', ')}],');
  if (relations.isNotEmpty) {
    buffer.writeln('    relations: [${relationNames.join(', ')}],');
  }
  if (table.computedFields.isNotEmpty) {
    final fields = [
      for (final field in table.computedFields)
        computedFieldMembers[field.name],
    ];
    buffer.writeln('    computedFields: [${fields.join(', ')}],');
  }
  buffer
    ..writeln('  );')
    ..writeln();
  for (final column in table.columns) {
    final binding = bindings[column.name]!;
    final columnType = switch ((binding.kind, column.isNullable)) {
      (ColumnTypeKind.vector, true) =>
        'PostgrestNullableVectorColumn<$rowType>',
      (ColumnTypeKind.vector, false) => 'PostgrestVectorColumn<$rowType>',
      (_, true) => 'PostgrestNullableColumn<$rowType, ${binding.dartType}>',
      (_, false) => 'PostgrestColumn<$rowType, ${binding.dartType}>',
    };
    // A vector column decodes its literal itself.
    final decoder = binding.kind == ColumnTypeKind.vector
        ? null
        : decoders.claim(binding);
    final arguments = decoder == null ? '' : ', fromJson: $decoder';
    buffer.writeln(
      '  static const ${columnMembers[column.name]} = '
      '$columnType(${_stringLiteral(column.name)}$arguments);',
    );
  }
  for (final field in table.computedFields) {
    final binding = computedFieldBindings[field.name]!;
    final decoder = decoders.claim(binding);
    final arguments = decoder == null ? '' : ', fromJson: $decoder';
    buffer.writeln();
    _writeDocComment(
      buffer,
      'The `${field.name}` computed field, selected by name; `select()` '
      'leaves it out.',
      indent: '  ',
    );
    buffer.writeln(
      '  static const ${computedFieldMembers[field.name]} = '
      'PostgrestComputedField<$rowType, ${binding.dartType}>'
      '(${_stringLiteral(field.name)}$arguments);',
    );
  }
  for (final (index, relation) in relations.indexed) {
    buffer.writeln();
    _writeDocComment(buffer, relation.docLine, indent: '  ');
    buffer
      ..writeln(
        '  static const ${relationNames[index]} = ${relation.type}(',
      )
      ..writeln('    ${_stringLiteral(relation.embedName)},');
    if (!relation.isComputed) {
      buffer.writeln('    columns: [${relation.columns.join(', ')}],');
    }
    buffer.writeln(
      '    referencedTable: ${_stringLiteral(relation.referencedTable)},',
    );
    if (!relation.isComputed) {
      buffer.writeln(
        '    referencedColumns: [${relation.referencedColumns.join(', ')}],',
      );
    }
    if (relation.ambiguous) {
      buffer.writeln('    alias: ${_stringLiteral(relationKeys[index])},');
    }
    buffer.writeln('  );');
  }
  buffer
    ..writeln('}')
    ..writeln();
}

/// The private top-level functions the column tokens decode their values
/// with, one per Dart type that differs from its JSON representation, shared
/// by every column of that type.
class _DecoderRegistry {
  /// The decoder name by the type it produces and the body producing it.
  final Map<(String, String), String> _names = {};
  final Set<String> _claimed = {};

  /// The name of the decoder for [binding], or `null` when the decoded JSON
  /// is the value and the column token needs none.
  String? claim(_Binding binding) {
    final body = _decoderBody(binding, 'json');
    if (body == null) return null;
    return _names.putIfAbsent(
      (binding.dartType, body),
      () => _claimName(_claimed, _decoderName(binding)),
    );
  }

  /// Writes the decoders claimed so far, sorted by name.
  void write(StringBuffer buffer) {
    final entries = _names.entries.toList()
      ..sort((a, b) => a.value.compareTo(b.value));
    for (final MapEntry(key: (type, body), value: name) in entries) {
      buffer
        ..writeln('$type $name(Object json) => $body;')
        ..writeln();
    }
  }
}

/// `_dateTimeFromJson` for `DateTime`, `_intListFromJson` for `List<int>`
/// and `_postgrestRangeOfIntFromJson` for `PostgrestRange<int>`.
String _decoderName(_Binding binding) {
  var words = binding.dartType;
  final argument = RegExp(r'<([^<>]+)>');
  while (argument.hasMatch(words)) {
    words = words.replaceAllMapped(
      argument,
      (match) => 'Of${_capitalized(match[1]!)}',
    );
  }
  words = words.replaceAll(RegExp(r'\W'), '');
  final base = words.startsWith('ListOf')
      ? '${words.substring('ListOf'.length)}List'
      : words;
  if (base.isEmpty) return '_fromJson';
  return '_${base[0].toLowerCase()}${base.substring(1)}FromJson';
}

String _capitalized(String word) =>
    '${word[0].toUpperCase()}${word.substring(1)}';

/// The expression converting [json], one decoded present JSON value bound to
/// [binding], into its Dart type, or `null` when the decoded value is used
/// as it is and the column token needs no decoder.
String? _decoderBody(_Binding binding, String json) {
  if (binding.kind == ColumnTypeKind.array) {
    final conversion = _readConversion(binding.element!, 'element');
    final list = '($json as List<dynamic>)';
    return conversion == null
        ? '$list.cast()'
        : '$list.map((element) => $conversion).toList()';
  }
  return _readConversion(binding, json);
}

/// What decides the Dart type of a value: the type kinds and enum of a
/// column or a computed field, with its [name] for error messages.
typedef _TypeShape = ({
  String name,
  ColumnTypeKind typeKind,
  ColumnTypeKind? elementTypeKind,
  ColumnTypeKind? boundTypeKind,
  EnumDescription? enumType,
});

_TypeShape _columnShape(ColumnDescription column) => (
  name: column.name,
  typeKind: column.typeKind,
  elementTypeKind: column.elementTypeKind,
  boundTypeKind: column.boundTypeKind,
  enumType: column.enumType,
);

_TypeShape _computedFieldShape(ComputedFieldDescription field) => (
  name: field.name,
  typeKind: field.typeKind,
  elementTypeKind: field.elementTypeKind,
  boundTypeKind: field.boundTypeKind,
  enumType: field.enumType,
);

_Binding _bindingFor(
  _TypeShape shape,
  Map<(String, String), String> enumTypeNames,
) {
  if (shape.typeKind == ColumnTypeKind.array) {
    final element = _elementBindingFor(shape, enumTypeNames);
    return _Binding(
      'List<${element.dartType}>',
      ColumnTypeKind.array,
      element: element,
    );
  }
  return _scalarBindingFor(shape.typeKind, shape, enumTypeNames);
}

/// The binding of a scalar of [kind], resolving an enum or the range bounds
/// through [shape].
_Binding _scalarBindingFor(
  ColumnTypeKind kind,
  _TypeShape shape,
  Map<(String, String), String> enumTypeNames,
) => switch (kind) {
  ColumnTypeKind.enumType => _Binding(
    _enumTypeName(shape, enumTypeNames),
    ColumnTypeKind.enumType,
  ),
  ColumnTypeKind.integer => const _Binding('int', ColumnTypeKind.integer),
  ColumnTypeKind.floating => const _Binding('double', ColumnTypeKind.floating),
  ColumnTypeKind.numeric => const _Binding('num', ColumnTypeKind.numeric),
  ColumnTypeKind.boolean => const _Binding('bool', ColumnTypeKind.boolean),
  ColumnTypeKind.date => const _Binding('PostgrestDate', ColumnTypeKind.date),
  ColumnTypeKind.time => const _Binding('PostgrestTime', ColumnTypeKind.time),
  ColumnTypeKind.interval => const _Binding(
    'PostgrestInterval',
    ColumnTypeKind.interval,
  ),
  ColumnTypeKind.timestamp => const _Binding(
    'DateTime',
    ColumnTypeKind.timestamp,
  ),
  ColumnTypeKind.timestampWithTimeZone => const _Binding(
    'DateTime',
    ColumnTypeKind.timestampWithTimeZone,
  ),
  ColumnTypeKind.text => const _Binding('String', ColumnTypeKind.text),
  ColumnTypeKind.binary => const _Binding('Uint8List', ColumnTypeKind.binary),
  ColumnTypeKind.vector => const _Binding(
    'List<double>',
    ColumnTypeKind.vector,
  ),
  ColumnTypeKind.range => _Binding(
    'PostgrestRange<${_boundDartType(shape.boundTypeKind)}>',
    ColumnTypeKind.range,
    boundKind: shape.boundTypeKind,
  ),
  ColumnTypeKind.json ||
  ColumnTypeKind.array ||
  ColumnTypeKind.unknown => const _Binding('Object', ColumnTypeKind.json),
};

/// The binding of the elements of the array [shape], which convert like a
/// scalar of the same kind.
///
/// pgvector elements stay in their wire representation: the filter renderer
/// could not tell a `List<double>` element from a nested array. Nested arrays
/// and JSON elements are `Object`.
_Binding _elementBindingFor(
  _TypeShape shape,
  Map<(String, String), String> enumTypeNames,
) => switch (shape.elementTypeKind) {
  ColumnTypeKind.vector => const _Binding('String', ColumnTypeKind.text),
  null => const _Binding('Object', ColumnTypeKind.json),
  final kind => _scalarBindingFor(kind, shape, enumTypeNames),
};

/// The generated Dart enum of the enum column or computed field [shape],
/// resolved by the schema and name of its Postgres enum rather than by a
/// qualified string, which could not tell `tenant.v1`.`status` from
/// `tenant`.`v1.status`.
String _enumTypeName(
  _TypeShape shape,
  Map<(String, String), String> enumTypeNames,
) {
  final enumType = shape.enumType;
  if (enumType == null) {
    throw ArgumentError.value(
      shape.name,
      'name',
      'An enum column has to name its enum type.',
    );
  }
  return enumTypeNames[(enumType.schema, enumType.name)] ??
      (throw ArgumentError.value(
        shape.name,
        'name',
        'The enum ${enumType.qualifiedName} is not among the described enums.',
      ));
}

String _boundDartType(ColumnTypeKind? boundTypeKind) => switch (boundTypeKind) {
  ColumnTypeKind.integer => 'int',
  ColumnTypeKind.numeric => 'num',
  ColumnTypeKind.date => 'PostgrestDate',
  ColumnTypeKind.timestamp ||
  ColumnTypeKind.timestampWithTimeZone => 'DateTime',
  ColumnTypeKind.time ||
  ColumnTypeKind.interval ||
  ColumnTypeKind.floating ||
  ColumnTypeKind.boolean ||
  ColumnTypeKind.text ||
  ColumnTypeKind.binary ||
  ColumnTypeKind.vector ||
  ColumnTypeKind.json ||
  ColumnTypeKind.enumType ||
  ColumnTypeKind.array ||
  ColumnTypeKind.range ||
  ColumnTypeKind.unknown ||
  null => 'String',
};

/// The function that reads one bound of a range literal.
String _boundParser(ColumnTypeKind? boundTypeKind) => switch (boundTypeKind) {
  ColumnTypeKind.integer ||
  ColumnTypeKind.numeric ||
  ColumnTypeKind.date ||
  ColumnTypeKind.timestamp ||
  ColumnTypeKind.timestampWithTimeZone =>
    '${_boundDartType(boundTypeKind)}.parse',
  ColumnTypeKind.time ||
  ColumnTypeKind.interval ||
  ColumnTypeKind.floating ||
  ColumnTypeKind.boolean ||
  ColumnTypeKind.text ||
  ColumnTypeKind.binary ||
  ColumnTypeKind.vector ||
  ColumnTypeKind.json ||
  ColumnTypeKind.enumType ||
  ColumnTypeKind.array ||
  ColumnTypeKind.range ||
  ColumnTypeKind.unknown ||
  null => '(bound) => bound',
};

String _getterType(ColumnDescription column, _Binding binding) {
  if (binding.kind == ColumnTypeKind.json) return 'Object?';
  return column.isNullable ? '${binding.dartType}?' : binding.dartType;
}

String _readExpression(ColumnDescription column, _Binding binding) {
  final access = "_json[${_stringLiteral(column.name)}]";
  final suffix = column.isNullable ? '?' : '';
  if (binding.kind == ColumnTypeKind.json) return '$access as Object?';
  if (binding.kind == ColumnTypeKind.floating) {
    return '($access as num$suffix)$suffix.toDouble()';
  }
  if (binding.kind == ColumnTypeKind.array) {
    // PostgREST encodes integral elements of floating point arrays as JSON
    // integers, so converted elements go through the same conversion as the
    // scalars instead of a lazy cast that would throw on access.
    final conversion = _readConversion(binding.element!, 'element');
    final list = '($access as List<dynamic>$suffix)$suffix';
    return conversion == null
        ? '$list.cast()'
        : '$list.map((element) => $conversion).toList()';
  }
  final conversion = _readConversion(
    binding,
    column.isNullable ? 'value' : access,
  );
  if (conversion == null) return '$access as ${binding.dartType}$suffix';
  if (!column.isNullable) return conversion;
  return 'switch ($access) { null => null, final Object value => '
      '$conversion }';
}

/// The expression converting [value], one decoded JSON value bound to
/// [binding], into its Dart type, or `null` when the decoded value is used
/// as it is.
String? _readConversion(_Binding binding, String value) =>
    switch (binding.kind) {
      ColumnTypeKind.floating => '($value as num).toDouble()',
      ColumnTypeKind.timestamp ||
      ColumnTypeKind.timestampWithTimeZone ||
      ColumnTypeKind.date ||
      ColumnTypeKind.time ||
      ColumnTypeKind.interval => '${binding.dartType}.parse($value as String)',
      ColumnTypeKind.enumType =>
        '${binding.dartType}.fromWire($value as String)',
      ColumnTypeKind.binary => 'postgrestBytea.decode($value as String)',
      ColumnTypeKind.vector => 'postgrestVector.decode($value as String)',
      ColumnTypeKind.range =>
        'PostgrestRange.parse($value as String, '
            '${_boundParser(binding.boundKind)})',
      ColumnTypeKind.integer ||
      ColumnTypeKind.numeric ||
      ColumnTypeKind.boolean ||
      ColumnTypeKind.text ||
      ColumnTypeKind.array ||
      ColumnTypeKind.json ||
      ColumnTypeKind.unknown => null,
    };

String _writeExpression(
  String parameterName,
  _Binding binding, {
  required bool nullable,
}) {
  if (!nullable) {
    return _writeConversion(binding, parameterName)?.expression ??
        parameterName;
  }
  final rendering = _writeConversion(binding, 'value');
  if (rendering == null) return parameterName;
  final expression = rendering.expression;
  if (rendering.chained) {
    return '$parameterName?${expression.substring('value'.length)}';
  }
  return 'switch ($parameterName) { null => null, final value => $expression }';
}

/// A rendering of a Dart value for the wire, see [_writeConversion]: the
/// [expression], and whether it is a member chain on the value, which a
/// nullable value reaches through `?.` instead of a null switch.
typedef _Rendering = ({String expression, bool chained});

/// How a Dart [value] bound to [binding] is rendered into what the column
/// takes on the wire, or `null` when the value is sent as it is.
_Rendering? _writeConversion(_Binding binding, String value) {
  _Rendering chain(String members) => (
    expression: '$value$members',
    chained: true,
  );
  return switch (binding.kind) {
    ColumnTypeKind.date ||
    ColumnTypeKind.time ||
    ColumnTypeKind.interval => chain('.literal'),
    ColumnTypeKind.timestamp => chain('.toIso8601String()'),
    ColumnTypeKind.timestampWithTimeZone => chain(
      '.toUtc().toIso8601String()',
    ),
    ColumnTypeKind.enumType => chain('.wireName'),
    ColumnTypeKind.binary => (
      expression: 'postgrestBytea.encode($value)',
      chained: false,
    ),
    ColumnTypeKind.vector => (
      expression: 'postgrestVector.encode($value)',
      chained: false,
    ),
    ColumnTypeKind.range => switch (binding.boundKind) {
      ColumnTypeKind.timestamp => chain(
        '.render((bound) => bound.toIso8601String())',
      ),
      ColumnTypeKind.timestampWithTimeZone => chain(
        '.render((bound) => bound.toUtc().toIso8601String())',
      ),
      ColumnTypeKind.date ||
      ColumnTypeKind.time ||
      ColumnTypeKind.interval ||
      ColumnTypeKind.integer ||
      ColumnTypeKind.numeric ||
      ColumnTypeKind.floating ||
      ColumnTypeKind.boolean ||
      ColumnTypeKind.text ||
      ColumnTypeKind.binary ||
      ColumnTypeKind.vector ||
      ColumnTypeKind.json ||
      ColumnTypeKind.enumType ||
      ColumnTypeKind.array ||
      ColumnTypeKind.range ||
      ColumnTypeKind.unknown ||
      null => chain('.literal'),
    },
    ColumnTypeKind.array => switch (_writeConversion(
      binding.element!,
      'element',
    )?.expression) {
      null => null,
      final expression => chain('.map((element) => $expression).toList()'),
    },
    ColumnTypeKind.integer ||
    ColumnTypeKind.floating ||
    ColumnTypeKind.numeric ||
    ColumnTypeKind.boolean ||
    ColumnTypeKind.text ||
    ColumnTypeKind.json ||
    ColumnTypeKind.unknown => null,
  };
}

/// Maps raw database names to unique Dart member identifiers.
///
/// [reserved] seeds identifiers that must not be produced. When [existing] is
/// given, names are kept identical to it where possible so that, for example,
/// column tokens and row getters share their spelling.
Map<String, String> _uniqueMemberNames(
  List<String> names, {
  Set<String> reserved = const {},
  Map<String, String>? existing,
}) {
  final used = {...reserved};
  return {
    for (final name in names)
      name: _claimName(used, existing?[name] ?? memberIdentifier(name)),
  };
}

/// Adds [candidate] to [used], suffixed with `\$` until no earlier name
/// matches, and returns the name added.
String _claimName(Set<String> used, String candidate) {
  var name = candidate;
  while (!used.add(name)) {
    name = '$name\$';
  }
  return name;
}

void _writeDocComment(
  StringBuffer buffer,
  String? comment, {
  String indent = '',
}) {
  if (comment == null) return;
  final width = 80 - indent.length - '/// '.length;
  for (final line in comment.trim().split(_lineTerminators)) {
    for (final wrapped in _wrap(line.trim(), width)) {
      buffer.writeln('$indent/// $wrapped');
    }
  }
}

/// Every Dart source line terminator: a comment line broken on LF alone
/// would let a CR or U+2028/U+2029 end the generated `///` comment early and
/// turn the remainder into source code.
final _lineTerminators = RegExp('\\r\\n?|[\\n\\u2028\\u2029]');

/// Greedily wraps [text] into lines of at most [width] characters, keeping
/// words longer than [width] on their own line.
Iterable<String> _wrap(String text, int width) sync* {
  final words = text.split(' ').where((word) => word.isNotEmpty);
  final line = StringBuffer();
  for (final word in words) {
    if (line.isNotEmpty && line.length + 1 + word.length > width) {
      yield line.toString();
      line.clear();
    }
    if (line.isNotEmpty) line.write(' ');
    line.write(word);
  }
  if (line.isNotEmpty) yield line.toString();
}

String _stringLiteral(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r')
      .replaceAll('\t', r'\t')
      .replaceAll('\u2028', r'\u{2028}')
      .replaceAll('\u2029', r'\u{2029}');
  return "'$escaped'";
}
