import 'package:dart_style/dart_style.dart';

import 'identifiers.dart';
import 'schema_description.dart';

class _Binding {
  const _Binding(this.dartType, this.kind);

  /// The non-nullable Dart type of the column.
  final String dartType;
  final ColumnTypeKind kind;
}

/// Generates a Dart source file with typed table definitions, row extension
/// types, insert and update value types, column tokens and Postgres enums for
/// [schema].
///
/// The generated code depends only on the library at [importUri], which must
/// export the typed table access API of `package:postgrest` (`PostgrestTable`
/// and `TableColumn`).
String generateDartCode(
  SchemaDescription schema, {
  String importUri = 'package:postgrest/postgrest.dart',
}) {
  final buffer = StringBuffer()
    ..writeln('// Generated by supabase_typegen. Do not edit by hand.')
    ..writeln('//')
    ..writeln('// Source schema: ${schema.schemaName}')
    ..writeln()
    ..writeln("import '$importUri';")
    ..writeln();

  final typeNames = _TypeNameRegistry();
  final enumTypeNames = <String, String>{};

  for (final enumDescription in schema.enums) {
    final typeName = typeNames.claim(pascalCase(enumDescription.name));
    enumTypeNames[enumDescription.qualifiedName] = typeName;
    _writeEnum(buffer, enumDescription, typeName);
  }

  for (final table in schema.tables) {
    if (table.columns.isEmpty) continue;
    _writeTable(buffer, table, typeNames, enumTypeNames);
  }

  return DartFormatter(
    languageVersion: DartFormatter.latestLanguageVersion,
  ).format(buffer.toString());
}

/// Hands out unique top level type names, suffixing `$` on collisions.
class _TypeNameRegistry {
  final _used = <String>{};

  String claim(String name) {
    var candidate = name;
    while (!_used.add(candidate)) {
      candidate = '$candidate\$';
    }
    return candidate;
  }
}

void _writeEnum(
  StringBuffer buffer,
  EnumDescription enumDescription,
  String typeName,
) {
  final valueNames = _uniqueMemberNames(enumDescription.values);

  buffer
    ..writeln('/// Postgres enum `${enumDescription.qualifiedName}`.')
    ..writeln('enum $typeName {');
  for (final value in enumDescription.values) {
    buffer.writeln("  ${valueNames[value]}(${_stringLiteral(value)}),");
  }
  buffer
    ..writeln(';')
    ..writeln()
    ..writeln('  const $typeName(this.wireName);')
    ..writeln()
    ..writeln('  /// The value as stored in the database.')
    ..writeln('  final String wireName;')
    ..writeln()
    ..writeln('  /// Parses the database representation of the enum.')
    ..writeln('  static $typeName fromWire(String wireName) =>')
    ..writeln('      values.firstWhere((value) => value.wireName == wireName);')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  String toString() => wireName;')
    ..writeln('}')
    ..writeln();
}

void _writeTable(
  StringBuffer buffer,
  TableDescription table,
  _TypeNameRegistry typeNames,
  Map<String, String> enumTypeNames,
) {
  final baseName = pascalCase(table.name);
  final rowType = typeNames.claim('${baseName}Row');
  final insertType = typeNames.claim('${baseName}Insert');
  final updateType = typeNames.claim('${baseName}Update');
  final namespaceType = typeNames.claim(baseName);

  final memberNames = _uniqueMemberNames([
    for (final column in table.columns) column.name,
  ]);
  final bindings = {
    for (final column in table.columns)
      column.name: _bindingFor(column, enumTypeNames),
  };

  _writeRow(buffer, table, rowType, memberNames, bindings);
  _writeValues(
    buffer,
    table,
    insertType,
    memberNames,
    bindings,
    requireRequiredColumns: true,
    docLine:
        'Values for inserting a row into `${table.name}`. Columns that are '
        'nullable, part of a generated primary key, or covered by a database '
        'default are optional; passing `null` omits the column so the '
        'database default applies.',
  );
  _writeValues(
    buffer,
    table,
    updateType,
    memberNames,
    bindings,
    requireRequiredColumns: false,
    docLine:
        'Values for updating rows of `${table.name}`. All columns are '
        'optional; passing `null` leaves the column unchanged.',
  );
  _writeNamespace(buffer, table, namespaceType, rowType, memberNames, bindings);
}

void _writeRow(
  StringBuffer buffer,
  TableDescription table,
  String rowType,
  Map<String, String> memberNames,
  Map<String, _Binding> bindings,
) {
  buffer.writeln('/// A row of the `${table.name}` table.');
  _writeDocComment(buffer, table.comment);
  buffer
    ..writeln('extension type const $rowType(Map<String, dynamic> _json)')
    ..writeln('    implements Map<String, dynamic> {');
  for (final column in table.columns) {
    final binding = bindings[column.name]!;
    _writeDocComment(buffer, column.comment, indent: '  ');
    buffer.writeln(
      '  ${_getterType(column, binding)} get ${memberNames[column.name]} => '
      '${_readExpression(column, binding)};',
    );
  }
  buffer
    ..writeln('}')
    ..writeln();
}

void _writeValues(
  StringBuffer buffer,
  TableDescription table,
  String typeName,
  Map<String, String> memberNames,
  Map<String, _Binding> bindings, {
  required bool requireRequiredColumns,
  required String docLine,
}) {
  bool isRequired(ColumnDescription column) =>
      requireRequiredColumns && column.isRequired;

  buffer
    ..writeln('/// $docLine')
    ..writeln('extension type const $typeName._(Map<String, dynamic> _json)')
    ..writeln('    implements Map<String, dynamic> {')
    ..writeln('  $typeName({');
  for (final column in table.columns) {
    final binding = bindings[column.name]!;
    final name = memberNames[column.name]!;
    if (isRequired(column)) {
      buffer.writeln('    required ${binding.dartType} $name,');
    } else {
      buffer.writeln('    ${binding.dartType}? $name,');
    }
  }
  buffer.writeln('  }) : this._({');
  for (final column in table.columns) {
    final binding = bindings[column.name]!;
    final name = memberNames[column.name]!;
    final key = _stringLiteral(column.name);
    if (isRequired(column)) {
      buffer.writeln(
        '         $key: ${_writeExpression(name, binding, nullable: false)},',
      );
    } else {
      buffer.writeln(
        '         $key: ?${_writeExpression(name, binding, nullable: true)},',
      );
    }
  }
  buffer
    ..writeln('       });')
    ..writeln('}')
    ..writeln();
}

void _writeNamespace(
  StringBuffer buffer,
  TableDescription table,
  String namespaceType,
  String rowType,
  Map<String, String> memberNames,
  Map<String, _Binding> bindings,
) {
  final columnNames = _uniqueMemberNames(
    [for (final column in table.columns) column.name],
    reserved: {'table'},
    existing: memberNames,
  );

  buffer
    ..writeln('/// Typed access to the `${table.name}` table.')
    ..writeln('class $namespaceType {')
    ..writeln('  const $namespaceType._();')
    ..writeln()
    ..writeln('  /// Table definition for [PostgrestClient.table].')
    ..writeln(
      '  static const table = PostgrestTable'
      '(${_stringLiteral(table.name)}, $rowType.new);',
    )
    ..writeln();
  for (final column in table.columns) {
    final binding = bindings[column.name]!;
    buffer.writeln(
      '  static const ${columnNames[column.name]} = '
      'TableColumn<${binding.dartType}>(${_stringLiteral(column.name)});',
    );
  }
  buffer
    ..writeln('}')
    ..writeln();
}

_Binding _bindingFor(
  ColumnDescription column,
  Map<String, String> enumTypeNames,
) => switch (column.typeKind) {
  ColumnTypeKind.enumType => _Binding(
    enumTypeNames[column.postgresFormat]!,
    ColumnTypeKind.enumType,
  ),
  ColumnTypeKind.array => _Binding(
    'List<${_elementDartType(column.elementTypeKind)}>',
    ColumnTypeKind.array,
  ),
  ColumnTypeKind.integer => const _Binding('int', ColumnTypeKind.integer),
  ColumnTypeKind.floating => const _Binding('double', ColumnTypeKind.floating),
  ColumnTypeKind.numeric => const _Binding('num', ColumnTypeKind.numeric),
  ColumnTypeKind.boolean => const _Binding('bool', ColumnTypeKind.boolean),
  ColumnTypeKind.dateTime => const _Binding(
    'DateTime',
    ColumnTypeKind.dateTime,
  ),
  ColumnTypeKind.text => const _Binding('String', ColumnTypeKind.text),
  ColumnTypeKind.json ||
  ColumnTypeKind.unknown => const _Binding('Object', ColumnTypeKind.json),
};

String _elementDartType(ColumnTypeKind? elementTypeKind) =>
    switch (elementTypeKind) {
      ColumnTypeKind.integer => 'int',
      ColumnTypeKind.floating => 'double',
      ColumnTypeKind.numeric => 'num',
      ColumnTypeKind.boolean => 'bool',
      ColumnTypeKind.text => 'String',
      ColumnTypeKind.dateTime ||
      ColumnTypeKind.json ||
      ColumnTypeKind.enumType ||
      ColumnTypeKind.array ||
      ColumnTypeKind.unknown ||
      null => 'Object',
    };

String _getterType(ColumnDescription column, _Binding binding) {
  if (binding.kind == ColumnTypeKind.json) return 'Object?';
  return column.isNullable ? '${binding.dartType}?' : binding.dartType;
}

String _readExpression(ColumnDescription column, _Binding binding) {
  final access = "_json[${_stringLiteral(column.name)}]";
  final nullable = column.isNullable;
  return switch (binding.kind) {
    ColumnTypeKind.integer ||
    ColumnTypeKind.numeric ||
    ColumnTypeKind.boolean ||
    ColumnTypeKind.text =>
      '$access as ${binding.dartType}${nullable ? '?' : ''}',
    ColumnTypeKind.floating =>
      nullable
          ? '($access as num?)?.toDouble()'
          : '($access as num).toDouble()',
    ColumnTypeKind.array =>
      nullable
          ? '($access as List<dynamic>?)?.cast()'
          : '($access as List<dynamic>).cast()',
    ColumnTypeKind.dateTime =>
      nullable
          ? _nullableSwitch(access, 'DateTime.parse(value as String)')
          : 'DateTime.parse($access as String)',
    ColumnTypeKind.enumType =>
      nullable
          ? _nullableSwitch(
              access,
              '${binding.dartType}.fromWire(value as String)',
            )
          : '${binding.dartType}.fromWire($access as String)',
    ColumnTypeKind.json || ColumnTypeKind.unknown => '$access as Object?',
  };
}

String _nullableSwitch(String access, String conversion) =>
    'switch ($access) { null => null, final Object value => $conversion }';

String _writeExpression(
  String parameterName,
  _Binding binding, {
  required bool nullable,
}) {
  final access = nullable ? '$parameterName?' : parameterName;
  return switch (binding.kind) {
    ColumnTypeKind.dateTime => '$access.toIso8601String()',
    ColumnTypeKind.enumType => '$access.wireName',
    ColumnTypeKind.integer ||
    ColumnTypeKind.floating ||
    ColumnTypeKind.numeric ||
    ColumnTypeKind.boolean ||
    ColumnTypeKind.text ||
    ColumnTypeKind.array ||
    ColumnTypeKind.json ||
    ColumnTypeKind.unknown => parameterName,
  };
}

/// Maps raw database names to unique Dart member identifiers.
///
/// [reserved] seeds identifiers that must not be produced. When [existing] is
/// given, names are kept identical to it where possible so that, for example,
/// column tokens and row getters share their spelling.
Map<String, String> _uniqueMemberNames(
  List<String> names, {
  Set<String> reserved = const {},
  Map<String, String>? existing,
}) {
  final used = {...reserved};
  final result = <String, String>{};
  for (final name in names) {
    var candidate = existing?[name] ?? memberIdentifier(name);
    while (!used.add(candidate)) {
      candidate = '$candidate\$';
    }
    result[name] = candidate;
  }
  return result;
}

void _writeDocComment(
  StringBuffer buffer,
  String? comment, {
  String indent = '',
}) {
  if (comment == null) return;
  for (final line in comment.trim().split('\n')) {
    buffer.writeln('$indent/// ${line.trim()}');
  }
}

String _stringLiteral(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
  return "'$escaped'";
}
