import 'dart:convert';
import 'dart:io';

// The package version is internal; the tests read it to check the header.
// ignore: invalid_use_of_internal_member
import 'package:supabase_typegen/src/version.dart';
import 'package:supabase_typegen/supabase_typegen.dart';
import 'package:test/test.dart';

import 'goldens/hostile_fixture.dart';

final _whitespace = RegExp(r'\s+');
final _headerVersion = RegExp(r'supabase_typegen \S+ from');

/// Collapses whitespace so the comparison is stable across formatter
/// versions, and blanks the package version in the header so a release bump
/// does not invalidate the goldens; `tool/regenerate_goldens.dart` refreshes
/// the golden.
String _normalize(String code) => code
    .replaceAll(_whitespace, ' ')
    .replaceFirst(_headerVersion, 'supabase_typegen <version> from')
    .trim();

void main() {
  late DatabaseDescription schema;

  setUpAll(() {
    final document =
        jsonDecode(
              File(
                'test/fixtures/generator_metadata.json',
              ).readAsStringSync(),
            )
            as Map<String, dynamic>;
    schema = parseGeneratorMetadata(document);
  });

  test('matches the golden output', () {
    final golden = File('test/goldens/supabase_schema.dart').readAsStringSync();

    expect(
      _normalize(generateDartCode(schema)),
      _normalize(golden),
      reason:
          'The generator output changed. Regenerate the golden with '
          '`dart run tool/regenerate_goldens.dart` and review the diff.',
    );
  });

  test('matches the hostile golden output', () {
    final golden = File('test/goldens/hostile_schema.dart').readAsStringSync();

    expect(
      _normalize(generateDartCode(hostileSchema)),
      _normalize(golden),
      reason:
          'The generator output changed for the pathological schema. '
          'Regenerate the golden with `dart run tool/regenerate_goldens.dart` '
          'and review the diff; the checked-in golden is what proves the '
          'generated code analyzes cleanly for hostile names.',
    );
  });

  test('split representation clauses carry no trailing comma', () {
    final code = generateDartCode(hostileSchema);

    // The name is long enough that the formatter has to split the clause.
    expect(code, contains('PrivateAchievementItemProgressTblInsert._(\n'));
    // Language versions before 3.13 reject a trailing comma there.
    expect(code, isNot(matches(RegExp(r'_json,\s*\)'))));
  });

  test('range columns parse their literal and render it back', () {
    final code = _normalize(generateDartCode(hostileSchema));
    final compact = code.replaceAll(' ', '');

    expect(
      compact,
      contains(
        "PostgrestColumn<MapRow,PostgrestRange<int>>"
        "('pages'",
      ),
    );
    expect(
      compact,
      contains(
        "PostgrestNullableColumn<MapRow,"
        "PostgrestRange<DateTime>>('during'",
      ),
    );
    expect(
      compact,
      contains(
        "PostgrestColumn<MapRow,PostgrestRange<PostgrestDate>>('season'",
      ),
    );
    expect(
      code,
      contains(
        "PostgrestRange.parse(_json['season'] as String, PostgrestDate.parse)",
      ),
    );
    expect(
      code,
      contains("PostgrestRange.parse(_json['pages'] as String, int.parse)"),
    );
    expect(
      compact,
      contains(
        "PostgrestRange<num>?getprices=>switch(_json['prices']){null=>null,"
        "finalObjectvalue=>PostgrestRange.parse(valueasString,num.parse),};",
      ),
    );
    expect(code, contains("'pages': pages.literal,"));
    expect(code, contains("'season': ?season?.literal,"));
    expect(
      code,
      contains("'shift': shift.render((bound) => bound.toIso8601String()),"),
    );
    expect(
      compact,
      contains(
        "'during':?during?.render((bound)=>bound.toUtc().toIso8601String()),",
      ),
    );
  });

  test('names objects outside public after their schema and emits the '
      'schema of every table', () {
    final code = generateDartCode(schema);

    expect(code, contains('// Source schemas: inventory, public'));
    expect(
      code,
      startsWith(
        '// Generated by supabase_typegen $version from GeneratorMetadata '
        'version 1.\n// Do not edit by hand.\n',
      ),
    );
    expect(code, contains('enum InventoryCondition {'));
    expect(code, contains('enum Mood {'));
    expect(code, contains('extension type const InventoryBooksRow('));
    expect(code, contains('extension type const BooksRow('));
    expect(code, contains('class InventoryStock {'));
    expect(code, contains("/// Typed access to the `inventory.stock` table."));
    expect(code, contains("/// Typed access to the `books` table."));
    final compact = _normalize(code).replaceAll(' ', '');
    expect(
      compact,
      contains(
        "PostgrestTable<InventoryStockRow,InventoryStockInsert,"
        "InventoryStockUpdate>('stock',InventoryStockRow.new,"
        "schema:'inventory'",
      ),
    );
    expect(
      compact,
      contains(
        "PostgrestTable<BooksRow,BooksInsert,BooksUpdate>('books',BooksRow.new,"
        "schema:'public'",
      ),
    );
  });

  test('keys into another schema produce no relation member', () {
    final compact = _normalize(generateDartCode(schema)).replaceAll(' ', '');

    // inventory.stock references inventory.books and public.books; only the
    // key within the schema is embeddable through PostgREST.
    expect(
      compact,
      contains(
        "staticconstbooks=PostgrestToOneRelation<InventoryStockRow,"
        "InventoryBooksRow>('books'",
      ),
    );
    expect(compact, isNot(contains('<InventoryStockRow,BooksRow>')));
    expect(compact, isNot(contains('<BooksRow,InventoryStockRow>')));

    final hostile = _normalize(generateDartCode(hostileSchema));
    expect(hostile, contains('class EvilMultilineSchemaNamePostgrestColumn {'));
    expect(
      hostile,
      isNot(contains('EvilMultilineSchemaNamePostgrestColumnRow>')),
    );
  });

  test('bytea columns read and write through the bytea codec', () {
    final code = _normalize(generateDartCode(hostileSchema));
    final compact = code.replaceAll(' ', '');

    expect(code, contains("import 'dart:typed_data';"));
    expect(
      compact,
      contains(
        "PostgrestNullableColumn<PostgrestTableRow,Uint8List>('uint8_list',"
        "fromJson:_uint8ListFromJson",
      ),
    );
    expect(
      compact,
      contains(
        "Uint8List?getuint8List=>switch(_json['uint8_list']){null=>null,"
        "finalObjectvalue=>postgrestBytea.decode(valueasString),};",
      ),
    );
    expect(
      compact,
      contains(
        "'uint8_list':?switch(uint8List){null=>null,"
        "finalvalue=>postgrestBytea.encode(value),},",
      ),
    );
    // A column named like the codec cannot shadow it in the conversions.
    expect(
      compact,
      contains(
        "Uint8ListgetpostgrestBytea\$=>"
        "postgrestBytea.decode(_json['postgrest_bytea']asString);",
      ),
    );
    expect(
      compact,
      contains("'postgrest_bytea':postgrestBytea.encode(postgrestBytea\$),"),
    );
    expect(
      compact,
      contains(
        "List<Uint8List>?getblobs=>(_json['blobs']asList<dynamic>?)"
        "?.map((element)=>postgrestBytea.decode(elementasString)).toList();",
      ),
    );
    expect(
      compact,
      contains(
        "'blobs':?blobs?.map((element)=>postgrestBytea.encode(element))"
        ".toList(),",
      ),
    );
  });

  test('column tokens decode through one helper per Dart type', () {
    final compact = _normalize(
      generateDartCode(schema),
    ).replaceAll(' ', '');

    expect(
      compact,
      contains(
        "PostgrestColumn<BooksRow,DateTime>('created_at',"
        "fromJson:_dateTimeFromJson",
      ),
    );
    expect(
      compact,
      contains(
        "PostgrestNullableColumn<BooksRow,DateTime>('updated_at',"
        "fromJson:_dateTimeFromJson",
      ),
    );
    expect(
      compact,
      contains(
        "PostgrestNullableColumn<BooksRow,Mood>('mood',fromJson:_moodFromJson",
      ),
    );
    expect(
      compact,
      contains(
        "PostgrestNullableColumn<BooksRow,List<int>>('page_counts',"
        "fromJson:_intListFromJson",
      ),
    );
    expect(
      compact,
      contains(
        "PostgrestNullableColumn<BooksRow,double>('rating',"
        "fromJson:_doubleFromJson",
      ),
    );
    // Types the decoded JSON already is need no decoder.
    expect(compact, contains("PostgrestColumn<BooksRow,int>('id');"));
    expect(compact, contains("PostgrestColumn<BooksRow,String>('title');"));
    expect(
      compact,
      contains("PostgrestNullableColumn<BooksRow,num>('price');"),
    );
    expect(
      compact,
      contains("PostgrestNullableColumn<BooksRow,Object>('metadata');"),
    );
    expect(
      compact,
      contains(
        "DateTime_dateTimeFromJson(Objectjson)=>DateTime.parse(jsonasString);",
      ),
    );
    expect(
      compact,
      contains("Mood_moodFromJson(Objectjson)=>Mood.fromWire(jsonasString);"),
    );
    expect(
      compact,
      contains(
        "List<int>_intListFromJson(Objectjson)=>(jsonasList<dynamic>).cast();",
      ),
    );
    expect(compact.split('_dateTimeFromJson(Objectjson)'), hasLength(2));
  });

  test('array and range decoders are named after their type', () {
    final compact = _normalize(
      generateDartCode(hostileSchema),
    ).replaceAll(' ', '');

    expect(
      compact,
      contains(
        "List<PostgrestRange<int>>_postgrestRangeOfIntListFromJson(Objectjson)"
        "=>(jsonasList<dynamic>).map((element)=>PostgrestRange.parse("
        "elementasString,int.parse)).toList();",
      ),
    );
    expect(
      compact,
      contains(
        "List<double>_doubleListFromJson(Objectjson)=>(jsonasList<dynamic>)"
        ".map((element)=>(elementasnum).toDouble()).toList();",
      ),
    );
    // A `List<String$>` enum array cannot take the `List<String>` helper.
    expect(compact, contains("List<String>_stringListFromJson(Objectjson)"));
    expect(
      compact,
      contains("List<String\$>_stringListFromJson\$(Objectjson)"),
    );
  });

  test('row types carry no relation getters', () {
    final code = _normalize(generateDartCode(schema));

    expect(code, isNot(contains('AuthorsRow? get authors')));
    expect(code, isNot(contains('List<BooksRow> get books')));
    expect(code, contains('static const authors = PostgrestToOneRelation'));
  });

  test('vector columns read and write through the vector codec', () {
    final compact = _normalize(
      generateDartCode(hostileSchema),
    ).replaceAll(' ', '');

    expect(
      compact,
      contains(
        "PostgrestNullableVectorColumn<PostgrestTableRow>('half_embedding'",
      ),
    );
    expect(
      compact,
      contains("PostgrestVectorColumn<PostgrestTableRow>('postgrest_vector'"),
    );
    expect(
      compact,
      contains(
        "List<double>?gethalfEmbedding=>switch(_json['half_embedding']){"
        "null=>null,finalObjectvalue=>postgrestVector.decode(valueasString),};",
      ),
    );
    expect(
      compact,
      contains(
        "'half_embedding':?switch(halfEmbedding){null=>null,"
        "finalvalue=>postgrestVector.encode(value),},",
      ),
    );
    // A column named like the codec cannot shadow it in the conversions.
    expect(
      compact,
      contains(
        "List<double>getpostgrestVector\$=>"
        "postgrestVector.decode(_json['postgrest_vector']asString);",
      ),
    );
    expect(
      compact,
      contains(
        "'postgrest_vector':postgrestVector.encode(postgrestVector\$),",
      ),
    );
    // Array elements stay in their wire representation.
    expect(compact, contains('List<String>?getembeddings=>'));
  });

  test('date, time and interval columns read and write through their value '
      'types', () {
    final code = _normalize(generateDartCode(hostileSchema));
    final compact = code.replaceAll(' ', '');

    expect(
      compact,
      contains(
        "PostgrestColumn<MapRow,PostgrestDate>('since',"
        "fromJson:_postgrestDateFromJson",
      ),
    );
    expect(
      compact,
      contains(
        "PostgrestColumn<MapRow,PostgrestTime>('opens_at',"
        "fromJson:_postgrestTimeFromJson",
      ),
    );
    expect(
      compact,
      contains("PostgrestNullableColumn<MapRow,PostgrestTime>('closes_at'"),
    );
    expect(
      compact,
      contains(
        "PostgrestNullableColumn<MapRow,PostgrestInterval>('ttl',"
        "fromJson:_postgrestIntervalFromJson",
      ),
    );
    expect(
      code,
      contains(
        "PostgrestDate get since => PostgrestDate.parse(_json['since'] "
        "as String);",
      ),
    );
    expect(
      compact,
      contains(
        "PostgrestTime?getclosesAt=>switch(_json['closes_at']){null=>null,"
        "finalObjectvalue=>PostgrestTime.parse(valueasString),};",
      ),
    );
    expect(
      compact,
      contains(
        "PostgrestInterval?getttl=>switch(_json['ttl']){null=>null,"
        "finalObjectvalue=>PostgrestInterval.parse(valueasString),};",
      ),
    );
    expect(code, contains("'since': since.literal,"));
    expect(code, contains("'opens_at': opensAt.literal,"));
    expect(code, contains("'closes_at': ?closesAt?.literal,"));
    expect(code, contains("'ttl': ?ttl?.literal,"));
    expect(code, isNot(contains('_dateString')));
  });

  test('the typed_data import is only emitted for bytea columns', () {
    const textOnlySchema = DatabaseDescription(
      schemaNames: ['public'],
      tables: [
        TableDescription(
          schema: 'public',
          name: 'notes',
          columns: [
            ColumnDescription(
              name: 'body',
              postgresFormat: 'text',
              typeKind: ColumnTypeKind.text,
              isRequired: true,
              hasDefault: false,
              isNullable: false,
            ),
          ],
        ),
      ],
      enums: [],
    );

    expect(
      generateDartCode(textOnlySchema),
      isNot(contains('dart:typed_data')),
    );
  });

  test('emits a relation member for each side of a foreign key', () {
    final compact = _normalize(generateDartCode(schema)).replaceAll(' ', '');

    expect(
      compact,
      contains(
        "staticconstauthors=PostgrestToOneRelation<BooksRow,AuthorsRow>"
        "('authors',columns:[authorId],referencedTable:'authors',"
        "referencedColumns:[Authors.id],);",
      ),
    );
    expect(
      compact,
      contains(
        "staticconstbooks=PostgrestToManyRelation<AuthorsRow,BooksRow>('books',"
        "columns:[id],referencedTable:'books',"
        "referencedColumns:[Books.authorId],);",
      ),
    );
  });

  test('the table definition lists its primary key and relations', () {
    final compact = _normalize(generateDartCode(schema)).replaceAll(' ', '');

    expect(
      compact,
      contains(
        "staticconsttable=PostgrestTable<BooksRow,BooksInsert,BooksUpdate>("
        "'books',BooksRow.new,schema:'public',primaryKey:[id],"
        "relations:[authors],computedFields:[moodOrDefault,titleUpper],);",
      ),
    );
  });

  test(
    'a primary key over a column the document does not list is rejected',
    () {
      const malformed = DatabaseDescription(
        schemaNames: ['public'],
        tables: [
          TableDescription(
            schema: 'public',
            name: 'todos',
            primaryKey: ['id', 'missing'],
            columns: [
              ColumnDescription(
                name: 'id',
                postgresFormat: 'int8',
                typeKind: ColumnTypeKind.integer,
                isRequired: true,
                hasDefault: false,
                isNullable: false,
              ),
            ],
          ),
        ],
        enums: [],
      );

      expect(
        () => generateDartCode(malformed),
        throwsA(
          isA<FormatException>().having(
            (error) => error.message,
            'message',
            allOf(contains('primary key'), contains('"missing"')),
          ),
        ),
      );
    },
  );

  test('a view has an empty primary key and a sanitized key keeps its '
      'column constant', () {
    final compact = _normalize(generateDartCode(schema)).replaceAll(' ', '');
    final hostile = _normalize(
      generateDartCode(hostileSchema),
    ).replaceAll(' ', '');

    expect(
      compact,
      contains(
        "('author_stats',AuthorStatsRow.new,schema:'public',primaryKey:[],",
      ),
    );
    expect(hostile, contains('primaryKey:[quoteNameTail,days]'));
  });

  test('relation members are disambiguated by hint and column', () {
    final compact = _normalize(
      generateDartCode(hostileSchema),
    ).replaceAll(' ', '');

    // Two keys from postgrest_table to map: both carry the constraint hint.
    expect(
      compact,
      contains(
        "staticconstmapByMood=PostgrestToOneRelation<"
        "PostgrestTableRow,MapRow>"
        "('map!postgrest_table_mood_fkey'",
      ),
    );
    expect(
      compact,
      contains(
        "staticconstpostgrestTableViaDays=PostgrestToOneRelation<"
        "MapRow,PostgrestTableRow>"
        "('postgrest_table!postgrest_table_days_fkey'",
      ),
    );
  });

  test('a hinted relation is aliased to its member name', () {
    final compact = _normalize(
      generateDartCode(hostileSchema),
    ).replaceAll(' ', '');

    // Both embeds would come back under `map` otherwise.
    expect(
      compact,
      contains(
        "referencedColumns:[Map\$.list],alias:'map_by_mood',);",
      ),
    );
    expect(
      compact,
      contains(
        "referencedColumns:[PostgrestTable\$.mood],"
        "alias:'postgrest_table_via_mood',);",
      ),
    );
  });

  test('aliases of relations that share a member name stay distinct', () {
    // Two constraints over the same columns claim `mapByMood` and
    // `mapByMood$`, which snake case alone would both turn into `map_by_mood`.
    final duplicated = DatabaseDescription(
      schemaNames: hostileSchema.schemaNames,
      tables: hostileSchema.tables,
      enums: hostileSchema.enums,
      relationships: [
        ...hostileSchema.relationships,
        const RelationshipDescription(
          foreignKeyName: 'postgrest_table_mood_fkey2',
          sourceSchema: 'public',
          sourceTable: 'postgrest_table',
          sourceColumns: ['mood'],
          targetSchema: 'public',
          targetTable: 'map',
          targetColumns: ['list'],
        ),
      ],
    );
    final compact = _normalize(
      generateDartCode(duplicated),
    ).replaceAll(' ', '');

    expect(compact, contains("alias:'map_by_mood',"));
    expect(
      compact,
      contains(
        "staticconstmapByMood\$=PostgrestToOneRelation<"
        "PostgrestTableRow,MapRow>('map!postgrest_table_mood_fkey2',"
        "columns:[mood],referencedTable:'map',"
        "referencedColumns:[Map\$.list],alias:'map_by_mood_2',);",
      ),
    );
  });

  test('a self-referential key produces no relation member', () {
    // PostgREST needs a computed relationship to embed a table into itself,
    // which the fixture declares as `parent` and `children`.
    final compact = _normalize(
      generateDartCode(hostileSchema),
    ).replaceAll(' ', '');

    expect(compact, isNot(contains('<MapRow,MapRow>(')));
    expect(compact, isNot(contains('mapByList')));
    expect(compact, isNot(contains('map_list_fkey')));
  });

  test('respects a custom import', () {
    final code = generateDartCode(
      schema,
      importUri: 'package:supabase_flutter/supabase_flutter.dart',
    );

    expect(
      code,
      contains("import 'package:supabase_flutter/supabase_flutter.dart';"),
    );
  });

  test('marks not null columns without default as required on insert', () {
    final code = generateDartCode(schema);

    expect(code, contains('required String title'));
    expect(code, contains('int? id'));
  });

  test('not null columns with a default read non-nullable', () {
    final code = generateDartCode(schema);

    expect(code, contains("bool get inPrint => _json['in_print'] as bool;"));
    expect(
      code,
      contains(
        "DateTime get createdAt => "
        "DateTime.parse(_json['created_at'] as String);",
      ),
    );
  });

  test('always generated columns are excluded from insert and update', () {
    final code = generateDartCode(schema);

    expect(code, contains('AuthorsInsert({required String name})'));
    expect(code, contains('AuthorsUpdate({String? name})'));
    expect(code, contains("PostgrestColumn<AuthorsRow, int>('id')"));
  });

  test('read-only views and materialized views generate no insert or '
      'update surface', () {
    final code = generateDartCode(schema);

    expect(code, contains('extension type const AuthorStatsRow'));
    expect(code, isNot(contains('AuthorStatsInsert')));
    expect(code, isNot(contains('AuthorStatsUpdate')));

    expect(code, contains('extension type const BookSummariesRow'));
    expect(code, isNot(contains('BookSummariesInsert')));
    expect(code, isNot(contains('BookSummariesUpdate')));
  });

  test('a view with an INSTEAD OF INSERT trigger generates only an insert '
      'surface', () {
    final code = generateDartCode(schema);

    expect(code, contains('extension type const BookSubmissionsRow'));
    expect(code, contains('BookSubmissionsInsert({String? authorName'));
    expect(code, isNot(contains('BookSubmissionsUpdate')));
  });

  test('non-updatable view columns read but are excluded from insert and '
      'update', () {
    final code = generateDartCode(schema);

    expect(code, contains('num? get discountedPrice'));
    expect(
      _normalize(code),
      contains(
        "PostgrestNullableColumn<BookPricesRow, num>( 'discounted_price', )",
      ),
    );
    expect(
      code,
      contains('BookPricesInsert({int? id, num? price, String? title})'),
    );
    expect(
      code,
      contains('BookPricesUpdate({int? id, num? price, String? title})'),
    );
  });

  test('insert-only and update-only relations generate a single value '
      'type', () {
    ColumnDescription titleColumn() => const ColumnDescription(
      name: 'title',
      postgresFormat: 'text',
      typeKind: ColumnTypeKind.text,
      isRequired: false,
      hasDefault: false,
      isNullable: true,
    );
    final code = generateDartCode(
      DatabaseDescription(
        schemaNames: const ['public'],
        tables: [
          TableDescription(
            schema: 'public',
            name: 'book_submissions',
            columns: [titleColumn()],
            isInsertable: true,
            isUpdatable: false,
          ),
          TableDescription(
            schema: 'public',
            name: 'book_corrections',
            columns: [titleColumn()],
            isInsertable: false,
            isUpdatable: true,
          ),
        ],
        enums: [],
      ),
    );

    expect(code, contains('BookSubmissionsInsert({String? title})'));
    expect(code, isNot(contains('BookSubmissionsUpdate')));

    expect(code, contains('BookCorrectionsUpdate({String? title})'));
    expect(code, isNot(contains('BookCorrectionsInsert')));
  });

  test('enum names keep periods in the schema and type name apart', () {
    const nested = EnumDescription(
      schema: 'tenant.v1',
      name: 'status',
      values: ['a'],
    );
    const dotted = EnumDescription(
      schema: 'tenant',
      name: 'v1.status',
      values: ['b'],
    );
    ColumnDescription enumColumn(String name, EnumDescription enumType) =>
        ColumnDescription(
          name: name,
          postgresFormat: enumType.qualifiedName,
          typeKind: ColumnTypeKind.enumType,
          isRequired: true,
          hasDefault: false,
          isNullable: false,
          enumType: enumType,
        );
    final code = generateDartCode(
      DatabaseDescription(
        schemaNames: const ['public', 'tenant.v1'],
        tables: [
          TableDescription(
            schema: 'public',
            name: 'reviews',
            columns: [enumColumn('mood', nested), enumColumn('status', dotted)],
          ),
        ],
        enums: const [nested, dotted],
      ),
    );

    expect(code, contains('/// Postgres enum `tenant.v1.status`.'));
    expect(code, contains('enum TenantV1Status {'));
    expect(code, contains('enum TenantV1Status\$ {'));
    // Each column resolves to the Dart enum of its own Postgres enum even
    // though both share the qualified string.
    expect(code, contains('TenantV1Status get mood'));
    expect(code, contains('TenantV1Status\$ get status'));
  });

  test('an enum column without its enum type is rejected', () {
    const database = DatabaseDescription(
      schemaNames: ['public'],
      tables: [
        TableDescription(
          schema: 'public',
          name: 'reviews',
          columns: [
            ColumnDescription(
              name: 'mood',
              postgresFormat: 'public.mood',
              typeKind: ColumnTypeKind.enumType,
              isRequired: true,
              hasDefault: false,
              isNullable: false,
            ),
          ],
        ),
      ],
      enums: [],
    );

    expect(() => generateDartCode(database), throwsArgumentError);
  });

  test('the header records the metadata version of the document', () {
    final code = generateDartCode(
      const DatabaseDescription(
        metadataVersion: 2,
        schemaNames: ['public'],
        tables: [],
        enums: [],
      ),
    );

    expect(code, contains('from GeneratorMetadata version 2.'));
  });

  test('encodes hostile schema names and import URIs in the header', () {
    final code = generateDartCode(
      DatabaseDescription(
        schemaNames: const ['evil\nimport "dart:io";', 'public'],
        tables: const [],
        enums: const [],
      ),
      importUri: "package:postgrest/postgrest.dart'; import 'dart:io",
    );

    expect(code, isNot(contains('evil\nimport')));
    expect(code, contains('// Source schemas: evil import "dart:io";, public'));
    expect(
      code,
      contains(
        "import 'package:postgrest/postgrest.dart\\'; "
        "import \\'dart:io';",
      ),
    );
  });

  test('schema names shadowing core or imported types are suffixed', () {
    final code = generateDartCode(
      DatabaseDescription(
        schemaNames: const ['public'],
        tables: const [
          TableDescription(
            schema: 'public',
            name: 'postgrest_table',
            columns: [
              ColumnDescription(
                name: 'name',
                postgresFormat: 'text',
                typeKind: ColumnTypeKind.text,
                isRequired: true,
                hasDefault: false,
                isNullable: false,
              ),
            ],
          ),
        ],
        enums: const [
          EnumDescription(schema: 'public', name: 'string', values: ['a']),
        ],
      ),
    );

    expect(code, contains('enum String\$ '));
    expect(code, contains('final String wireName;'));
    expect(code, isNot(contains('extension type const PostgrestTable._')));
  });

  test('a member named like a generated type is suffixed', () {
    const method = EnumDescription(
      schema: 'public',
      name: '2fa_method',
      values: ['totp'],
    );
    final code = generateDartCode(
      const DatabaseDescription(
        schemaNames: ['public'],
        tables: [
          TableDescription(
            schema: 'public',
            name: 'logins',
            columns: [
              ColumnDescription(
                name: '2fa_method',
                postgresFormat: '2fa_method',
                typeKind: ColumnTypeKind.enumType,
                enumType: method,
                isRequired: true,
                hasDefault: false,
                isNullable: false,
              ),
            ],
          ),
        ],
        enums: [method],
      ),
    );

    expect(code, contains(r'enum $2faMethod {'));
    expect(code, contains(r'$2faMethod get $2faMethod$ =>'));
    expect(
      code,
      contains(r'const $2faMethod$ = PostgrestColumn<LoginsRow, $2faMethod>('),
    );
  });

  test('an enum named like the error the parser throws is suffixed', () {
    final code = generateDartCode(
      DatabaseDescription(
        schemaNames: const ['public'],
        tables: const [],
        enums: const [
          EnumDescription(
            schema: 'public',
            name: 'argument_error',
            values: ['a'],
          ),
        ],
      ),
    );

    expect(code, contains('enum ArgumentError\$ '));
    expect(code, contains('throw ArgumentError.value('));
  });

  test('members named like a core type are suffixed', () {
    final code = generateDartCode(hostileSchema);

    expect(code, contains("int get num\$ => _json['num'] as int;"));
    expect(code, contains("num get int\$ => _json['int'] as num;"));
    expect(code, contains('static const num\$ = PostgrestColumn<'));
    expect(code, contains('static const int\$ = PostgrestColumn<'));
    expect(code, contains('static const bool\$ = PostgrestComputedField<'));
    expect(code, contains('static const double\$ ='));
  });

  test('floating array elements convert through num', () {
    final code = generateDartCode(
      DatabaseDescription(
        schemaNames: const ['public'],
        tables: const [
          TableDescription(
            schema: 'public',
            name: 'metrics',
            columns: [
              ColumnDescription(
                name: 'samples',
                postgresFormat: '_float8',
                typeKind: ColumnTypeKind.array,
                elementTypeKind: ColumnTypeKind.floating,
                isRequired: true,
                hasDefault: false,
                isNullable: false,
              ),
            ],
          ),
        ],
        enums: const [],
      ),
    );

    expect(code, contains('List<double> get samples'));
    expect(code, contains('(element as num).toDouble()'));
  });

  test('database comments cannot escape generated doc comments', () {
    final code = generateDartCode(
      DatabaseDescription(
        schemaNames: const ['public'],
        tables: const [
          TableDescription(
            schema: 'public',
            name: 'books',
            comment: 'first\rimport "dart:io";\u2028second',
            columns: [
              ColumnDescription(
                name: 'id',
                postgresFormat: 'int8',
                typeKind: ColumnTypeKind.integer,
                isRequired: true,
                hasDefault: false,
                isNullable: false,
              ),
            ],
          ),
        ],
        enums: const [],
      ),
    );

    expect(code, contains('/// first'));
    expect(code, contains('/// import "dart:io";'));
    expect(code, contains('/// second'));
  });

  test('string literals escape unicode line separators', () {
    final code = generateDartCode(
      DatabaseDescription(
        schemaNames: const ['public'],
        tables: const [
          TableDescription(
            schema: 'public',
            name: 'books',
            columns: [
              ColumnDescription(
                name: 'line\u2028break',
                postgresFormat: 'text',
                typeKind: ColumnTypeKind.text,
                isRequired: true,
                hasDefault: false,
                isNullable: false,
              ),
            ],
          ),
        ],
        enums: const [],
      ),
    );

    expect(code, contains(r"'line\u{2028}break'"));
    expect(code, isNot(contains('line\u2028break')));
  });

  test('array elements convert like a column of their kind', () {
    final code = _normalize(generateDartCode(hostileSchema));
    final compact = code.replaceAll(' ', '');

    expect(
      compact,
      contains(
        "List<PostgrestDate>?getdays=>(_json['days']asList<dynamic>?)"
        "?.map((element)=>PostgrestDate.parse(elementasString)).toList();",
      ),
    );
    expect(
      compact,
      contains("'days':?days?.map((element)=>element.literal).toList(),"),
    );
    expect(
      compact,
      contains(
        "List<String\$>?getmoods=>(_json['moods']asList<dynamic>?)"
        "?.map((element)=>String\$.fromWire(elementasString)).toList();",
      ),
    );
    expect(
      compact,
      contains("'moods':?moods?.map((element)=>element.wireName).toList(),"),
    );
    expect(
      compact,
      contains(
        "List<PostgrestRange<int>>?getspans=>(_json['spans']asList<dynamic>?)"
        "?.map((element)=>PostgrestRange.parse(elementasString,int.parse))"
        ".toList();",
      ),
    );
    expect(
      compact,
      contains("'spans':?spans?.map((element)=>element.literal).toList(),"),
    );
    expect(
      compact,
      contains(
        "List<DateTime>?getstamps=>(_json['stamps']asList<dynamic>?)"
        "?.map((element)=>DateTime.parse(elementasString)).toList();",
      ),
    );
    expect(
      compact,
      contains(
        "'stamps':?stamps?.map((element)=>element.toUtc().toIso8601String())"
        ".toList(),",
      ),
    );
    expect(
      compact,
      contains(
        "'shifts':?shifts?.map((element)=>element.render((bound)=>"
        "bound.toIso8601String()),).toList(),",
      ),
    );
    expect(
      compact,
      contains(
        "PostgrestNullableColumn<PostgrestTableRow,List<PostgrestDate>>"
        "('days',fromJson:_postgrestDateListFromJson",
      ),
    );
    expect(
      compact,
      contains(
        "PostgrestNullableColumn<PostgrestTableRow,List<PostgrestRange<int>>>"
        "('spans'",
      ),
    );
    // Elements without a conversion keep the lazy cast.
    expect(
      compact,
      contains(
        "List<String>?getembeddings=>(_json['embeddings']asList<dynamic>?)"
        "?.cast();",
      ),
    );
  });

  test('a required converted array renders its elements without a null '
      'check', () {
    final code = _normalize(
      generateDartCode(
        DatabaseDescription(
          schemaNames: const ['public'],
          tables: const [
            TableDescription(
              schema: 'public',
              name: 'events',
              columns: [
                ColumnDescription(
                  name: 'days',
                  postgresFormat: '_date',
                  typeKind: ColumnTypeKind.array,
                  elementTypeKind: ColumnTypeKind.date,
                  isRequired: true,
                  hasDefault: false,
                  isNullable: false,
                ),
              ],
            ),
          ],
          enums: const [],
        ),
      ),
    );

    final compact = code.replaceAll(' ', '');

    expect(
      compact,
      contains(
        "List<PostgrestDate>getdays=>(_json['days']asList<dynamic>)"
        ".map((element)=>PostgrestDate.parse(elementasString)).toList();",
      ),
    );
    expect(compact, contains('requiredList<PostgrestDate>days'));
    expect(
      compact,
      contains("'days':days.map((element)=>element.literal).toList()"),
    );
  });

  test('pgvector array elements stay wire strings', () {
    final code = generateDartCode(
      DatabaseDescription(
        schemaNames: const ['public'],
        tables: const [
          TableDescription(
            schema: 'public',
            name: 'events',
            columns: [
              ColumnDescription(
                name: 'embeddings',
                postgresFormat: '_vector',
                typeKind: ColumnTypeKind.array,
                elementTypeKind: ColumnTypeKind.vector,
                isRequired: true,
                hasDefault: false,
                isNullable: false,
              ),
            ],
          ),
        ],
        enums: const [],
      ),
    );

    expect(code, contains('List<String> get embeddings'));
    expect(code, contains("'embeddings': embeddings"));
  });

  test('tables whose columns are all read-only get parameterless '
      'insert and update constructors', () {
    final table = TableDescription(
      schema: 'public',
      name: 'counters',
      comment: null,
      columns: [
        ColumnDescription(
          name: 'id',
          postgresFormat: 'int8',
          typeKind: ColumnTypeKind.integer,
          isRequired: false,
          hasDefault: true,
          isNullable: false,
          isReadOnly: true,
        ),
      ],
    );
    final code = generateDartCode(
      DatabaseDescription(
        schemaNames: const ['public'],
        tables: [table],
        enums: const [],
      ),
    );

    expect(code, contains('CountersInsert() : this._({});'));
    expect(code, contains('CountersUpdate() : this._({});'));
    expect(code, contains("int get id => _json['id'] as int;"));
  });
  test('computed fields are constants next to the columns, with no row '
      'getter', () {
    final code = _normalize(generateDartCode(schema));
    final compact = code.replaceAll(' ', '');

    expect(
      compact,
      contains(
        "staticconsttitleUpper=PostgrestComputedField<BooksRow,String>("
        "'title_upper',);",
      ),
    );
    expect(
      compact,
      contains(
        "staticconstmoodOrDefault=PostgrestComputedField<BooksRow,Mood>("
        "'mood_or_default',fromJson:_moodFromJson,);",
      ),
    );
    expect(
      compact,
      contains(
        "staticconstdiscount=PostgrestComputedField<BookPricesRow,num>("
        "'discount',);",
      ),
    );
    expect(compact, contains('computedFields:[discount],'));
    expect(code, isNot(contains('get titleUpper')));
    expect(code, isNot(contains('get moodOrDefault')));
    expect(code, isNot(contains('get discount =>')));
    expect(code, isNot(contains('titleUpper,')));
    expect(code, isNot(contains('String? titleUpper')));
  });

  test('a function named like a column gets no computed field', () {
    final compact = _normalize(generateDartCode(schema)).replaceAll(' ', '');

    expect(
      compact,
      isNot(contains("PostgrestComputedField<BooksRow,String>('title'")),
    );
    expect(
      compact,
      contains("staticconsttitle=PostgrestColumn<BooksRow,String>('title');"),
    );
  });

  test('computed relationships embed through the function name', () {
    final compact = _normalize(generateDartCode(schema)).replaceAll(' ', '');

    expect(
      compact,
      contains(
        "///The`books`rowcomputedby`latest_book`."
        "staticconstlatestBook=PostgrestToOneRelation<AuthorsRow,BooksRow>"
        ".computed('latest_book',referencedTable:'books',);",
      ),
    );
    expect(
      compact,
      contains(
        "///The`books`rowscomputedby`recent_books`."
        "staticconstrecentBooks=PostgrestToManyRelation<AuthorsRow,BooksRow>"
        ".computed('recent_books',referencedTable:'books',);",
      ),
    );
    expect(
      compact,
      contains('relations:[authorStats,books,latestBook,recentBooks],'),
    );
  });

  test('computed field members are kept apart from reserved words, the '
      'table definition and the column constants', () {
    final compact = _normalize(
      generateDartCode(hostileSchema),
    ).replaceAll(' ', '');

    expect(
      compact,
      contains(
        "staticconstclass\$=PostgrestComputedField<PostgrestTableRow,String>("
        "'class',);",
      ),
    );
    expect(
      compact,
      contains(
        "staticconsttable\$=PostgrestComputedField<PostgrestTableRow,bool>("
        "'table',);",
      ),
    );
    expect(
      compact,
      contains(
        "staticconstquoteNameTail\$=PostgrestComputedField<PostgrestTableRow,"
        "int>('quote_name_tail',);",
      ),
    );
    expect(
      compact,
      contains(
        'computedFields:[class\$,table\$,quoteNameTail\$,moodsByWeight,'
        'thumbnail,],',
      ),
    );
  });

  test('computed fields decode through the helpers the columns share', () {
    final compact = _normalize(
      generateDartCode(hostileSchema),
    ).replaceAll(' ', '');

    expect(
      compact,
      contains(
        "staticconstmoodsByWeight=PostgrestComputedField<PostgrestTableRow,"
        "List<String\$>>('moods_by_weight',fromJson:_stringListFromJson\$,);",
      ),
    );
    expect(
      compact,
      contains(
        "staticconstthumbnail=PostgrestComputedField<PostgrestTableRow,"
        "Uint8List>('thumbnail',fromJson:_uint8ListFromJson,);",
      ),
    );
    expect(
      'List<String\$>_stringListFromJson\$(Objectjson)'.allMatches(compact),
      hasLength(1),
    );
    expect(
      'Uint8List_uint8ListFromJson(Objectjson)'.allMatches(compact),
      hasLength(1),
    );
  });

  test('computed relationships reach the table itself and tables of other '
      'schemas', () {
    final compact = _normalize(
      generateDartCode(hostileSchema),
    ).replaceAll(' ', '');

    expect(
      compact,
      contains(
        "staticconstparent=PostgrestToOneRelation<MapRow,MapRow>.computed("
        "'parent',referencedTable:'map',);",
      ),
    );
    expect(
      compact,
      contains(
        "staticconstchildren=PostgrestToManyRelation<MapRow,MapRow>.computed("
        "'children',referencedTable:'map',);",
      ),
    );
    expect(
      compact,
      contains(
        "staticconstpostgrestColumn=PostgrestToManyRelation<PostgrestTableRow,"
        "EvilMultilineSchemaNamePostgrestColumnRow>.computed("
        "'postgrest_column',referencedTable:'postgrest_column');",
      ),
    );
    expect(
      compact,
      contains('relations:[mapByMood,mapByDays,map,postgrestColumn],'),
    );
  });

  test('a computed relationship into a table without columns gets no '
      'member', () {
    const database = DatabaseDescription(
      schemaNames: ['public'],
      tables: [
        TableDescription(
          schema: 'public',
          name: 'todos',
          columns: [
            ColumnDescription(
              name: 'id',
              postgresFormat: 'int8',
              typeKind: ColumnTypeKind.integer,
              isRequired: true,
              hasDefault: false,
              isNullable: false,
            ),
          ],
          computedRelationships: [
            ComputedRelationshipDescription(
              name: 'audit',
              targetSchema: 'public',
              targetTable: 'empty',
              isToMany: true,
            ),
          ],
        ),
        TableDescription(schema: 'public', name: 'empty', columns: []),
      ],
      enums: [],
    );

    final code = _normalize(generateDartCode(database));

    expect(code, isNot(contains('relations:')));
    expect(code, isNot(contains('audit')));
  });

  test('a computed relationship named like a foreign key embed replaces '
      'it', () {
    const id = ColumnDescription(
      name: 'id',
      postgresFormat: 'int8',
      typeKind: ColumnTypeKind.integer,
      isRequired: true,
      hasDefault: false,
      isNullable: false,
    );
    const database = DatabaseDescription(
      schemaNames: ['public'],
      tables: [
        TableDescription(
          schema: 'public',
          name: 'authors',
          columns: [id],
          // PostgREST resolves `authors(*)` on books to this function, so the
          // detected foreign key embed is unreachable by its plain name.
          computedRelationships: [
            ComputedRelationshipDescription(
              name: 'books',
              targetSchema: 'public',
              targetTable: 'books',
              isToMany: true,
            ),
          ],
        ),
        TableDescription(
          schema: 'public',
          name: 'books',
          columns: [
            id,
            ColumnDescription(
              name: 'author_id',
              postgresFormat: 'int8',
              typeKind: ColumnTypeKind.integer,
              isRequired: true,
              hasDefault: false,
              isNullable: false,
            ),
          ],
          computedRelationships: [
            ComputedRelationshipDescription(
              name: 'authors',
              targetSchema: 'public',
              targetTable: 'authors',
              isToMany: false,
            ),
          ],
        ),
      ],
      relationships: [
        RelationshipDescription(
          foreignKeyName: 'books_author_id_fkey',
          sourceSchema: 'public',
          sourceTable: 'books',
          sourceColumns: ['author_id'],
          targetSchema: 'public',
          targetTable: 'authors',
          targetColumns: ['id'],
        ),
      ],
      enums: [],
    );

    final compact = _normalize(generateDartCode(database)).replaceAll(' ', '');

    expect(
      compact,
      contains(
        "staticconstauthors=PostgrestToOneRelation<BooksRow,AuthorsRow>"
        ".computed('authors',referencedTable:'authors',);",
      ),
    );
    expect(
      compact,
      contains(
        "staticconstbooks=PostgrestToManyRelation<AuthorsRow,BooksRow>"
        ".computed('books',referencedTable:'books',);",
      ),
    );
    expect(compact, isNot(contains("('authors',columns:")));
    expect(compact, isNot(contains("('books',columns:")));
    expect(compact, contains('relations:[authors],'));
    expect(compact, contains('relations:[books],'));
  });

  test('a bytea computed field alone brings the typed_data import', () {
    const database = DatabaseDescription(
      schemaNames: ['public'],
      tables: [
        TableDescription(
          schema: 'public',
          name: 'todos',
          columns: [
            ColumnDescription(
              name: 'id',
              postgresFormat: 'int8',
              typeKind: ColumnTypeKind.integer,
              isRequired: true,
              hasDefault: false,
              isNullable: false,
            ),
          ],
          computedFields: [
            ComputedFieldDescription(
              name: 'thumbnail',
              postgresFormat: 'bytea',
              typeKind: ColumnTypeKind.binary,
            ),
          ],
        ),
      ],
      enums: [],
    );

    final code = generateDartCode(database);

    expect(code, contains("import 'dart:typed_data';"));
    expect(code, contains('PostgrestComputedField<TodosRow, Uint8List>'));
  });
}
