name: supabase_flutter
description: Flutter integration for Supabase. This package makes it simple for developers to build secure and scalable products.
version: 2.15.3
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/supabase_flutter'
documentation: 'https://supabase.com/docs/reference/dart/introduction'

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  app_links: '>=6.2.0 <8.0.0'
  async: ^2.11.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  meta: ^1.7.0
  passkeys_platform_interface: ^2.8.0
  supabase: 2.13.3
  url_launcher: ^6.1.2
  shared_preferences: ^2.0.0
  logging: ^1.2.0
  web: '>=0.5.0 <2.0.0'

dev_dependencies:
  dart_jsonwebtoken: ">=2.17.0 <4.0.0"
  flutter_test:
    sdk: flutter
  supabase_lints: ^0.1.0
  web_socket_channel: '>=2.3.0 <4.0.0'

platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux:

flutter:
