-- Schema, functions and tables exercised by the postgrest_client tests.
-- Ported from the former infra/postgrest/db/00-schema.sql.

-- Second schema, exposed through the Data API for the schema-switching tests.
create schema if not exists personal;

-- USERS
create type public.user_status as enum ('ONLINE', 'OFFLINE');
create table public.users (
  username text primary key,
  data jsonb default null,
  age_range int4range default null,
  status user_status default 'ONLINE'::public.user_status,
  catchphrase tsvector default null,
  interests text[] default null
);
alter table public.users replica identity full;
comment on column public.users.data is 'For unstructured data and prototyping.';

-- CHANNELS
create table public.channels (
  id bigint generated by default as identity primary key,
  data jsonb default null,
  slug text
);
alter table public.channels replica identity full;
comment on column public.channels.data is 'For unstructured data and prototyping.';

-- MESSAGES
create table public.messages (
  id bigint generated by default as identity primary key,
  data jsonb default null,
  message text,
  username text references users not null,
  channel_id bigint references channels not null,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.messages replica identity full;
comment on column public.messages.data is 'For unstructured data and prototyping.';

-- REACTIONS
create table public.reactions (
  id bigint generated by default as identity primary key,
  emoji text not null,
  message_id bigint references messages not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- STORED FUNCTIONS
create function public.get_status(name_param text)
returns user_status as $$
  select status from users where username = name_param;
$$ language sql immutable;

create function public.get_username_and_status(name_param text)
returns table(username text, status user_status) as $$
  select username, status from users where username = name_param;
$$ language sql immutable;

create function public.void_func()
returns void as $$
$$ language sql;

create function public.get_integer()
returns integer as $$
begin
  return 42;
end;
$$ language plpgsql;

create function public.get_array_element(arr integer[], index integer)
returns integer as $$
begin
  return arr[index];
end;
$$ language plpgsql;

-- SECOND SCHEMA USERS
create type personal.user_status as enum ('ONLINE', 'OFFLINE');
create table personal.users(
  username text primary key,
  data jsonb default null,
  age_range int4range default null,
  status user_status default 'ONLINE'::public.user_status
);

-- SECOND SCHEMA STORED FUNCTION
create function personal.get_status(name_param text)
returns user_status as $$
  select status from users where username = name_param;
$$ language sql immutable;

-- UPPERCASE TABLE NAME
create table public."TestTable" (
  id bigint generated by default as identity primary key,
  slug text
);

-- ROW LEVEL SECURITY ERROR TEST
create table public.sample (
  id bigint generated by default as identity primary key,
  name text not null
);
alter table public.sample enable row level security;

-- GEOJSON TEST and POSTGIS SUPPORT
create extension if not exists postgis with schema extensions;

create table public.addresses (
  id bigint generated by default as identity primary key,
  username text references users not null,
  location extensions.geometry(POINT, 4326)
);

-- Test table for UPSERT & onConflict
create table public.imported_data (
  id bigint generated by default as identity primary key,
  external_id text not null,
  source_system text not null,
  data jsonb default null,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(external_id, source_system)
);

-- Long-running task for testing abortion
create or replace function public.long_running_task()
returns void as $$
declare
  start_time timestamp := clock_timestamp();
begin
  while clock_timestamp() < start_time + interval '10 seconds' loop
    PERFORM pg_sleep(0.1);
  end loop;
end;
$$ language plpgsql;

-- Enable PostgREST's EXPLAIN/plan output for the .explain() tests (the previous
-- Docker setup set PGRST_DB_PLAN_ENABLED=1). PostgREST reads this from the
-- authenticator role on startup.
alter role authenticator set pgrst.db_plan_enabled = 'true';

-- Expose the public and personal schema entities to the Data API roles. The
-- postgrest tests authenticate as service_role; granting here keeps the test
-- tables reachable without relying on the deprecated api.auto_expose_new_tables.
grant usage on schema public, personal to anon, authenticated, service_role;
grant all on all tables in schema public, personal to anon, authenticated, service_role;
grant all on all functions in schema public, personal to anon, authenticated, service_role;
grant all on all sequences in schema public, personal to anon, authenticated, service_role;
alter default privileges in schema public, personal
  grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public, personal
  grant all on sequences to anon, authenticated, service_role;
