name: supabase_example
description: An absolute bare-bones supabase web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  web: '>=0.5.0 <2.0.0'
  supabase: ^2.9.0

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.6
  lints: ^4.0.0

