name: supabase_example
description: An absolute bare-bones supabase web app.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  web: '>=0.5.0 <2.0.0'
  supabase: ^2.9.0

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  lints: ^4.0.0

