name: Block WIP/Draft Merges

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  block-merge:
    uses: supabase/actions/.github/workflows/block-merge.yml@2e898cb306c525525ad3f0b34c6f0ab1e3f8ba87
    with:
      block_labels: "do-not-merge,blocked"
      block_keywords: "wip,do not merge"
