name: Publish Packages

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: 'Name of the package to publish'
        required: true
        type: string
      package-version:
        description: 'Version to publish (without v prefix, e.g. 2.18.0)'
        required: true
        type: string

concurrency:
  group: release-publish-${{ inputs.package-name }}
  cancel-in-progress: false

permissions:
  contents: write
  id-token: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: ${{ inputs.package-name }}-v${{ inputs.package-version }}

      - name: Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          cache: true

      - name: Publish to pub.dev and create GitHub Release
        uses: bluefireteam/melos-action@2982f8e4fc92440a219490009d6d05195cb1a6a5 # v3.8.0
        with:
          publish: true
          create-release: true
          token: ${{ steps.app-token.outputs.token }}
