name: SDK Compliance

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    permissions:
      contents: read
      pull-requests: write
    uses: supabase/sdk/.github/workflows/validate-sdk-compliance-dart.yml@2a4d008ba8e6815e4a94fab59a54a2f202d489a5 # capability-matrix/v1.14.0