name: SDK Compliance

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    permissions:
      contents: read
      pull-requests: write
    uses: supabase/sdk/.github/workflows/validate-sdk-compliance-dart.yml@9e71603c5d8410255493d264738e5c5f64251735 # capability-matrix-v1.12.0