name: SDK Compliance

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    permissions:
      contents: read
      pull-requests: write
    uses: supabase/sdk/.github/workflows/validate-sdk-compliance-dart.yml@63c1ac1d44959bfd02e4fc70a09df287db4a425a # v1.1.1